### ISSUE TITLE
Local compose : Ctrl-C on "up" runs "down", it should only stop containers

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#1031]
behaviour difference between `docker compose` and `docker-compose`

**Comment by ulyssessouza** [comment]
Looks like @ndeloof already implemented that!
https://github.com/docker/compose-cli/blob/main/cli/cmd/compose/up.go#L109

@gtardif Can you confirm

**Comment by ulyssessouza** [comment]
Closed by https://github.com/docker/compose-cli/pull/1163
