### ISSUE TITLE
Local compose: make 'convert' command specific to ECS context

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#1034]
it currently appears in the global list of commands when typing `docker compose` or `docker compose --help`, and it's quite specific to ECS

**Comment by ndeloof** [comment]
Code still make sense on local compose as implementation for `docker-compose config`

**Comment by gtardif** [comment]
Yes, we need to change the command name (or have an alias) to `config`. 
default output should be compose yaml, and we have flags for cloudformation output or later kube(helm) output

**Comment by gtardif** [comment]
Done as a side effect of other tickets, config is an alias for convert, available on different backends
