### ISSUE TITLE
It would be nice to have build in method of service dependency

### ISSUE THREAD

**Issue by dmikov** [docker/compose-cli#1045]
Docker-compose has depends_on property which is not really useful for applications running, just for dependency tracking. It would be nice to have some specific to compose functionality either build-in or external script/function-based, that does not require building it up into image and modifying default entry points. This is not an image property, but a service collection property.

**Comment by ndeloof** [comment]
`depends_on` defines `condition: service_healthy` so a service will wait for his dependencies to be ready.
Please note this project is not about evolving the compose file format and concepts, see https://github.com/compose-spec/compose-spec if you want to suggest improvements / new concepts
