### ISSUE TITLE
docker compose (experimental): container names 

### ISSUE THREAD

**Issue by EdSF** [docker/compose-cli#1046]
Running the experimental `docker compose` does not use the defined `container_name` in docker-compose.yml (while running `docker-compose up` does.

Note: I actually "stumbled" on this by forgetting the dash `-` (while not in Azure CLI context). 

Having said that, when using the Azure CLI context, which only supports `docker compose` (no dash), this occurs there too. If you have network resources that depend on `container_name` for connections (re: between containers), these will fail (names defined in compose file aren't used).

**Steps to reproduce the issue:**
1. Define `container_name` for your services in `docker-compose.yml`
2. run the new/experimental `docker compose` (no dash)
3. Everything succeeds, but the container names _looks like_ some combination of `services` names + numeric suffix

**Describe the results you received:**

Container names look "generated" from `services` names defined in docker-compose.yml with a numeric suffix

**Describe the results you expected:**

Container names as defined in `container-name` key in compose file - in other words, just like what you'd expect running `docker-compose up`

**Comment by gtardif** [comment]
Thanks for the feedback, indeed we know we don't have full support for all compose features yet, we'll prioritize this in our next improvements in local compose. 
... And also try to match this in ACI as you mentioned, this is not available in ACI either

**Comment by EdSF** [comment]
> Thanks for the feedback, indeed we know we don't have full support for all compose features yet, we'll prioritize this in our next improvements in local compose.
> ... And also try to match this in ACI as you mentioned, this is not available in ACI either

Thank you! 

I was in an Azure webinar a couple of days ago and I had this question for them (ACI/ACR) because I couldn't figure out the container naming (and thought it was an `Azure CLI` issue) while trying things out based on [Tutorial: Deploy a multi-container group using Docker Compose](https://docs.microsoft.com/en-us/azure/container-instances/tutorial-docker-compose)(and experienced the network connection issue..)

**Comment by ndeloof** [comment]
AFAIK @aiordache fixed this as part of her implementation of `compose run`
