### ISSUE TITLE
docker compose: usage help section is incomplete

### ISSUE THREAD

**Issue by mskutin** [docker/compose-cli#1061]
Usage section is quite generic, it doesn't specify format for all args and options.

<details>
  <summary>docker compose:</summary>
  
  ```bash
Docker Compose

Usage:
  docker compose [command]
```
  
</details>

<details>
  <summary>docker-compose:</summary>
  
```bash
Usage:
  docker-compose [-f <arg>...] [options] [--] [COMMAND] [ARGS...]
  docker-compose -h|--help
```
</details>

**Comment by ndeloof** [comment]
Thanks for reporting this.

`docker-compose [-f <arg>...] [options] [--] [COMMAND] [ARGS...]`  is not really usefull either as the actual support for option and args depends on the selected command ... This is really just a very generic "unix command line syntax".

`docker compose` align with the docker CLI to list subcommands and general options. See for sample `docker` top level ouput:

```console
➜  ~ docker
Usage:
  docker [flags]
  docker [command]

Available Commands:
...
Flags:
      --config DIRECTORY   Location of the client config files DIRECTORY (default "/home/nicolas/.docker")
...
```

**Comment by mskutin** [comment]
I see, that's a fair point. Although I believe my initial confusion was about absence of `-f ` which is present in docker-compose usage output, do you think it should be a part of "Global Flags"? I think since every single command that is currently present in docker compose requires it in case when `docker-compose.yml` file name is non-default?

**Comment by ndeloof** [comment]
I also think `-f` (and `--project-name`) should be Global flags, just like they do in docker-compose, so that tools can be used as a drop-in replacement in users scripts.

IIUC the initial intent was to relocate those flags under subcommands as some command might not require those (typically: `docker compose ls`)

**Comment by ndeloof** [comment]
I created https://github.com/docker/compose-cli/issues/1069 for this purpose
