### ISSUE TITLE
Install docker CLI 20.10 on GHA nodes

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#1063]
Some CI test did not detect issues due to CLI interaction with /docker/cli v20.10. 
See https://github.com/docker/compose-cli/pull/1062

We need to replace default docker installed on CLI with CLI 20.10

**Comment by gtardif** [comment]
We also need to install 20.10 on windows nodes, and re-enable local compose e2e on windows, cf https://github.com/docker/compose-cli/pull/1068

**Comment by ulyssessouza** [comment]
@gtardif For the windows side I just need a way to get the binary from somewhere.
