### ISSUE TITLE
The submitted information didn't contain changes. Submit different information to create a change set.

### ISSUE THREAD

**Issue by SEFI2** [docker/compose-cli#1074]
**Description**

I am getting this message, even though I have changes and want to deploy them:
`The submitted information didn't contain changes. Submit different information to create a change set.`

**Steps to reproduce the issue:**
1. docker-compose up --context myecscontext

**Describe the results you received:**
As I understood, compose-cli cannot create a changeset after creating a template, but couldn't get where exactly it fails.

**Describe the results you expected:**
I had a lot of things changed: `code`, `Dockerfiles`, and `docker-compose`, but still it shows this information.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
docker-compose version 1.27.4, build 40524192
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
[
    {
        "Name": "myecscontext",
        "Metadata": {
            "Type": "ecs"
        },
        "Endpoints": {
            "docker": {
                "SkipTLSVerify": false
            },
            "ecs": {
                "Profile": "default"
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "/Users/kadyrbeknarmamatov/.docker/contexts/meta/8bb20fb47c4248774ab660063891d2332facb5997d914f61b3bdfeb471eaddba",
            "TLSPath": "/Users/kadyrbeknarmamatov/.docker/contexts/tls/8bb20fb47c4248774ab660063891d2332facb5997d914f61b3bdfeb471eaddba"
        }
    }
]
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 8
  Running: 0
  Paused: 0
  Stopped: 8
 Images: 74
 Server Version: 20.10.0
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: UBPC:NEYF:75X4:7XJD:J62Q:IWU3:K5NU:5B2C:UEMU:Z46M:NO5W:H2EB
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 43
  Goroutines: 49
  System Time: 2020-12-16T20:48:03.4052923Z
  EventsListeners: 4
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by ndeloof** [comment]
If you updated code and built/push updated images under same tag, this is a know limitation: From CloudFormation point of view the mode hasn't been updated - we plan to use image digest as the app is deployed to enforce the image being used by service is the one you expected by the time you run `compose up`, just like implemented by https://github.com/docker/app

If you made any other change to your compose file, can you please share a diff ? 

Unfortunatelly the CloudFormation API doesn't make it simple to catch this specific error

**Comment by SEFI2** [comment]
@ndeloof Thanks for the response, that is very helpful! Actually, turns out that I was changing only the `build` parameter of the compose file, which, as you know, is not supported by `ecs`, so that's why it was not able to recognize any change that was made.
 
 Right now, in order to propagate my build changes or any change, I am just adding `environment` variable called `UPDATE=1` and changing the value of it after each build, didn't find anything better so far.
