### ISSUE TITLE
Buckets created to hold large cloudformation templates do not have unique names. Perhaps include AWS account number?

### ISSUE THREAD

**Issue by geoffian** [docker/compose-cli#1077]
See below we get bucket name created to hold templates > 51200 are not available as the bucket name is always set as follows:

bucket := "com.docker.compose." + region

https://github.com/docker/compose-cli/blob/b2b9ce0a53d1509a5918e5fa73a959f2f7975d80/ecs/sdk.go#L273-L286

zammad-docker-compose % docker compose up -D
DEBU[0000] CheckRequirements on VPC : vpc-xxxxxx      
DEBU[0000] Retrieve SubNets                             
DEBU[0000] searching for existing filesystem as volume "elasticsearch-data" 
DEBU[0001] searching for existing filesystem as volume "postgresql-data" 
DEBU[0001] searching for existing filesystem as volume "zammad-backup" 
DEBU[0001] searching for existing filesystem as volume "zammad-data" 
DEBU[0002] Create CloudFormation stack                  
DEBU[0002] Create s3 bucket to store cloudformation template 
DEBU[0003] Stack  created                               
BucketAlreadyExists: The requested bucket name is not available. The bucket namespace is shared by all users of the system. Please select a different name and try again.

**Comment by chris-crone** [comment]
Arg. Thanks for reporting this @geoffian! I'll add it to our backlog so that we can tackle it when the team is back in the new year.

**Comment by ndeloof** [comment]
"The bucket namespace is shared by all users of the system" :scream:

**Comment by jorgecuevas92** [comment]
Currently getting this error with a large template, are there any workarounds that we can try while the team finds time to fix this bug?

**Comment by trauts2** [comment]
This is an issue for us.  Any suggested workarounds?
