### ISSUE TITLE
ECS: Stickiness support to allow Socket.IO applications

### ISSUE THREAD

**Issue by robogeek** [docker/compose-cli#1088]
**Description**

I have a simple _Socket_._IO_ application that when deployed to ECS using Compose w/ ECS Context it fails when there are multiple instances deployed.  With one instance (`replicas: 1`) the application functions correctly, but with more instances it fails.

_Socket_._IO_ is a framework for doing WebSockets between server and client, supporting semi-real-time communication between multiple clients.  I've deployed this application into several contexts - straight Docker - Docker Swarm - and now ECS.  The failure mode with both Swarm and ECS is the same, and the solution for both is the same.  Namely, to implement sticky sessions.

There are surely other kinds of applications that require sticky sessions.  For _Socket_._IO_ the issue is that if the session cookie lands on a server that doesn't recognize the session ID, then the request is rejected as an error.

With _Socket_._IO_ this is a known issue, and there is a known solution involving using a REDIS server to share session data between instances.  The application in question does implement that solution, but in this case it does not help.  The only thing which helped was to turn on sticky sessions.  When deploying to Docker Swarm that meant using Traefik as the load balancer in front of the application, and using its sticky session support.  When deploying to ECS there is a _Stickiness_ setting on the Load Balancer Target Group, and when enabled the application works correctly.

**Steps to reproduce the issue:**
1.  Deploy the application to ECS
2. Notice that with one instance it works perfectly
3. Notice that with two or more instances it fails, and in the browser console log there is a constant stream of errors

**Describe the results you received:**

This is the Compose file.

```
version: '3.8'

services:
    todo:
        image: robogeek/todo-app:first-dockerize-redis
        ports:
          - "80:80"
        # deploy:
        #   replicas: 5
        environment:
            - SEQUELIZE_CONNECT=models/sequelize-sqlite.yaml
            - REDIS_ENDPOINT=redis.todo-docker-ecs.local
            - DEBUG=todos:*,ioredis:*,socket.io:*,engine

    redis:
        image: redis
```

The `DEBUG` variable turns on debugging output sufficient to see traffic to/from the client.  An additional variable can be set (`- NODE_DEBUG=redis`) that will turn on tracing of the REDIS connection.  The `REDIS_ENDPOINT` value should be modified to the correct Compose Project Name, or else you should run it with `--project-name`.  The `SEQUELIZE_CONNECT` variable is a YAML file to specify a database configuration.  With this setting it uses SQLite3 and stores the data inside the container, which of course means that any notes created in the application will not be shared between instances, but that's not necessary to see the problem called out by this report.

You can easily disable REDIS by commenting out the `redis` service and the `REDIS_ENDPOINT` variable.

When the application starts - the page is empty, but there is a `+` icon at the top.  Click on that to add a TODO item.  You have to select a priority.  If the application is working, the popup will dismiss when you click the Submit button, and the TODO item will appear on the screen, and further if there are multiple browser windows the item will appear on each window.  If the application is failing, the popup will not dismiss, and nothing shows up in the window, and error messages will show up in the browser console log.

A critical piece of the logging output is this:

```
todo    | 2020-12-29T19:12:47.711Z engine intercepting request for path "/socket.io/"
todo    | 2020-12-29T19:12:47.711Z engine handling "POST" http request "/socket.io/?EIO=3&transport=polling&t=NQlwiOE&sid=1D9aYvoEqfBsoVTJAAAG"
todo    | 2020-12-29T19:12:47.711Z engine unknown sid "1D9aYvoEqfBsoVTJAAAG"
```

Requests coming from the _Socket_._IO_ client arrive on the `/socket.io/` URL, so this shows one such request being intercepted by the server-side code.  And, it says the session ID is not recognized.

The sticky session support is required to ensure the request lands on the correct service instance.

**Describe the results you expected:**

What's needed is a mechanism to configure the _Stickiness_ attribute of an AWS Target Group.

It's possible to go into the Target Group dashboard page and manually add this attribute.  It's possible to do so using the AWS CLI:

```
aws elbv2 modify-target-group-attributes \
            --target-group-arn $TGARN \
            --attributes Key=stickiness.enabled,Value=true
```

Once this is enabled the application will work correctly.

One possible solution is an `x-aws-` attribute to the long form `ports` specification, like:

```
ports:
    - target: 80
       published: 80
       x-aws-target-group-sticky: true
```

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.0
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        7287ab3
 Built:             Tue Dec  8 18:55:43 2020
 OS/Arch:           darwin/amd64
 Context:           ecs-env
 Experimental:      true
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
```

**Output of `docker context show`:**  

```
$ docker context show
ecs-env
$ docker context inspect ecs-env
[
    {
        "Name": "ecs-env",
        "Metadata": {
            "Description": "credentials read from environment",
            "Type": "ecs"
        },
        "Endpoints": {
            "docker": {
                "SkipTLSVerify": false
            },
            "ecs": {
                "CredentialsFromEnv": true
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "/Users/david/.docker/contexts/meta/680fd64ab74e714ddd488483239eeeb3c4e2e99e10f7a853b73e99d0e4158454",
            "TLSPath": "/Users/david/.docker/contexts/tls/680fd64ab74e714ddd488483239eeeb3c4e2e99e10f7a853b73e99d0e4158454"
        }
    }
]
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

It's deployed to AWS ECS -- I have Docker Desktop for Mac 3.0.x installed, hence am using 20.10.0

**Comment by ndeloof** [comment]
With recently introduced support for Cloudformation overlays, you can set stickyness attribute on your TargetGroup with:

```yaml
Resources 
  FooBarTargetGroup:
    Properties:
      TargetGroupAttributes:
        - Key: stickiness.enabled
          Value: true
        - Key: deregistration_delay.timeout_seconds
          Value: 30
```

see https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticloadbalancingv2-targetgroup-targetgroupattribute.html for details
