### ISSUE TITLE
ECS: Config option to turn off creation of load balancer resources

### ISSUE THREAD

**Issue by robogeek** [docker/compose-cli#1089]
There are several issues with the current ECS Context related to the configuration of the AWS Load Balancer.  The semantics of the Load Balancer don't fit well with semantics of the Compose file. 

I see there are two possible directions to take:

1. Come up with additions to the Compose specification or else additional `x-aws-` settings so that we can describe important Load Balancer configuration scenarios without having to resort to Cloud Formation or Terraform
2. Make it possible to tell the ECS Context to not create Load Balancer Listeners, Rules and Target Groups, and instead to funnel traffic into the target group or listener of an externally created load balancer

The several issues I've identified are:

1. Cannot set up HTTPS/SSL support
2. Cannot assign domain names to services
3. Cannot set sticky sessions -- Some applications require sticky sessions. See:  #1088 
4. The Health Check semantics do not work for all applications -- For example I recently tried deploying Kanboard to ECS.  It's `/` URL is a 301 redirect to `/login`, which the default health check deems is unhealthy and after a few moments ECS forces the container to be destroyed and recreated.

What I see is that when specifying:

```
x-aws-loadbalancer: ${ALB_ARN}
```

If the ALB created by my code has Listeners/Rules/Target Groups, then `docker compose up` dies with this message:

```
Resource of type 'AWS::ElasticLoadBalancingV2::Listener' with identifier 'A listener already exists on this port for this load balancer 'arn:aws:elasticloadbalancing:us-west-2:09E1X6A8MPLE:loadbalancer/app/wp-ecs-load-balancer/031fb204d4ee0d00' (Service: ElasticLoadBalancingV2, Status Code: 400, Request ID: ea5b2a3e-268c-4f2d-9db5-42985039bf25, Extended Request ID: null)' already exists.
```

Obviously, the ECS Context is insisting that it create the Listeners/Rules/Target Groups, and sees mine as an error.

It's fairly easy to create a Load Balancer configuration that supports all those features (and more), and at lower computation cost to the service.

Obviously each Service must be connected to a Target Group.  In an ECS Service, the `target_group_arn` declares which Target Group the service is supposed to connect to.  Hence, in the `deploy` attribute for a service there could be a `x-aws-target-group-arn` attribute for that purpose.

In such a case the Service might not need a `ports` attribute at all, because declaration of the Listeners would occur in the load balancer.  That is, an externally declared AWS Load Balancer would have its own Listeners, and what's needed is for Services to connect to the Target Groups.  Therefore the Services do not need to declare `ports`.

The top-level `x-aws-loadbalancer` attribute might become:

```
x-aws-loadbalancer:
     external: true
     arn: ${ALB_ARN}
```

**Comment by danbo0001** [comment]
oh no, i just read this and it has put a spanner in my plans to use this for my next ecs implementation - i thought with the cli adding in support for referencing external lb's and security groups etc then it would also be able to reference external listeners/rules/tg's. i have to create listener's and rules in cloudformation/cdk because it all wires up to my dns, it cannot be created here.

so i would like to add my support to this request to remove more types of resources from needing to be generated by this cli, specifically listeners and rules, but target groups as well if possible.

**Comment by ndeloof** [comment]
afaict CloudFormation overlays is a better approach to this problem and make this issue obsolete, right?

**Comment by danbo0001** [comment]
errr would you mind giving a small explanation of that before closing the issue....

**Comment by ndeloof** [comment]
sure, sorry => read more on https://github.com/docker/compose-cli/issues/1115 and user-facing documentation https://deploy-preview-12080--docsdocker.netlify.app//cloud/ecs-integration/#tuning-the-cloudformation-template

**Comment by danbo0001** [comment]
ok cool thanks, i will read through and give it a try - as long as i can configure everything i need in the compose file, it should be fine :)
