### ISSUE TITLE
(feat): Suppress warn message

### ISSUE THREAD

**Issue by lukasmrtvy** [docker/compose-cli#1108]
Would be nice to be able somehow suppress warn message: `The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli` for better machine parsing..
Thanks

**Comment by ndeloof** [comment]
IMHO it would make sense indeed for user to has some acknowledge mechanism so they don't get this warning, comparable to CLI plugins enablement. Maybe we could skip this message when some environment variable is set?
cc @nebuk89

**Comment by chris-crone** [comment]
+1 We could also not show it after x runs or something.

**Comment by thaJeztah** [comment]
We could have a look at reinstating the global `--log-level` flag that's present on the `docker` CLI (and add it to the `~/.docker/config.json`);

```
  -l, --log-level string   Set the logging level ("debug"|"info"|"warn"|"error"|"fatal") (default "info")
```

That option was mostly inherited from when the CLI and Daemon were a single binary (many/most parts of the cli currently ignore it, but perhaps it's a good one for this?)

**Comment by chris-crone** [comment]
Yep, that's an option too.

We should also decide what is required for us to be comfortable removing the warning all together. I think everyone wants this to just be GA :)

**Comment by gabrieldemarmiesse** [comment]
One easy solution to allow parsing of outputs would be to print this warning to stderr instead of stdout (it's currently printed to stdout). 
```
$ docker compose -f dummy_compose.yml  ps --quiet 2>/dev/null
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
809a979544d62b8777823baadbd1424a4be5f2ccf20641cc01ec7439ea459b39
2b109f69822e570f024f4419140a6817b08f0a43cf432323396834341914767e
```

As far as I understand @lukasmrtvy  just wants to parse stdout. It's easier to redirect the warning to stderr than to make a new option in the config.json or moving out of experimental.

**Comment by chris-crone** [comment]
That's a good idea @gabrieldemarmiesse. We [write warnings to stderr on the docker/cli](https://github.com/docker/cli/blob/1e54c5d67c536ff4e6cf3efa5aa66999c0d4e11f/cli/config/config.go#L141).

**Comment by thaJeztah** [comment]
Yes, they should be on stderr; see https://github.com/docker/cli/pull/1859

**Comment by chris-crone** [comment]
Let's aim to have this for the next release:
- stderr instead of stdout
- Add to help message
- Only print if the command exits with a non-zero code

**Comment by ndeloof** [comment]
I expected I could handle this in command's `PostRun` but this one is not executed on error. Need to find another way, any suggestion is welcome
