### ISSUE TITLE
Split repo to better isolate local vs aci vs ecs backends

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#1140]
**Description**
Whenever a mono-repo make it easier to iterate over shared API and move code around, this doesn't mean we need to develop local+aci+ecs backends asa monolith.

Repo should be re-organized to create isolated components, not just packages. 

https://github.com/kubernetes-sigs/kustomize/ demonstrate a valid approach relying on go modules with relative paths `replace` directives, which allow cross-component dependencies for flexible development but well defined boundaries between components.

compose-cli must be split into:
- cli
- api (shared types, utility and go-plumbing code)
- local backend 
- ecs backend
- aci backend

as a further step, each backend could be packaged into a dedicated binary, using the cli module to opt-in for commands and flags being supported (to enforce an homogeneous UX).

**Comment by gtardif** [comment]
Closing this, see discussion in #1174
