### ISSUE TITLE
Control-C issues duplicate signals to container

### ISSUE THREAD

**Issue by ryanuber** [docker/compose-cli#1151]
- [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: BD253A61-8FD5-49F8-BC42-41EFE6A5AC2A/20210112212415

### Expected behavior

Running a container in the foreground via `docker run` and pressing ctrl-c sends exactly one signal (defined by STOPSIGNAL in the Dockerfile) to the running process.

### Actual behavior

Two signals are sent to the running container, causing undesired behavior in the running application. Running with `-it` (interactive, TTY) produces a single signal, as expected.

### Information
  - Is it reproducible? Yes
  - Is the problem new? Yes - this seems to have been a behavior change at Docker Desktop 2.4.0. Prior versions send a single signal as expected.
  - Did the problem appear with an update? Versions from 2.4.0 onward exhibit the unexpected multiple signals behavior.
  - macOS Version: 10.15.7

### Steps to reproduce the behavior

1. Create a `Dockerfile` with the following content:
```Dockerfile
FROM ubuntu:20.04

COPY sig.sh /sig.sh
RUN chmod +x /sig.sh

STOPSIGNAL SIGINT

ENTRYPOINT ["/sig.sh"]
``` 
2. Create a script file `sig.sh` with the following content:
```bash
#!/bin/bash

trap "register" INT

register() {
    echo "INT"
    [ -z "$SIG" ] && SIG=1 || exit
}

while true; do
    sleep 100 &
    wait
done
```
3. Build the container with `docker build -t signal-test:latest .`
4. Run the container with `docker run signal-test:latest`
5. Press ctrl+c once. Note that `INT` is printed twice, thus indicating that two signals were sent to the process.

**Comment by stephen-turner** [comment]
I'm just going to move the ticket to that repo.

**Comment by ndeloof** [comment]
Internaly tracked as https://docker.atlassian.net/browse/IL-268

**Comment by jakeonfire** [comment]
i'm not seeing _any_ signals hit the running process.

running:
```
docker compose run --rm app my_script.sh
```

`my_script.sh`:
```
#!/usr/bin/env bash

echo sleeping
sleep 30 &
PID=$!

function cleaupQUIT() {
  echo got SIGQUIT
}
trap cleanupQUIT SIGQUIT

function cleaupTERM() {
  echo got SIGTERM
}
trap cleanupTERM SIGTERM

function cleaupEXIT() {
  echo got EXIT
}
trap cleanupEXIT EXIT

wait ${PID}
exit 0
```

output, hitting CTRL+C twice:
```
sleeping
^C^CERRO[0004] got 3 SIGTERM/SIGINTs, forcing shutdown
```

**Comment by francipvb** [comment]
Hello, I got this issue under wsl2.

**Comment by jakeonfire** [comment]
> Hello, I got this issue under wsl2.

i have not had this issue since the fix. could you be more specific, and/or open a new issue?

**Comment by chrkr** [comment]
I have this exact issue with Docker for Desktop version 4.19.0.

I am not sure when it (re?)appeared as I haven't previously tried to handle Control-C in a way which counts the number of signals.

I have tried:

- Run docker command _without_ `-it` in a WSL2 terminal, and also in a VSCode terminal, press Control-C:
 -> container received signal twice on first keypress
- Run docker command _with_ `-it` parameter in WSL2 terminal, press Control-C:
 -> container received signal once
- Run docker command _without_ `-it` in a regular CMD.EXE terminal, press Control-C:
 -> container received signal once
- Run docker command _without_ `-it` in a WSL2 terminal, send `SIGTERM` to the PID of the actual `docker run` command:
 -> container received signal once
- Run `com.docker.cli` _without_ `-it` in a WSL2 terminal, press Control-C:
 -> container received signal once
