### ISSUE TITLE
Fix exec.LookPath on windows

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#1164]
We currently have a workaround for how we find the moby CLI on windows, to avoid looking up in CWD (cf https://github.com/docker/compose-cli/blob/main/cli/mobycli/resolvepath/lp_windows.go)

We should be able to remove this now that the original issue has been fixed in go 1.15.7, see https://github.com/golang/go/issues/43783

**Comment by thaJeztah** [comment]
> We should be able to remove this now that the original issue has been fixed in go 1.15.7,

go 1.15 only fixes this for the `go` command itself (`go build` etc), but not for other uses of `LookPath`;

> This has been fixed by altering the usage of os/exec.LookPath by the go command to reject the usage of any binaries that reside in the current directory. If you are interested in understanding **whether your own programs have a problem**, we’ve written a blog post about the underlying issue: https://blog.golang.org/path-security.

**Comment by thaJeztah** [comment]
Fix for the `go` command can be found in this commit, which adds an `internal` package with a customised `LookPath`; https://github.com/golang/go/commit/07e3195293ec510171d7d43ec8ac2bcb9cf00df#diff-25560022006dcc0a0bf07fe3291119c24ca8b12d0f29d3ad01f7c8a55265af58R34-R43

**Comment by thaJeztah** [comment]
Looks like they also included a fixed version in golang.org/x/sys (same thing as the `internal` package from above); see https://github.com/docker/docker-credential-helpers/pull/195

**Comment by thaJeztah** [comment]
.
