### ISSUE TITLE
docker login azure doesn't open browser on macOS

### ISSUE THREAD

**Issue by chris-crone** [docker/compose-cli#1170]
**Description**
`docker login azure` does not open a browser but falls back to the code based login flow on macOS.

Tested on `1.0.7-39-gfea9697` (current `HEAD:main`) and `1.0.5-37-g5b660c8`, running macOS 11.2 beta 2 on an M1 mini.

**Steps to reproduce the issue:**
1. `docker login azure`

**Describe the results you received:**

```
docker login azure
Could not automatically open a browser, falling back to Azure device code flow authentication
2021/01/21 13:35:43 To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXX to authenticate.
```

**Describe the results you expected:**
Open a browser window so that I can login.

**Comment by mgingios** [comment]
ditto
