### ISSUE TITLE
Proposal: Move build to shell out instead of vendoring buildx

### ISSUE THREAD

**Issue by chris-crone** [docker/compose-cli#1202]
Chatting to @tonistiigi I believe the preferred way of doing builds is to shell out to buildx rather than vendoring it as we [currently are](https://github.com/docker/compose-cli/blob/main/local/compose/build.go). @gtardif has raised that shelling out does have some downsides: proper signal handling/passing is tricky and shelling out has a performance cost.

WDYT?

**Comment by thaJeztah** [comment]
If we do change, it would be good if buildx had some minimal sdk that helps with converting options to correct arguments to pass on the cli

**Comment by gabrieldemarmiesse** [comment]
I would be happy to see that. In python-on-whales, we also shell out buildx. One tricky thing is that buildx ouputs are not as easy to parse as other docker CLI sub-commands (no json and such). For future reference, here are the issues that I opened in buildx to make it easier to call it programmatically:
https://github.com/docker/buildx/issues/382
https://github.com/docker/buildx/issues/381
https://github.com/docker/buildx/issues/380

**Comment by thaJeztah** [comment]
I think for this particular use, the cli should not parse the output (so just trigger the build and output the buildx output)

having more structured output for other uses could be useful (but orthogonal to this issue)
