### ISSUE TITLE
Simple demo of "docker composer up" with ecs runs container locally?

### ISSUE THREAD

**Issue by dkegel-sigsci** [docker/compose-cli#1235]
**Description**

Tried to write minimal demo of using "composer up" to run a "hello, world" container on ECS, but the resulting container runs locally instead.

**Steps to reproduce the issue:**
Edit this script to use your AWS id and profile at the top, 
replace the SSO if not using okta,
possibly back up your ~/.aws directory, then run.
```
#!/bin/sh
# Demonstrate use of AWS ECR with docker compose
set -ex

# Define credentials and how to log in to AWS and docker using okta sso.
AWS_ID=foo
AWS_PROFILE=bar
AWS_REGION=us-west-2
okta_aws() {
    $HOME/.okta/bin/withokta "aws --profile $1" "$@"
}
okta_auth() {
    OKTA_AWS_ROLE_TO_ASSUME="arn:aws:iam::${AWS_ID}:role/Developer" okta_aws ${AWS_PROFILE} sts get-caller-identity
}
reset_okta() {
    rm -f ~/.aws/credentials ~/.okta/profiles ~/.okta/cookies.properties ~/.okta/.current-session
}
ecr_auth() {
    aws --profile sigsci_dev --region ${AWS_REGION} ecr get-login-password | docker login --password-stdin --username AWS https://${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com
}
set -ex

# Define docker image repository.
REPOPREFIX=${AWS_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/
REPO=$USER-ecrdemo

echo "0. Remove all existing docker containers, if desired"
docker system prune -a

echo "1. Build and run a "Hello, World" container locally"
# See https://serverfault.com/questions/462903/how-to-know-if-a-machine-is-an-ec2-instance for detecting whether on ECS
docker build -t ${REPOPREFIX}${REPO}:latest . -f - <<"_EOF_"
FROM alpine:latest
RUN apk update; apk add curl
CMD echo "Hello, world!  /sys/hypervisor/uuid='$(cat /sys/hypervisor/uuid)', dmi/id/product_uuid='$(cat /sys/devices/virtual/dmi/id/product_uuid)', curl says '$(curl -s -m 5 http://169.254.169.254/latest/dynamic/instance-identity/document)'"
_EOF_
docker run -t ${REPOPREFIX}${REPO}:latest

echo "2. Run it using docker-compose."
# First, create a compose file.
cat > ecr-compose.yaml  <<_EOF_
services:
  hello:
    image: ${REPOPREFIX}${REPO}:latest
_EOF_
docker-compose -f ecr-compose.yaml up

echo "----------------------------------------------------------"
echo "3. Do a fresh login to AWS and docker/ecr."
reset_okta
okta_auth
ecr_auth

echo "4. Create a repository in ECR for this image"
aws --profile $AWS_PROFILE ecr batch-delete-image --repository-name $REPO --image-ids imageTag=latest > /dev/null 2>&1 || true
aws --profile $AWS_PROFILE ecr delete-repository --repository-name $REPO > /dev/null 2>&1 || true
aws --profile $AWS_PROFILE ecr create-repository --repository-name $REPO

echo "5. Create a docker context referring to ECR, if none exists yet"
if ! docker context inspect myecr > /dev/null
then
    docker context create ecs myecr --profile $AWS_PROFILE
fi

echo "3. Push it to ECR"
# FIXME: wanted to use docker compose push, but couldn't?
docker push ${REPOPREFIX}${REPO}:latest

echo "4. Run it on ... whatever ECS cluster $AWS_PROFILE has access to?"
# See e.g. https://aws.amazon.com/blogs/containers/deploy-applications-on-amazon-ecs-using-docker-compose/
# FIXME: appears to be running locally :-(
docker compose --file ecr-compose.yaml --context myecr up
```

**Describe the results you received:**

Docker compose up ran the container locally (per e.g. the output of curl).

**Describe the results you expected:**

Docker compose up should have run the container on ECS (e.g. curl should have output ECS info).

**Additional information you deem important (e.g. issue happens only occasionally):**

I am a docker and AWS newbie.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.4
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:23 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

Output of docker context inspect myecr:
```
[
    {
        "Name": "myecr",
        "Metadata": {
            "Type": "ecs"
        },
        "Endpoints": {
            "docker": {
                "SkipTLSVerify": false
            },
            "ecs": {
                "Profile": "xxxxxxx"
            }
        },
        "TLSMaterial": {
            "kubernetes": [
                "ca.pem",
                "cert.pem",
                "key.pem"
            ]
        },
        "Storage": {
            "MetadataPath": "/Users/dkegel/.docker/contexts/meta/xxxx",
            "TLSPath": "/Users/dkegel/.docker/contexts/tls/xxxx"
        }
    }
]
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 3
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: KU7S:YJRH:NT2K:OALP:HS3M:43EF:7526:CHYG:WWQ6:5D2G:NAMV:2ZXQ
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 43
  Goroutines: 46
  System Time: 2021-02-03T18:29:39.467449506Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

Trying to use AWS ECS but failing :-(

Other people have run containers using the same AWS id and profile, so while I may be doing something wrong, at least it doesn't seem like it would be a permission problem.

**Comment by nathanpeck** [comment]
The local version you are seeing is probably the one that was launched by the previous line in your script where you called: `docker-compose -f ecr-compose.yaml up`

Check the following things:

- Output of `docker context ls` so we can see if the `myecr` context is actually created.
- Check the AWS console for ECS to see if there are any ECS resources created

This article may also help you: https://aws.amazon.com/blogs/containers/deploy-applications-on-amazon-ecs-using-docker-compose/

**Comment by ndeloof** [comment]
You can check deployed application by `docker  --context myecr compose ls`

**Comment by dkegel-sigsci** [comment]
That's the article I used to write the minimal reproducer script :-)  But it is not quite plug and chug, so I must have missed something.

```docker context ls``` clearly shows myecr was in fact created (and ```docker context inspect myecr``` shows it is of type ecs).

I didn't see anything new on the ECS console (though the image does show up in ECR).

Commenting out the 'docker run' and 'docker-compose up' lines that are supposed to do local runs does not change the result; 'docker compose up' still runs locally.

```docker --context myecr compose ls``` shows nothing but the title row.

I tried ```docker context use myecr```; after that, ```docker compose --file ecr-compose.yaml up```
output the interesting error
```
account has not default VPC
```
and now I get that error even if I go back to specifying the context on the commandline, and that seems like a really good clue about what I'm doing wrong.

I also get crashes occasionally, e.g.
```
bash-3.2$ docker compose --file ecr-compose.yaml --context myecr up
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
[+] Running 0/0
envoy-front-proxy-sigsci_hello_1  Restart                                                                                                                                                                                                               0.1s
[+] Running 0/1
envoy-front-proxy-sigsci_hello_1  Restart                                                                                                                                                                                                               0.2s
[+] Running 1/1
envoy-front-proxy-sigsci_hello_1  Restarted                                                                                                                                                                                                             0.3s
Attaching to envoy-front-proxy-sigsci_hello_1
hello     cat: can't open '/sys/hypervisor/uuid': No such file or directory
hello     Hello, world!  /sys/hypervisor/uuid='', dmi/id/product_uuid='ba4c4d5a-0000-0000-80dc-a4c260b5800e', curl says ''
hello     cat: can't open '/sys/hypervisor/uuid': No such file or directory
hello     Hello, world!  /sys/hypervisor/uuid='', dmi/id/product_uuid='ba4c4d5a-0000-0000-80dc-a4c260b5800e', curl says ''
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x2759661]

goroutine 72 [running]:
github.com/docker/compose-cli/local.(*composeService).attachContainerStreams.func1(0x34c7c00, 0xc0005b4540, 0x34aac80, 0xc0005b4740, 0x0, 0x0)
        github.com/docker/compose-cli/local/compose.go:412 +0x61
created by github.com/docker/compose-cli/local.(*composeService).attachContainerStreams
        github.com/docker/compose-cli/local/compose.go:409 +0x12c
˙˙˙

**Comment by ndeloof** [comment]
@dkegel-sigsci seems you missed the command selecting the newly created ECS context in Amazon article 

> Now, Docker has an additional context call myecscontext (or type ecs) that points to my existing AWS CLI default profile. Note that we are also setting myecscontext to be our new active context (which is marked with a * ):
> 
> ➜ docker context ls                     
> NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT               KUBERNETES ENDPOINT   ORCHESTRATOR
> default *           moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                         swarm
> myecscontext        ecs                                                                                                               
> ➜ docker context use myecscontext
> myecscontext
> ➜ docker context ls              
> NAME                TYPE                DESCRIPTION                               DOCKER ENDPOINT               KUBERNETES ENDPOINT   ORCHESTRATOR
> default             moby                Current DOCKER_HOST based configuration   unix:///var/run/docker.sock                         swarm
> myecscontext *      ecs 
> Bash
> 

=> **docker context use myecscontext**


_account has not default VPC_ error means your AWS account has no VPC set by default (which would be the case for a newly created AWS account). You'll have to make it explicit which VPC to use with `x-aws-vpc` extension field in your compose file, otherwise you can create a default VPC.

I created https://github.com/docker/compose-cli/issues/1239 to track the golang panic you reported.

**Comment by dkegel-sigsci** [comment]
I didn't forget the context; i specified it explicitly with a --context flag, which (after looking at the code) seems to do the same thing:
``` 
docker compose --file ecr-compose.yaml --context myecr up
```

There really should be a tutorial with an executable sample script that goes all the way from start to finish.  It would solve a lot of head scratching.   But that "no default VPC" message didn't show up until after I'd filed this issue (IIRC), so maybe the flakiness hid it.

Off to specify a VPC!

**Comment by dkegel-sigsci** [comment]
Confirming, adding x-aws-vpc specifying one of the VPCs listed in the AWS console (don't ask me, I just work here) did the trick; docker --context myecr compose up definitely ran the container on ecs.  Marking a default VPC in the AWS console would have done, too, I'm sure.

(Now, getting the log from the resulting 10 millisecond runtime container, that's another mystery :-) )
