### ISSUE TITLE
Verbose not available via "docker compose" (and why's it different from -l debug?)

### ISSUE THREAD

**Issue by kengruven** [docker/compose-cli#1253]
**Description**

With the old(?) `docker-compose`, there are two ways to get lots of debugging output: `--log-level=debug` and `--verbose`.  It's not clear what the difference between them is.  I was trying to debug some "bind mounts", for example, and those appear in `--verbose` but not in `--log-level=debug` (the most verbose logging level?).

With the new(?) `docker compose`, `--log-level debug` was fixed (#1226), but there is no `--verbose` flag.

The verbose/debug discrepancy is pretty confusing.  Why are there two ways to turn up the logging verbosity, with different feature sets?

Anyway, what I want is a way to see what "bind mounts" Docker Compose thinks there are, when running `docker compose`.  One way might be to bring `--verbose` to `docker compose`, but it'd be even nicer if `--verbose` just went away and `--log-level=debug` took over those duties, too.

**Steps to reproduce the issue:**
1. Make a docker-compose.yml file with a bind mount, like:

```
    my_service:
      volumes:
       - ./foo:/foo/
```

2. Run `docker-compose --verbose up`, and observe that it prints lines like:

    compose.cli.verbose_proxy.proxy_callable: docker create_container <- ...[redacted]... 'Binds': ['/my/project/folder/foo:/foo:rw'], ...[redacted]...

3. Try other ways to run Docker Compose verbosely, like `docker-compose --log-level=debug up`, `docker compose --verbose up`, etc.  (Note that you need to run "down" between these.)

**Describe the results you received:**

The only way to see info about bind mounts is `docker-compose --verbose`.  `--log-level=debug` doesn't print that info.  The `--verbose` flag doesn't exist for `docker compose`.

**Describe the results you expected:**

Running `--log-level=debug` should give me the maximum verbosity in all logging.  A separate `--verbose` flag is just confusing, and I don't know why it exists.

The new `docker compose` command should support the maximum level of logging, somehow.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:12:42 2020
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 10
 Server Version: 20.10.2
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.121-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.944GiB
 Name: docker-desktop
 ID: JCTN:YWV4:AUEC:7QV3:E4HB:AODP:DJGK:72X7:3PE7:SQBO:SJCZ:5OZG
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by ndeloof** [comment]
I'll check what `--verbose` actually implies in docker-compose and see if/how we should replicate on compose-cli. Otherwise we could make this an alias for `-D` (debug) flag which was introduced in early design of the compose CLI targeting cloud platforms.

**Comment by kengruven** [comment]
I didn't even notice `--debug` before.  Now I'm wondering what the conceptual difference between `--log-level=debug` and `--debug` was supposed to be!

**Comment by ndeloof** [comment]
--debug justwas introduced during initial design, and I recently added support for log-level for better compatibility with other docker tools. Consider --debug as a shortcut for --log-level=debug

**Comment by kengruven** [comment]
Well, I'm not opposed to a shortcut, as long as it's clearly documented.  Debugging seems like a common task, and there aren't that many flags here yet (unlike `ls --help` or `grep --help`!).

Right now, `docker help` only says "Enable debug mode".  [The documentation](https://docs.docker.com/engine/reference/commandline/cli/) shows (part of) the output of `docker help` but doesn't explain what any of these flags do.  I googled "docker debug mode" and read a few webpages but couldn't find a clear answer as to what "debug mode" means.

I would be perfectly happy with this flag if it said:

      -D, --debug              A synonym for --log-level=debug

That would be simple enough that even I could understand it!  Or you could just hide it, as you say -- I usually use the long form of flags, so it makes no difference to me either way.
