### ISSUE TITLE
Support compose ps  --filter

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#1274]
```
 --filter KEY=VAL     Filter services by a property
```

**Comment by ndeloof** [comment]
Implementation note: assuming the goal is to replicate docker-compose flag, this is only relevant if we implement #1273 
see https://github.com/docker/compose/blob/master/compose/cli/main.py#L766-L771

**Comment by gtardif** [comment]
Given this option only works with --services, and the cumbersome & undocumented functionality it provides in docker-compose, putting this a lower priority for the moment, waiting for user feedback if this is actually needed.
