### ISSUE TITLE
Compose down fail with 'removal of container is already in progress'

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#1282]
I noticed a few time CI failures caused by 
`removal of container xxx is already in progress`

`compose down` should catch this corner case and just ignore this error, and the requested action is actually executed

**Comment by gtardif** [comment]
Hmmm... looks like a possible race condition I just encountered adding unit tests in #1281 : 
most of the time green test, then suddenly 
```
TestDownRemoveOrphans (0.00s)
    /Users/gtardif/docker/src/github.com/docker/compose-cli/local/compose/down.go:101: Unexpected call to *mocks.MockAPIClient.ContainerStop([context.Background 789 <nil>]) at /Users/gtardif/docker/src/github.com/docker/compose-cli/local/mocks/mock_docker_api.go:579 because: 
        expected call at /Users/gtardif/docker/src/github.com/docker/compose-cli/local/compose/down_test.go:72 has already been called the max number of times
        expected call at /Users/gtardif/docker/src/github.com/docker/compose-cli/local/compose/down_test.go:71 doesn't match the argument at index 1.
        Got: 789
        Want: is equal to 123
        expected call at /Users/gtardif/docker/src/github.com/docker/compose-cli/local/compose/down_test.go:73 doesn't match the argument at index 1.
        Got: 789
        Want: is equal to 321
```
looks like we're trying to delete several times the same container, and not the other ones

**Comment by gtardif** [comment]
Just fixed an actual [issue](https://github.com/docker/compose-cli/pull/1281/commits/90b61a9504026e2b59bbf3e96294fd2cff83c28c), but happening only in case of `down --remove-orphans`, not sure if the CI issue mentioned here was happening in this scenario

**Comment by gtardif** [comment]
Seems to have ben fixed with issue mentioned above, reopen if this happens again
