### ISSUE TITLE
`down` invoke `ContainerList` twice

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#1304]
**Description**

`down` command invokes `ContainerList` with same parameters **twice**
(as unit test demonstrate https://github.com/docker/compose-cli/blob/main/local/compose/down_test.go#L41)

implementation could load containers (use `getContainers` with adequate filters), then pass containers to load project from labels

**Comment by ndeloof** [comment]
I also noticed we invoke `ImageInspectWithRaw` twice:
- once to check service image is present (localImagePresent)
- then again looking for image's "anonymous" volume (buildContainerVolumes)

**Comment by ulyssessouza** [comment]
@ndeloof I've just created an [issue](https://github.com/docker/compose-cli/issues/1466) to address your comment.
