### ISSUE TITLE
Unable to deploy simple example to ECS

### ISSUE THREAD

**Issue by metasoarous** [docker/compose-cli#1310]
Hello; Thanks for your time.

**Description**

Over at #1308 I mentioned that I was able to get `docker compose` working locally using the example here: https://docs.docker.com/compose/gettingstarted/. However, when I try to witch contexts to a freshly minted `ecs` context, it fails to deploy.

**Steps to reproduce the issue:**
1. `docker context create ecs myecscontext`
2. go through setup in https://docs.docker.com/compose/gettingstarted/
3. run `docker compose up` on default context to ensure it works
4. run `docker context use myecscontext` to switch to our new context
5. run `docker compose up` to deploy to new context

**Describe the results you received:**

```
% docker compose up
redis:alpine resolved to docker.io/library/redis:alpine@sha256:d2b1b0bf521f55381c81b1bc0218aec4ddc92fb545e9e8492e8ff324462eed58
invalid reference format
```

**Describe the results you expected:**

Expected the app to deploy under my credentials.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
% docker version                                                :( 1 21-02-15 - 15:48:53
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.3
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        48d30b5
 Built:             Fri Jan 29 14:33:25 2021
 OS/Arch:           linux/amd64
 Context:           polis-preprod
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.3
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       46229ca
  Built:            Fri Jan 29 14:31:35 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
myecscontext
```

**Output of `docker info`:**

```
% docker info                                                        21-02-15 - 16:15:18
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)

Server:
 Containers: 47
  Running: 0
  Paused: 0
  Stopped: 47
 Images: 678
 Server Version: 20.10.3
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc version: ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.8.0-7630-generic
 Operating System: Pop!_OS 20.10
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 62.43GiB
 Name: barco
 ID: ZQJ2:IPJM:ITUY:TIY5:GPAA:E2PB:DDDY:27XJ:GYEB:7IQK:ULH2:YUOP
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio weight support
WARNING: No blkio weight_device support

```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

Have tested AWS credentials successfully

**Comment by marcellodesales** [comment]
@metasoarous I'm curious if you tried the steps from https://aws.amazon.com/blogs/containers/deploy-applications-on-amazon-ecs-using-docker-compose/... I'm going to take some time this week to go over the steps myself...

**Comment by metasoarous** [comment]
Hi @marcellodesales. Thanks for taking a look.

I have been following that same blog post, but still having no luck.

**Comment by SamuelMS** [comment]
Can you post your compose yaml file (sans sensitive information)?

**Comment by metasoarous** [comment]
Hi @SamuelMS. Thanks for taking a look.

Again, I'm just following the example in https://docs.docker.com/compose/gettingstarted/, which has this compose file:

```
version: "3.9"
services:
  web:
    build: .
    ports:
      - "5000:5000"
  redis:
    image: "redis:alpine"
```

Works locally, but as soon as I switch to the ecs context it poops out `invalid reference format`

**Comment by ndeloof** [comment]
Tried to reproduce using your compose file,  but works for me
```
redis:alpine resolved to docker.io/library/redis:alpine@sha256:d2b1b0bf521f55381c81b1bc0218aec4ddc92fb545e9e8492e8ff324462eed58
[+] Running 6/8
 ⠧ nicolas                 CreateInProgress User Initiated
 ⠿ LogGroup                CreateComplete
 ⠧ CloudMap                CreateInProgress Resource creation Initiated
 ⠿ RedisTaskExecutionRole  CreateComplete                               
...
```

Trying to understand execution path that would trigger such an error ...

**Comment by ndeloof** [comment]
weird. This should have been catch by https://github.com/docker/compose-cli/blob/main/ecs/compatibility.go#L114-L115 ...

**Comment by metasoarous** [comment]
Hi @ndeloof. Thanks for your thoughts on this.

Does this mean that to use this functionality I have to deploy the docker images somewhere first, like dockerhub?

Thanks in advance.

**Comment by SamuelMS** [comment]
Not who you asked, but saw a notification come through regardless – yeah, images definitely have to be deployed somewhere so the remote ECS (Fargate) services can download and run them. If your images are private, you'll need to set up credentials as described here: https://docs.docker.com/cloud/ecs-integration/#private-docker-images

**Comment by metasoarous** [comment]
Got it; Thank you @SamuelMS. That's very helpful. I'll try publishing these images to see if I can't get this working (or switch to a different example that presumably already has images, such as the one used in the blog post, though I wanted to try to get it working with a bare bones example first). Will report back my progress.

**Comment by marcellodesales** [comment]
@SamuelMS @metasoarous that's great there's progress here... I will try running this as well...!
