### ISSUE TITLE
Compose cli shows a warning when using the supported `services.deploy.restart_policy` attribute within the ecs context

### ISSUE THREAD

**Issue by patrix58** [docker/compose-cli#1312]
**Description**
The compose cli prints an unsupported attribute warning when using the `services.deploy.restart_policy` attribute within the ecs context.
The warning message is the following: `WARN[0001] services.deploy.restart_policy: unsupported attribute`
Although the documentation lists this attribute as supported (https://docs.docker.com/cloud/ecs-compose-features/) and the feature is functional, but this warning message may discourage users to add this attribute to their docker compose yaml. 

**Steps to reproduce the issue:**
1. Create a simple docker compose configuration including a `services.deploy.restart_policy` attribute, like:
```yml
version: "3.9"
services:
  redis:
    image: redis:alpine
    deploy:
      restart_policy:
        condition: on-failure
```
2. Choose docker ecs context: `docker context use <context-name>`
3. Run `docker compose up`

**Describe the results you received:**
We can see a warning message: `WARN[0001] services.deploy.restart_policy: unsupported attribute`

**Describe the results you expected:**
Not to show the warning message.

**Additional information you deem important (e.g. issue happens only occasionally):**
I'm not familiar with the `compose-cli` code, but I assume that the attribute is missing from the compatibility list: https://github.com/docker/compose-cli/blob/main/ecs/compatibility.go#L53

**Output of `docker version`:** 

```
Client: Docker Engine - Community
 Cloud integration: 1.0.7
 Version:           20.10.2
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        2291f61
 Built:             Mon Dec 28 16:17:34 2020
 OS/Arch:           linux/amd64
 Context:           ecs
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.2
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8891c58
  Built:            Mon Dec 28 16:15:28 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.3
  GitCommit:        269548fa27e0089a8b8278fc4fc781d7f65a939b
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by ndeloof** [comment]
AFAICT there's no way to set restart policy for an ECS TaskDefinition, so the CLI is right this isn't supported (and then, ignored). Documentation will need to be fixed accordingly

**Comment by ndeloof** [comment]
confirmed: https://stackoverflow.com/questions/46226882/aws-ecs-restart-policy

**Comment by MrChrisRodriguez** [comment]
Documentation for the above needs to be updated.

**Comment by actualben** [comment]
Documentation fix being attempted in my (admittedly shambolic) first PR to this repo: #2184
