### ISSUE TITLE
Support compose up --attach-dependencies  

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#1371]
compose up option: 
`--attach-dependencies      Attach to dependent containers.`

**Comment by ndeloof** [comment]
could rely on https://github.com/docker/compose-cli/pull/1375/files#diff-a32e13b043f418f3ce48ed99cb9b06a9cfb9a52672ee292b15107a725beca269R71

**Comment by ulyssessouza** [comment]
Resolved by https://github.com/docker/compose-cli/pull/1383
