### ISSUE TITLE
CI/CD - Deploy to ECS

### ISSUE THREAD

**Issue by MartinJ-Dev** [docker/compose-cli#1385]
`docker compose` works well when manually creating AWS context and calling `docker compose up`. However, we couldn't figure out how to deploy it in the context of CI/CD on Linux. 

Suppose we have a Gitlab docker runner that can test, build, push or run any CI jobs based on any docker image.
https://docs.gitlab.com/ee/ci/docker/using_docker_build.html

The problem we have is to deploy using `docker --context ecs compose up`. Since each job executor uses a clean build environment, it doesn't have access to previously installed compose-cli or AWS context. 

One option would be using a custom image including docker, compose-cli, aws-cli, etc. Would creating a new aws context for every deployment update the existing stack in ECS **OR** creating a new one?

We are not sure if this falls into the domain of compose-cli. Given it's fairly new (yet promising), we can find very limited resources online. Any feedback is appreciated.

**Comment by ndeloof** [comment]
Starting from a clean build environment, you should use
`docker context create ecs ecs --from-env` so that a context is created with name `ecs` and expect `AWS_*` variables to be set for your AWS account (up to you to get those injected in your build environment)

**Comment by MartinJ-Dev** [comment]
@ndeloof Thank you for your prompt reply. Can I confirm with you - if keeping the following variables constant, we'd update the existing stack instead of creating a new one: 
- Name of the context (e.g., `ecs`)
- AWS_* variables (`AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_DEFAULT_REGION`)
- Application name (derived from `$PWD` or specified by `--project-name`) 

Do we need anything else?

**Comment by MartinJ-Dev** [comment]
Another issue we are running into is that the official docker image doesn't come with compose-cli. We try to create a custom image based on docker 

```
FROM docker:latest
RUN apk add --no-cache curl
RUN curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
```

which gives error

```
$ curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5888  100  5888    0     0  33645      0 --:--:-- --:--:-- --:--:-- 33645
Running checks...
Warning: This script has been tested on Ubuntu and may not work on other distributions
Error: This script only works if the Docker CLI is installed to /usr/bin/
Please follow the manual install instructions
````

Then we figured out `docker:latest` is based on linux alpine but compose-cli only works on Ubuntu. 


We gave another shot by using an ubuntu based image 
```
FROM ubuntu:18.04
RUN apt-get update
RUN apt-get install -y curl
RUN curl -fsSL https://get.docker.com -o get-docker.sh
RUN sh get-docker.sh
RUN curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
CMD ["docker", "compose"]
```

While it seems working, we are concerned if this is the right way given its complexity. Please advise.

It'd be great if you could provide an official image that comes with both docker and compose-cli so that users can run CI/CD with ease. It'd provide more values to users if you could create a working example of typical CI/CD flow.

**Comment by ndeloof** [comment]
you can install on alpine but need to follow https://github.com/docker/compose-cli/blob/main/INSTALL.md#manual-install

using same AWS credentials and project name, `docker compose ..` commands will indeed apply to the same Cloudformatin stack / ECS deployment

**Comment by MartinJ-Dev** [comment]
@ndeloof Great thanks for confirming. Looking forward to more progress on compose-cli.
