### ISSUE TITLE
Unable to bind to IPv6

### ISSUE THREAD

**Issue by chris-crone** [docker/compose-cli#1386]
**Description**
`docker compose` on the local context does not allow binding to an IPv6 address.

**Steps to reproduce the issue:**

Compose file with IPv6 port, e.g.:
```yaml
...
ports:
  - "${IP6_ADDR}:53:53/tcp"
...
```

**Describe the results you received:**

```console
1 error(s) decoding:                      
                                            
* error decoding 'Ports': Invalid ip address REDACTED: address REDACTED: too many colons in address
```

**Describe the results you expected:**

Same behavior as `docker-compose up`.

**Additional information you deem important (e.g. issue happens only occasionally):**

Reproducible with current `HEAD:main` (12ffdd140521deeeb0b1694c2b5615817c24c66c).

**Comment by ndeloof** [comment]
docker-compose relies on docker-py to parse the port specification string:
https://github.com/docker/docker-py/blob/6da140e26c1cbe8e362b328b1c78d9c736f3a1a2/docker/utils/ports.py#L6

docker compose relies on go-connections (and then indirectly on net.SplitHostPort) which **require** literal IPv6 address enclosed in square brackets

Depending on fix complexity we can either make go-connextion more flexible _or_ have docker-py support square brakets, but at least need to ensure an homogeneous and documented solution. Which means we also need to document supported/expected syntax on https://github.com/compose-spec/compose-spec/blob/master/spec.md#short-syntax-2

**Comment by ndeloof** [comment]
fixed
