### ISSUE TITLE
Compose child command not listed

### ISSUE THREAD

**Issue by Veverke** [docker/compose-cli#1404]
File: [engine/reference/commandline/docker.md](https://docs.docker.com/engine/reference/commandline/docker/)

Hi there, I have been using `docker-compose` but noticed there is a `docker compose` (without the dash) as well.
Someone in StackOverflow pointed out that the latter is a sub-command of the `docker` exe, not a command itself.
If this is correct, I would expect the `compose` sub-command to be listed in the child commands doc [here](https://docs.docker.com/engine/reference/commandline/docker/).

**Comment by gtardif** [comment]
compose command reference doc is now live
