### ISSUE TITLE
Support running containers in ECS without a load balancer

### ISSUE THREAD

**Issue by dpca** [docker/compose-cli#1408]
For certain workloads, it's useful to be able to run docker containers without having any inbound connections via a load balancer. Some examples include ETL jobs that run on a schedule or an internal slack bot that establishes its own outbound connections. At the moment I don't think it's possible for docker-compose to spin up something in ECS without it adding an ALB or specifying one via x-aws-loadbalancer.

Here's an example `docker-compose.yml` file that should spin up containers without an ALB:

```
version: '2'
services:
  hello:
    image: hello-world
```

If I try running `docker compose up` in an ECS context with that docker-compose.yml file, first there's an error:

```
account has no default VPC. Set VPC to deploy to using 'x-aws-vpc'
```

and if I give it a blank VPC:

```
VPC ----- should have at least 2 associated public subnets in different availability zones
```

Thanks for taking a look at this!

**Comment by ndeloof** [comment]
if none of the service do declare `ports` we indeed don't need to define a LoadBalancer (and other network components).
I actually thought we already skipped this in such a scenario (see https://github.com/docker/compose-cli/blob/5bb676c4315d5b00e32fbf338fd2090a1574e3b8/ecs/awsResources.go#L428-L433)

That being said, "ETL Jobs" you describe would better be implemented as ECS Scheduled Taks (https://docs.aws.amazon.com/AmazonECS/latest/developerguide/scheduled_tasks.html) but the compose-spec does not (yet) define a "jobs" type (see https://github.com/compose-spec/compose-spec/issues/92)

**Comment by dpca** [comment]
That's great! Is there any way to get it past the error messages about the VPC? I don't think public subnets are needed if the services aren't hooked up to a load balancer.

**Comment by mfloresVicomtech** [comment]
Hi, what if you want to expose a service without using a ELB? Like having an Nginx or HAProxy service that handles the reverse proxy/SSL termination/load balancing without relying in a aws load balancer.

**Comment by Cliftonz** [comment]
This should still be open.
