### ISSUE TITLE
Define outputs for resources created in ECS CloudFormation stack

### ISSUE THREAD

**Issue by mikesir87** [docker/compose-cli#1431]
**Description**

I believe I had this request in the old GH repo, but it got lost/dropped when everything merged into this repo. So, here I am again!

In the generated CF stack template, I'd like to have the various resources defined as outputs. This can then let me have other scripts that can consume the stack outputs and do additional things with it. As a specific example, I'd like to do some integrations with Terraform, which can pull CF stack outputs as datasources. I like the overlay idea, but sometimes I need/want to connect various apps and TF is currently my tool of choice for that.

**Comment by ndeloof** [comment]
I wonder which resources should then be exposed as output. Or should we expose all of them?

**Comment by mikesir87** [comment]
If possible, it would be great to expose all of them. Otherwise, it'll be a constant feature request loop as I'm sure someone will want the thing you're not exposing. Will make it a nice standard too if any new resources are added to the stack in the future.
