### ISSUE TITLE
Provide arm v6 and v7 builds in releases

### ISSUE THREAD

**Issue by BretFisher** [docker/compose-cli#1471]
@chris-crone could this be as simple as a makefile edit to add the two platforms?  I'd like parity with the `docker` image platforms list.

**Comment by chris-crone** [comment]
Yep, it requires an edit to build here: https://github.com/docker/compose-cli/blob/main/builder.Makefile#L61-L66

Package here: https://github.com/docker/compose-cli/blob/main/builder.Makefile#L89-L97

And a tar transform here: https://github.com/docker/compose-cli/blob/main/builder.Makefile#L45-L48

I'll add it to our upcoming sprint

**Comment by BretFisher** [comment]
🥇
