### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by chris-crone** [docker/compose-cli#1473]
Now that we have support for local Compose, we should update the README with this information.

**Comment by BretFisher** [comment]
Hah I was about to open a issue+PR for updating the README to help reduce confusion between projects, based on #901 and my response.  If you're opening a PR, please include:

- Current status of this tool vs. https://github.com/docker/compose and link to feature party #1283 
- The eventual goal of this tool replacing https://github.com/docker/compose, assuming that's true
- The main reasons to use this tool over the python one (integrations, new commands, buildkit defaul, etc.)

**Comment by chris-crone** [comment]
@dieucao was the one who caught this. I just added it to our backlog :)

We can do this iteratively; starting with your (1) and (3), and then looking at (2) when we have a timeline.
