### ISSUE TITLE
docker compose up command failed to use credential info from docker

### ISSUE THREAD

**Issue by albertjone** [docker/compose-cli#1526]
**Description**
i was use `docker compose up` to create containers following https://docs.stackstorm.com/install/docker.html, but it failed with below error:
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to build LLB: failed to load cache key: failed to copy: httpReaderSeeker: failed open: unexpected status code https://registry-1.docker.io/v2/stackstorm/st2auth/manifests/sha256:dbc9b1bc01725ca17d01e22873287899c0def080bf8f21574a093a2fbc6547a2: 429 Too Many Requests - Server message: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit
And i was behind a lb.

**Steps to reproduce the issue:**
1. git clone https://github.com/stackstorm/st2-docker
2. cd st2-docker
3. docker-compose up
4. then you get the above error

**Describe the results you received:**
got the error info, even i login in. But i use `docker-compose up` is ok.

**Describe the results you expected:**
After i docker login with my user name and password, i am able to docker compose up the st2.

**Additional information you deem important (e.g. issue happens only occasionally):**
it always happen.
**Output of `docker version`:**

```
Docker version 20.10.0, build 7287ab3
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
[]
context "context-name" does not exist
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-docker)
  scan: Docker Scan (Docker Inc., v0.5.0)

Server:
 Containers: 35
  Running: 19
  Paused: 0
  Stopped: 16
 Images: 53
 Server Version: 19.03.12
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7ad184331fa3e55e52b890ea95e65ba581ae3429
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.130-boot2docker
 Operating System: Boot2Docker 19.03.12 (TCL 10.1)
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.696GiB
 Name: default
 ID: BCDS:ZZPD:KVDE:QODN:4A5N:XTNB:CUDW:XFFH:JYBV:WSWN:P5TP:OI2Q
 Docker Root Dir: /mnt/sda1/var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
  provider=virtualbox
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by ndeloof** [comment]
Can you please clarify? You said you get this error "even I login in" but then you say "after login compose up is successful" which is contradictory

Also, `You have reached your pull rate limit` is a DockerHub limitation that can indeed be balanced by logging in. Command line tools just report this pull error, they have no way to workaround this limitation.
