### ISSUE TITLE
Running docker compose up -d (strconv.Atoi: parsing "": invalid syntax)

### ISSUE THREAD

**Issue by art-boer** [docker/compose-cli#1537]
**Description**

Currently, I am using docker-compose up -d in my project. However, I would love to be able to use docker compose up -d to get the same result. Except within my project I get the following error:

**strconv.Atoi: parsing "": invalid syntax**

Using docker-compose I do not have this issue.

**Steps to reproduce the issue:**
1. Use the following docker-compose.yml:
```
version: '3'

services:
  deploy:
    hostname: deploy.magento2.docker
    image: 'magento/magento-cloud-docker-php:7.4-cli-1.2.1'
    extends: generic
    volumes:
      - 'xyz-magento-sync:/app:nocopy'
    networks:
      magento:
        aliases:
          - deploy.magento2.docker
```
2. Run docker compose up -d, create bash shell into the deploy image, click Quit docker desktop, restart and run docker compose up -d

**Describe the results you received:**
strconv.Atoi: parsing "": invalid syntax

**Describe the results you expected:**

It should create my containers and run them, just like docker-compose does

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  

```
[
    {
        "Name": "default",
        "Metadata": {
            "StackOrchestrator": "swarm"
        },
        "Endpoints": {
            "docker": {
                "Host": "unix:///var/run/docker.sock",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "\u003cIN MEMORY\u003e",
            "TLSPath": "\u003cIN MEMORY\u003e"
        }
    }
]

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 30
  Running: 11
  Paused: 0
  Stopped: 19
 Images: 29
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 4.083GiB
 Name: docker-desktop
 ID: RTD3:Y4JD:OQF7:WLQG:NZU4:PBSN:4RZU:N4HY:XDYW:YUSB:SU5P:YXOY
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

Local

**Comment by ndeloof** [comment]
Could you please try to remove a few services from this compose file to make it easier for us to reproduce and diagnose this issue? Especially, we don't have access to your private docker image to run this compose file.

**Comment by art-boer** [comment]
I found out how to recreate the issue.

1. Make sure you have some containers setup, and open a bash shell this should create a container called service_name_325afasd21352345n or whatever.
2. Now close Docker using the "Quit Docker Desktop" or kill the process which leaves the service_name_325afasd21352345n container on your computer
3. Now rerun docker and try docker compose up -d, it will try recreating the bash container and give the following error: strconv.Atoi: parsing "": invalid syntax

**Comment by erielmejias99** [comment]
This is still happening for me :(. I just stopped the container that @art-boer mentioned in step 1, and it worked. But those containers start restarting again and again. I have to stop them and quickly run **docker-compose up** before they restart.

```
Make sure you have some containers setup, and open a bash shell this should create a container
called service_name_325afasd21352345n or whatever.
```

**Comment by chylex** [comment]
Ran into the same issue on Linux with Docker Compose v2.12.0.

For some reason `docker compose up -d` tried to start some nonsense container that is not in my `docker-compose.yml`:

```
⠋ Container nervous_swartz             Recreate
strconv.Atoi: parsing "": invalid syntax
```

I commented out the service that was missing and "replaced" by this nonsense container, then I got:

> WARN[0000] Found orphan containers ([nervous_swartz distracted_jennings vigilant_leavitt]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.

Ran with `--remove-orphans`, uncommented the service, ran `docker compose up -d` again and now it works.

**Comment by danielgafni** [comment]
I have the same issue. By the way, Docker Compose v1 doesn't have this problem.

**Comment by i3130002** [comment]
### For others getting `strconv.Atoi: parsing "": invalid syntax` with no apparent reason.

Use `sudo docker system prune` to clean up docker cache and etc.
#### Use it at your own risk

**Comment by 0xBYTESHIFT** [comment]
run into this issue too. docker system prune doesn't help at all. I'm stuck

**Comment by ValentinFrancois** [comment]
@0xBYTESHIFT did you also try `docker container prune`?

This happened to me and it was coming from a stopped service container that was randomly named `vigorous_lovelace` (although all my services in  `docker-compose.yml` have fixed names defined with `container_name`).

Maybe try to find any weird stopped container with `docker-compose ps -a | grep exited`, remove them and then see if it helped when you retry `docker-compose up`.

Using docker-compose v2.12.2 and docker v20.10.21.

**Comment by danielgafni** [comment]
For me `docker-compose` works when `docker compose` fails with this error

**Comment by ndeloof** [comment]
This has been fixed by https://github.com/docker/compose/pull/10005
(by the way, this is wrong repository to report docker compose issues!)

**Comment by pangyuteng** [comment]
if `docker system prune -f` doesn't work, give `docker compose down --remove-orphans` a t ry!

**Comment by AidPaike** [comment]
> if `docker system prune -f` doesn't work, then give `docker compose down --remove-orphans` a try!

it worked! thank you~   

I suspect docker-compose didn't close with `docker-compose down`

**Comment by ptran1203** [comment]
> if `docker system prune -f` doesn't work, then give `docker compose down --remove-orphans` a try!

Thank you, I just removed all of system containers
