### ISSUE TITLE
docker-compose.override.yml file is not automatically consumed by new docker compose command

### ISSUE THREAD

**Issue by srajkovic** [docker/compose-cli#1546]
**Description**

The new `docker compose` usage does not automatically use docker-compose.override.yml, like the old `docker-compose` does.

**Steps to reproduce the issue:**
1. Have both `docker-compose.yml` and `docker-compose.override.yml`
2. Run `docker compose up` (or `docker compose down`)

**Describe the results you received:**
Only the configuration in the `docker-compose.yml` file is used (additional containers described in `docker-compose.override.yml` are not).

**Describe the results you expected:**
Both the configuration in the `docker-compose.yml` and `docker-compose.override.yml` are.

**Additional information you deem important (e.g. issue happens only occasionally):**
I realize using `-f docker-compose.yml -f docker-compose.override.yml` will ensure both are used, but since it previously used the override by default, figured I'd file this to make sure it's either an intentional change or potentially fixed. I'd be willing to contribute a fix if needed (though I'm new to the codebase so it might take a little longer.

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 24
  Running: 20
  Paused: 0
  Stopped: 4
 Images: 18
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 3.844GiB
 Name: docker-desktop
 ID: AZWR:OZGS:Z626:5V4T:VDWN:36K7:5LRA:3MOY:H72F:XTX6:WCXH:XOJE
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 182
  Goroutines: 167
  System Time: 2021-04-14T23:03:54.2960723Z
  EventsListeners: 4
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Local on MacOS Catalina

**Comment by ndeloof** [comment]
support for override file is not defined by the compose specification, so this difference between tools behavior. We need to clarify this by compose spec, or at least make compose-go flexible enough so this is configurable

**Comment by hrabe** [comment]
https://docs.docker.com/compose/extends/

Understanding multiple Compose files
By default, Compose reads two files, a docker-compose.yml and an optional docker-compose.override.yml file. By convention, the docker-compose.yml contains your base configuration. The override file, as its name implies, can contain configuration overrides for existing services or entirely new services.

I would say this is normal docker-compose behavior and should be possible by docker cli compose too.

**Comment by imomaliev** [comment]
Maybe this could be done via env variable, which will be `true` during transition period from `docker-compose`?

**Comment by ndeloof** [comment]
@hrabe don't make me wrong, I'm not saying `docker compose` should _not_ reproduce `docker-compose` support for override files, just https://github.com/compose-spec/compose-spec does not mention this and we maybe should introduce this in the spec _as well_.

**Comment by srajkovic** [comment]
Thanks!
