### ISSUE TITLE
unable to use docker compose with MFA

### ISSUE THREAD

**Issue by Dranaxel** [docker/compose-cli#1551]
**Description**

Hello, I'm trying to use ECS with docker compose cli but when I try, I keep getting the error `AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.` I'm not sure it's important but, I use this with an assume role on another tenant

**Steps to reproduce the issue:**
1. generate a sts session token with `aws sts get-session-token --serial-number arn:aws:iam::XXXXXXX:mfa/john.doe --token-code 581700 --profile default`
2. export AWS_ACCESS_KEY/AWS_SECRET_ACCESS_KEY/AWS_SESSION_ACCESS_KEY 
3. docker compose up

**Describe the results you received:**
AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.

**Describe the results you expected:**
launching my stack on ECS

**Additional information you deem important (e.g. issue happens only occasionally):**
As I said I'm using assume role, MFA is activated on my master account

**Output of `docker version`:**

```
Docker version 20.10.5, build 55c4c88
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.
```

**Output of `docker info`:**

```
AssumeRoleTokenProviderNotSetError: assume role with MFA enabled, but AssumeRoleTokenProvider session option not set.
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
I'm using AWS cli 2 and Debian 9 on WSL

**Comment by JacopKane** [comment]
did you ever manage to solve this issue? @Dranaxel

**Comment by Dranaxel** [comment]
Hi Furlan, It's been a long time and we Moved to something else. Sorry I
cannot give you any retex on this issue

Le mar. 5 avr. 2022 à 09:44, Furkan Tunalı ***@***.***> a
écrit :
