### ISSUE TITLE
There is a difference in the way `.env` values are handled.

### ISSUE THREAD

**Issue by yyh-gl** [docker/compose-cli#1569]
**Description**

**Steps to reproduce the issue:**
1. Prepare the following files.
   - `.env` that contains spaces at the end of the value
      ```
      SAMPLE_KEY=SAMPLE_VALUE   
      ```
      ↑ `SAMPLE_VALUE` has spaces at the end of the value.
   - `docker-compose.yml` with `env_file`
      ```yml
      version: '3.7'
      services:
        sample:
          image: alpine:latest
          command: env
          env_file:
            - .env
      ```
    Directory structure
    ```
    $ tree -a
    .
    ├── .env
    └── docker-compose.yml
    ```
2. `docker-compose up --build` and `docker compose up --build`

**Describe the results you received:**

When `docker-compose up --build`,
`SAMPLE_KEY`'s value is "SAMPLE_VALUE".
-> No spaces at the end of the value.

When `docker compose up --build`,
`SAMPLE_KEY`'s value is "SAMPLE_VALUE    ".
-> Has spaces at the end of the value.

There is a difference between the two in that they both include/exclude spaces.

**Describe the results you expected:**

A simple solution, I think that "docker compose" command take over the operation of "docker-compose".

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
$ docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64 (rosetta)
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:16:48 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 16
  Running: 9
  Paused: 0
  Stopped: 7
 Images: 44
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 3.841GiB
 Name: docker-desktop
 ID: QW57:OKB3:2H4C:45LI:CQTJ:CUI6:F7DG:WY4K:W7LH:X4QE:VID2:OA7O
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Comment by ndeloof** [comment]
I ran a quick test and noticed Docker CLI also don't remove trailing spaces:
```
$ docker run --env-file .env alpine env
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
HOSTNAME=a48757531742
SAMPLE_KEY=SAMPLE_VALUE   #trailing spaces here
HOME=/root
```

As claimed on https://github.com/theskumar/python-dotenv#file-format, "he format is not formally specified" so it's unclear which one should be considered buggy ¯\\_(ツ)_/¯, anyway:

* godotenv indeed do explicitly trim values: https://github.com/joho/godotenv/blob/ddf83eb33bbb136f62617a409142b74b91dbcff3/godotenv.go#L290
* ruby dotenv spec check the same: https://github.com/bkeepers/dotenv/blob/master/spec/dotenv/parser_spec.rb#L29-L31
* *python-dotenv says "Spaces before and after keys, equal signs, and values are ignored"

so, Docker CLI clearly doesn't follow this convention
For legacy reasons, compose support in Docker has been using a home-made env file parser https://github.com/compose-spec/compose-go/tree/master/envfile
While Docker CLI uses a more generic Key,Value parser https://github.com/docker/cli/blob/master/opts/parse.go#L21

**Comment by yyh-gl** [comment]
@ndeloof 
Thank you for your additional survey.

I think this issue will solve by following PR, right?
-> https://github.com/compose-spec/compose-go/pull/123

**Comment by ndeloof** [comment]
yes indeed (once merged and we update compose-go dependency)

**Comment by yyh-gl** [comment]
Thank you for your quick action!!
