### ISSUE TITLE
`docker context create aci` --location flag seems to have no effect.

### ISSUE THREAD

**Issue by mornemaritz** [docker/compose-cli#1589]
When using docker compose to deploy a container group to Azure Container Instances, the `--location` argument specified when creating the docker context for aci, `docker context create aci...`, appears to have no effect.

I'm following [these azure instructions](https://docs.microsoft.com/en-us/azure/container-instances/tutorial-docker-compose) for using docker compose with azure container instances
and [this docker documentation](https://docs.docker.com/cloud/aci-integration/#create-an-aci-context) showing the additional arguments for the `docker context create` command

The ultimate manifestation of this issue is that I am unable to create a container group in azure because I'm working in the context of a resource group _which I cannot change_, but the resource group is in a location that does not support Azure Container Instances.
When I try and issue the `docker-compose up` command in the aci context that I *thought* I created in a location that *supports* azure container instances, I get a location not supported error, listing the location of the resource group and not the location I specified for the docker aci context.

Am I misunderstanding the purpose of the `--location` parameter?

I know you *can* mix and match locations between a container instance and a resource group because I am able to create a container instance via azure cli with a location different to that of the resource group that it is linked to.

**Steps to reproduce the issue:**
 1. Log into azure via the cli `az login`
 2. Authenticate docker with azure `docker login azure`
 3. Create an azure resource group in a specific location `az group create -l uksouth -n test-aci-ctx-group`
 4. Create a docker context specifying a location different to the resource group location `docker context create aci aci-context-eastus --resource-group test-aci-ctx-group --location eastus`
 
**Describe the results you received:**
a context bound to the same location as the azure resource group, i.e., uksouth

**Describe the results you expected:**
a context bound to the location specified as `--location` for the `docker context create` command, i.e.,  eastus

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 20.10.5, build 55c4c88
```

**Output of `docker context show`:**  
```
[
    {
        "Name": "aci-context-eastus",
        "Metadata": {
            "Description": "test-aci-ctx-group@uksouth",
            "Type": "aci"
        },
        "Endpoints": {
            "aci": {
                "Location": "uksouth",
                "ResourceGroup": "test-aci-ctx-group",
                "SubscriptionID": "xxxxxxxxxxxxxxxxxxx"
            },
            "docker": {
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "xxxx",
            "TLSPath": "xxxx"
        }
    }
]
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 13
  Running: 3
  Paused: 0
  Stopped: 10
 Images: 71
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.4.72-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 49.72GiB
 Name: docker-desktop
 ID: 2QSF:BLXR:WIR6:Q3BE:FNRD:SBHI:JNS7:PTVJ:OOFF:Q6AQ:AUSU:W2WS
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
**Output of `az  version`:**
```
{
  "azure-cli": "2.22.1",
  "azure-cli-core": "2.22.1",
  "azure-cli-telemetry": "1.0.6",
  "extensions": {}
}
```

Not sure if this is relevant but issuing the `docker info` command when in the non-default docker context, the following message was returned
`Command "info" not available in current context (aci-context-eastus), you can use the "default" context to run this command`

**Comment by karolz-ms** [comment]
@gtardif I think @mornemaritz has a point here

It is not a super well-known fact, but Azure resource group location only determines where metadata about the resources is stored. The resources group itself can contain resources from different location(s) https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/overview#resource-groups

**Comment by gtardif** [comment]
Thx for reporting this @mornemaritz (and sorry for the late reply).
Indeed that makes sense. And an easy fix !
