### ISSUE TITLE
docker compose build --build-arg ARG Not able to access ARG in the image while building

### ISSUE THREAD

**Issue by saikumar-everest** [docker/compose-cli#1602]
My **Dockerfile.dev** has a command to install all gems.

**Usual command:**
docker-compose build --build-arg BUNDLE_GEMS__CONTRIBSYS__COM app

This is able to build the image successfully as it could access the sending build argument which is a secret to download a gem from server securely.

**Experimental command:**
docker compose build --build-arg BUNDLE_GEMS__CONTRIBSYS__COM app

But with this command replaced, I'm not able to build image. I get 401 unauthorised error while downloading a gem. I clearly know that we get this when we don't try to download a gem securely by providing a secret.

So I expect this experimental feature is not yet working as expected (docker-compose ≠ docker compose).

**Comment by Liam-Johnston** [comment]
This same problem occurs when defining build args in `docker-compose.yml`

**Comment by ndeloof** [comment]
actually a duplicate for https://github.com/docker/compose-cli/issues/1560
