### ISSUE TITLE
stty is different between `docker-compose` and `docker compose`.

### ISSUE THREAD

**Issue by takamario** [docker/compose-cli#1605]
**Description**

`stty` is different between `docker-compose` and `docker compose`.
`tty: true` and `stdin_open: true` are already set in `docker-compose.yml`.

**Describe the results you received:**
```sh
 ❯ docker-compose exec some_container bash
root@c1a8e22ebc28:/app# stty size
49 270
```
```sh
 ❯ docker compose exec some_container bash
root@c1a8e22ebc28:/app# stty size
0 0
```

**Describe the results you expected:**

`stty` with `docker compose` returns same value as `docker-compose` .

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker version 20.10.5, build 55c4c88
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

I tried on macOS 11.2.3 (Docker Desktop).

**Comment by ndeloof** [comment]
Hi, thanks for reporting this issue
This has been fixed already on https://github.com/docker/compose-cli/pull/1512, will be part of 1.0.14 release
