### ISSUE TITLE
override file not being picked up

### ISSUE THREAD

**Issue by dudo** [docker/compose-cli#1612]
docker-compose would pick up a `docker-compose.override.yml` file if it existed, and do some deep merging. 

docker compose doesn't seem to be picking up that file.

**Comment by steveoh** [comment]
I have this issue also, i had to pass in both files with the --files command to make it work like docker-compose

**Comment by johnjcamilleri** [comment]
Same here, Docker Desktop 3.3.1 (63152) on macOS

**Comment by ndeloof** [comment]
This is a duplicate for https://github.com/docker/compose-cli/issues/1546, already fixed (release coming soon to docker Desktop, feel free to download binary from https://github.com/docker/compose-cli/releases)
