### ISSUE TITLE
New docker compose command does not accept valid YAML

### ISSUE THREAD

**Issue by gmr** [docker/compose-cli#1621]
A properly formatted YAML document SHOULD include the YAML directive. When a docker-compose file with the YAML directive is parsed by `docker compose` it errs. Removing the YAML directive allows the file to be parsed correctly. This poses a significant barrier for the quantity of projects in our organization that write proper YAML that will not be recognized by `docker compose`.

https://yaml.org/spec/1.2/spec.html#id2781553

This doesn't work:

```
%YAML 1.2
---
version: "3.7"
services:
   ...
```

This does:

```
version: "3.7"
services:
   ...
```

**Steps to reproduce the issue:**
1. Write valid YAML, including the leading YAML directive specifying the version of YAML markup
2. Run `docker compose`

**Describe the results you received:**

```
docker compose port postgres 5432
The new 'docker compose' command is currently experimental. To provide feedback or request new features please open issues at https://github.com/docker/compose-cli
yaml: found incompatible YAML document
```

**Describe the results you expected:**

```
docker compose port postgres 5432
0.0.0.0:54477
```

**Output of `docker version`:**

```
docker version
Client: Docker Engine - Community
 Cloud integration: 1.0.12
 Version:           20.10.5
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        55c4c88
 Built:             Tue Mar  2 20:13:00 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.5
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       363e9a8
  Built:            Tue Mar  2 20:15:47 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by ndeloof** [comment]
Thanks for reporting this issue, we will investigate getting this fixed as part of https://github.com/compose-spec/compose-go

**Comment by ndeloof** [comment]
note: this issue depends on https://github.com/go-yaml/yaml/issues/298
expected to be fixed in gopkg.in/yaml.v3

**Comment by ndeloof** [comment]
I created https://github.com/compose-spec/compose-go/issues/139 for this (can't transfert issue to another github organization)
