### ISSUE TITLE
Docker Compose on mac with homebrew install

### ISSUE THREAD

**Issue by logopk** [docker/compose-cli#1644]
**Description**

I would like to try to test the compose command (as my docker-compose client tells me it is available).
`Docker Compose is now in the Docker CLI, try 'docker compose'`

As I use the homebrew install, I can't access the Docker Desktop for Mac binaries to try it.

Do you have an idea how to add the new compose command to the homebrew binaries (or what would be your timeline to add this).

Compiling locally would be a possibility, but there is no explanation how to get the compose-cli integrated to a local build (like from the homebrew formula).

Thank you!

Peter

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Mon Apr 12 14:44:32 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true
```

**Output of `docker info`:**

```
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

- local VMWare host

**Comment by ndeloof** [comment]
We don't manage the compose homebrew installation
If you don't have Docker Desktop installed, I assume you only target remote docker hosts?

"new" Docker compose is actually a CLI plugin, you can download release package from github release page and install `docker-compose` binary into your `~/.docker/cli-plugins` folder

**Comment by logopk** [comment]
> We don't manage the compose homebrew installation
> If you don't have Docker Desktop installed, I assume you only target remote docker hosts?

exactly - started with macOS docker-machine a long time ago.

> 
> "new" Docker compose is actually a CLI plugin, you can download release package from github release page and install `docker-compose` binary into your `~/.docker/cli-plugins` folder

Like buildx?

**Comment by ndeloof** [comment]
> Like buildx?

yes, indeed

**Comment by logopk** [comment]
OK, I made it work.

The description is quite confusing - and leeds to an endless loop: docker calling com.docker.cli, calling com.docker.cli, ... hanging the terminal and later the machine

That's what I did to get it up and running (without the cloud integration yet):

```
▶ cd $HOME/.docker/cli-plugins
▶ curl -L https://github.com/docker/compose-cli/releases/download/v1.0.14/docker-darwin-amd64.tar.gz -o docker-cli.tgz
▶ tar xvzf docker-cli.tgz
▶ mv docker/docker-compose .
▶ rm -rf docker-cli.tgz docker

▶ docker compose version
Docker Compose version 2.0.0-beta.1

▶ docker version
Client: Docker Engine - Community
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Mon Apr 12 14:44:32 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true
 
!!! no  Cloud integration  0.1.6 !!!!
```
none of the other commands (for Ubuntu) made it work

**Comment by ndeloof** [comment]
If you only look for `compose` command in Docker CLI you don't need to get "Cloud integration" installed, which is indeed challenging to install as it replaces the `docker` command. This is only needed if you plan to deploy on Amazon ECS or Microsoft ACI.
