### ISSUE TITLE
Docker Compose says Invalid ip address: 8080 with JHipster 7

### ISSUE THREAD

**Issue by mraible** [docker/compose-cli#1652]
**Description**

`docker compose up` does not work as well as `docker-compose up`

**Steps to reproduce the issue:**

Clone my JHipster 7 microservices project:

```
git clone https://github.com/oktadeveloper/java-microservices-examples.git
cd java-microservices-examples/reactive-jhipster
```

Create Docker images for each app. In the {`gateway`, `blog`, `store` } directories, run the following Gradle command:

```
./gradlew -Pprod bootJar jibDockerBuild
```

Then, in the `docker-compose` directory, start everything:

```
docker compose up
```

You'll get an error. However, if you use `docker-compose up`, everything will work.

**Describe the results you received:**

```
The new 'docker compose' command is currently experimental. To provide feedback or request new features 
please open issues at https://github.com/docker/compose-cli
1 error(s) decoding:

* error decoding 'Ports': Invalid ip address: 8080
```

**Describe the results you expected:**

I expect it to work the same as `docker-compose up`.

**Output of `docker version`:**

```
Docker version 20.10.5, build 55c4c88
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.6.0)

Server:
 Containers: 8
  Running: 8
  Paused: 0
  Stopped: 0
 Images: 8
 Server Version: 20.10.5
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 10
 Total Memory: 19.55GiB
 Name: docker-desktop
 ID: CZ5P:AXAW:7QOK:H6CA:HVKU:UOIB:QX65:46OB:3I46:RQKB:DM3B:6DU5
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

local

**Comment by StefanScherer** [comment]
Hi @mraible 
Thank you for the report. We really like to get feedback from users trying the new `docker compose` commands. We don't plan to be 100% compatible with the classic `docker-compose`, but follow the current compose spec.

We had a quick look at your `docker-compose.yml` and it has a little weird line at https://github.com/oktadev/java-microservices-examples/blob/main/reactive-jhipster/docker-compose/docker-compose.yml#L19

```yaml
    ports:
      - "8080:8080:8080"
```

It looks to me that this is a typo and maybe the old `docker-compose` has ignored it.
Could you update your `docker-compose.yml` and put only `"8080:8080"` in it and let me know if that solves your problem?
Thanks.

**Comment by ndeloof** [comment]
I created https://github.com/oktadev/java-microservices-examples/pull/23 to fix and upgrade your compose file to match recent docker <space and dash> compose releases.

**Comment by johnwonder** [comment]
get it
