### ISSUE TITLE
Multiple host ports binding on the same container port fails (only 1 host--1 container port binding seams possible)

### ISSUE THREAD

**Issue by lucantolinos** [docker/compose-cli#1690]
**Description**
Hello,
I want to bind **two host port** 8000 and 8001 **on the same container port** 80. 
With docker-compose it's OK, I've got hosts ports 8000 and 8001 redirecting to port 80 inside the container. With 'docker compose' only the last line of port binding is taken into account (suppose it overrides previous configuration line for the same container port).

**Steps to reproduce the issue:**
1.
I use the following minimalist docker-compose.yml file with nginx hello world :
> version: "3"
> 
> services:
>   client:
>      image: nginx
>      ports:
>       - 8000:80
>       - 8001:80

2.
> docker-compose -f docker-compose.yml up

`docker ps` give me:

> CONTAINER ID   IMAGE     COMMAND                  CREATED         STATUS         PORTS                                                                          NAMES
> e544ffe1e47f   nginx     "/docker-entrypoint.…"   7 seconds ago   Up 2 seconds   0.0.0.0:8000->80/tcp, 0.0.0.0:8001->80/tcp, :::8000->80/tcp, :::8001->80/tcp   tmp_client_1
==> Ports 8000 and 8001 are opened on host and bind on the 80 in container.
3.
Same thing with 'docker compose' : 
> docker_ compose -f docker-compose.yml up

> 87389e17b0ea   f0b8a9a54136   "/docker-entrypoint.…"   3 hours ago   Up 3 seconds   0.0.0.0:8001->80/tcp, :::8001->80/tcp   tmp_client_1
==> As you can see, only port 8001 is bind. 

**Describe the results you received:**
Only 1 port is bind on the container, 2 were expected.

**Describe the results you expected:**
Host ports 8000 and 8001 redirect to 80 inside the container

**Additional information you deem important (e.g. issue happens only occasionally):**
Try with "bridge" network mode but with the same behavior. Work flawless with docker-compose.

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 24
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.776GiB
 Name: docker-desktop
 ID: PNV5:MDVI:JZQK:TS35:S4Q7:437Q:6VCD:QZ3H:7FX6:CIYB:BMIX:NB7T
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

Regards
Luc;

**Comment by ndeloof** [comment]
duplicate https://github.com/docker/compose-cli/issues/1655
