### ISSUE TITLE
Question: Is this project supported as a Go library?

### ISSUE THREAD

**Issue by cszatmary** [docker/compose-cli#1705]
Is this project supported as a library, or is it only intended to be the implementation for the `docker compose` CLI? That is, can the Go packages in this repository be imported and used by other Go programs?

If the answer to the above is no, has there been any consideration given to supporting this in the future?

For context, I work on a Go CLI that manages docker containers under the hood. For pure docker functionality I use the `github.com/docker/docker/client` package. However, in some cases I need access to compose functionality. In those cases I currently use `os/exec` to run `docker-compose` as a subprocess. Now that there is a Go implementation of compose thanks to this project, I was wondering if it would be possible to have an official Go library for compose.

**Comment by ndeloof** [comment]
Hi.

This is under consideration, but you should wait for compose v2 to be stable, as there are a bunch of refactoring planned. Basically, you could rely on the [compose.API](https://github.com/docker/compose-cli/blob/main/api/compose/api.go) as a stable abstraction so "compose-in-go" cna be used as a library, but we have to move the `Up` command as API implementation, not as a cli command run function.

**Comment by cszatmary** [comment]
Thanks for the response. Glad to know that this is under consideration.

**Comment by ndeloof** [comment]
right, basically as "anything public on github can be a Goland dependency" better we consider this a requirement :D

**Comment by cszatmary** [comment]
Yeah exactly. I was thinking should I just run `go get github.com/docker/compose-cli` and see if it works? But I figured it's better to ask and see if this is actually a supported use case. I don't want to risk things breaking because I'm using this project in an unsupported way.
