### ISSUE TITLE
New Docker compose CLI does not support setting the scale value as an environment variable

### ISSUE THREAD

**Issue by jflheureux** [docker/compose-cli#1725]
**Description**

Unlike the `docker-compose` CLI, the new `docker compose` CLI does not support setting the scale value of a service using an environment variable. Here are example files:

`.env`
```
TEST_SCALE=1
```

`docker-compose.yml`
```
services:
  test:
    image: docker/getting-started
    scale: ${TEST_SCALE}
```

CLI commands:
- `docker-compose config` displays the config.
- `docker compose config` (or other commands as `docker compose up`) displays an error "services.test.scale must be a integer".

**Steps to reproduce the issue:**
1. Create an `.env` and a `docker-compose.yml` file as described above.
2. Run the `docker compose config` CLI command.

**Describe the results you received:**

The error "services.test.scale must be a integer" is displayed.

**Describe the results you expected:**

I expect the docker compose commands to be successful like with the `docker-compose` CLI. 

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:49:36 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.24)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:45:40 2021
  OS/Arch:          windows/amd64
  Experimental:     true
```

**Output of `docker context show`:**  

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 0
  Paused: 0
  Stopped: 1
 Images: 2854
 Server Version: 20.10.6
 Storage Driver: windowsfilter (windows) lcow (linux)
  Windows:
  LCOW:
 Logging Driver: json-file
 Plugins:
  Volume: local
  Network: ics internal l2bridge l2tunnel nat null overlay private transparent
  Log: awslogs etwlogs fluentd gcplogs gelf json-file local logentries splunk syslog
 Swarm: inactive
 Default Isolation: hyperv
 Kernel Version: 10.0 18363 (18362.1.amd64fre.19h1_release.190318-1202)
 Operating System: Windows 10 Enterprise Version 1909 (OS Build 18363.1556)
 OSType: windows
 Architecture: x86_64
 CPUs: 12
 Total Memory: 31.81GiB
 Name: LT-JEL-T-CA
 ID: WLQO:DX2T:MOQH:HMR2:3N2S:XWEW:CX6F:7MMS:DK33:UP3M:4UU2:6EM7
 Docker Root Dir: C:\ProgramData\Docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Comment by ndeloof** [comment]
That's indeed a bug in github.com/compose-spec/compose-go.
Investigating

**Comment by mdemierre** [comment]
@ndeloof might be related to the newer #1734, also about environment variable substitution

**Comment by ndeloof** [comment]
go-yaml unfortunately don't give much flexibility so we could interpolate variables before the yaml node tree is translated into go structs. see https://github.com/go-yaml/yaml/issues/158 and https://github.com/go-yaml/yaml/issues/437

**Comment by ndeloof** [comment]
compose-go dependency has been updated with required fix.
