### ISSUE TITLE
Disabling healthcheck with healthcheck.disable: true does not work

### ISSUE THREAD

**Issue by Strayer** [docker/compose-cli#1726]
**Description**

I'm trying to disable the builtin HEALTHCHECK of an image. This works with `docker-compose` but not with `docker compose`.

**Steps to reproduce the issue:**
1. create a Dockerfile with HEALTHCHECK and a docker-compose.yml (see example below)
2. run the container with `docker-compose up -d`
3. confirm that the healthcheck is disabled with `docker inspect healthcheck-test_test_1`
4. clean up with `docker-compose down`
5. run the container with `docker compose up -d`
6. confirm that the healthcheck is *NOT* disabled with `docker inspect healthcheck-test_test_1`

**Describe the results you received:**

The healthcheck is not disabled and shows up in `docker inspect`:

```
      "Healthcheck": {
        "Test": [
          "CMD-SHELL",
          "true"
        ],
        "Interval": 1000000000
      },
```

**Describe the results you expected:**

The healthcheck should be disabled and does not show up in `docker inspect`:

```
      "Healthcheck": {
        "Test": [
          "NONE"
        ],
        "Interval": 1000000000
      },
```

**Additional information you deem important (e.g. issue happens only occasionally):**

Example Dockerfile:

```Dockerfile
FROM debian:buster

HEALTHCHECK --interval=1s CMD true

CMD sleep 1000
```

Example docker-compose.yml:

```yaml
version: "3.8"

services:
  test:
    build: .
    healthcheck:
      disable: true
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.2)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 6
  Running: 0
  Paused: 0
  Stopped: 6
 Images: 14
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 19.55GiB
 Name: docker-desktop
 ID: DHFX:72K2:OEY3:Y2W7:MRCG:D25P:XHUX:XPJ6:LE6I:Q3DU:UBF2:FOTZ
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

I'm using compose-cli version v1.0.16 downloaded from the releases here and put at ~/.docker/cli-plugins/docker-compose.

This also happens when using my local docker setup (see above) using a SSH context to my Unraid server running Docker 20.10.5, so this is most likely not related to Docker for Mac.

Note that setting `test: ["NONE"]` instead of `disable: true` DOES seem to work.

**Comment by ndeloof** [comment]
fixed by https://github.com/docker/compose-cli/commit/907e8e1f24f59beb653b57af66439194c5a9a969

**Comment by Strayer** [comment]
Thank you for fixing this, @ndeloof!
