### ISSUE TITLE
compose-cli fails to install on CircleCI ubuntu-2004:202104-01 image

### ISSUE THREAD

**Issue by khein-wherewolf** [docker/compose-cli#1727]
**Description**

compose-cli fails to install on the CircleCI machine image ubuntu-2004:202104-01.  This had previously been working last week.  Likely the reason for failure was introduced with the latest release.

Installing with:  
curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh

Now get the following error:

#!/bin/bash -eo pipefail
curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5818  100  5818    0     0  35048      0 --:--:-- --:--:-- --:--:-- 35048
Running checks...
Checks passed!
Downloading CLI...
Downloaded CLI!
Installing CLI...
Error: Docker Compose CLI installation error

When running 'docker' after the install, get the following error.

 docker
-bash: /usr/local/bin/docker: cannot execute binary file: Exec format error

**Comment by ndeloof** [comment]
We are working on isolating the "compose 2.0" code and both the release packaging and install script has been updated accordingly. But this isn't supported by any release so far, so the failure of this script as you use the one from `main` branch, You should rely on latest tag: https://raw.githubusercontent.com/docker/compose-cli/v1.0.16/scripts/install/install_linux.sh

**Comment by gabrieldemarmiesse** [comment]
Maybe let's update https://github.com/docker/compose-cli/blob/main/INSTALL.md#install-script ? Or would it be a pain to change the URL at each release?

**Comment by ndeloof** [comment]
@gabrieldemarmiesse this is temporary. Once 1.0.17 / 2.0.0-beta.3 have been released, script from `HEAD` will be fine
