### ISSUE TITLE
Environment Variables are not substituted properly when referencing Build Arguments

### ISSUE THREAD

**Issue by iveelsm** [docker/compose-cli#1734]
**Description**

`docker-compose build` and `docker compose build` produce different behaviors when using environment variables that are set with build arguments. As an example, below is a demonstration of a failure to authenticate to a private NPM registry when a build argument is used for the `NPM_TOKEN` authentication. `docker-compose build` is able to produce a successful build output when using a private registry. `docker compose build` however consistently fails to authenticate with the registry. This does appear to occur with **all environment variables being referenced by build arguments**, the NPM example is a demonstration of this.

Below is the setup for the private package registry with NPM.

**Dockerfile**
```Dockerfile
FROM node:14.17.0

ARG NPM_TOKEN
ENV APP_HOME /home/app/
ENV NPM_TOKEN ${NPM_TOKEN}

RUN mkdir -p ${APP_HOME}
ADD package.json package-lock.json .npmrc ${APP_HOME}
RUN npm ci
```

**.npmrc**
```
registry=https://npm.pkg.github.com/<organization omitted>
//npm.pkg.github.com/:_authToken=${NPM_TOKEN}
```

**docker-compose.yml**
```yaml
version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - NPM_TOKEN=${NPM_TOKEN}
```

**Steps to reproduce the issue:**

1. Run `docker compose build`

**Describe the results you received:**

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/9967497/120553619-f0b7b400-c3b5-11eb-9436-2422b924154e.png">

**Describe the results you expected:**

<img width="1434" alt="image" src="https://user-images.githubusercontent.com/9967497/120553654-f9a88580-c3b5-11eb-85dd-136fb9e9d06d.png">

**Additional information you deem important (e.g. issue happens only occasionally):**

N/A

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true
Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)
Server:
 Containers: 13
  Running: 0
  Paused: 0
  Stopped: 13
 Images: 91
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.941GiB
 Name: docker-desktop
 ID: IJJQ:VGBY:ZLEB:53RW:5WLB:KTUW:E5YU:P3OZ:HI7T:2IAE:AQAE:5QV7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 ```
 
**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

This occurs on locally on a Macbook Pro

**Comment by mdemierre** [comment]
I hit the same issue.

Note that this is a general issue, not related to NPM. Environment variables don't seem to be substituted correctly with `docker compose` (at least for build arguments).

The following minimal example shows the issue:

docker-compose.yml

```yml
version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - MY_ARG=${MY_ARG_ENV_OUTSIDE}
```

Dockerfile:

```dockerfile
FROM alpine:latest

ARG MY_ARG
ENV MY_ARG_ENV_INSIDE ${MY_ARG}

RUN echo "MY_ARG: ${MY_ARG}" >my_arg.txt
RUN echo "MY_ARG_ENV_INSIDE (build): ${MY_ARG_ENV_INSIDE}" >my_arg_env_inside_build.txt
```

Building:

```bash
export MY_ARG_ENV_OUTSIDE='helloworld'
docker compose build
```

With `docker compose`, `$MY_ARG` has an empty value at build time, with `docker-compose` it has the correct value `helloworld`.

@iveelsm Maybe we can make the title more generic?

**Comment by iveelsm** [comment]
@mdemierre I adjusted the title and ticket to make it more generic, hopefully that helps funnel the discussion.

**Comment by ndeloof** [comment]
Duplicate https://github.com/docker/compose-cli/issues/1665
This issue has been fixed already, will be delivered in next Docker Desktop release
