### ISSUE TITLE
Support for custom backends?

### ISSUE THREAD

**Issue by decentral1se** [docker/compose-cli#1744]
I am not sure where to raise questions but I am wondering if custom backends will be supported?

Then we can target other orchestrators like https://github.com/docker/compose-cli/issues/1350, Hashicorp Nomad, etc.

**Comment by ndeloof** [comment]
This is something under consideration, but the actual architecture is going to evolve in the incoming weeks to extract compose V2 "local backend" into a new home.
So better wait before you start investing time into an implementation :P
