### ISSUE TITLE
up creates default network even when not used

### ISSUE THREAD

**Issue by BretFisher** [docker/compose-cli#1756]
**Description**

Unlike `docker-compose`, `docker compose` will create the default network even when the service only lists a custom network.

**Steps to reproduce the issue:**
1. Create a compose file in a directory called `redis`

```yaml
services:
  redis:
    image: redis:6
    networks:
      - front-tier

networks:
    front-tier:
```

2. `docker compose up -d`
3. You'll see the CLI create two networks: `redis_front-tier` and `redis_default`.

**Describe the results you received:**

Compose creates two networks, even though the default isn't used.

**Describe the results you expected:**

When no services use the default network (or don't list a custom network), then the default network isn't created.

**Output of `docker compose version`:**

```
docker compose version
Docker Compose version 2.0.0-beta.3
```

**Output of `docker version`:**

```
docker version
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by ndeloof** [comment]
internally tracked as https://docker.atlassian.net/browse/IL-241

**Comment by ndeloof** [comment]
with the introduction for "profiles", it would actually make sense `up` filter the networks/volumes actually required for the active set of services, and ignore others that are declared in the compose model but not in use
