### ISSUE TITLE
Option to merge override env vars instead of replacing

### ISSUE THREAD

**Issue by atassis** [docker/compose-cli#1778]
**Description**

In current state `docker-compose.override.yml` rewrites env variables when `environment` is being set in service. I am interested if you can provide an option to merge variables into existing ones, so we don't have to copy paste environmentss (it might be inconvenient when a lot of variables was set)

**Comment by ndeloof** [comment]
If I misunderstood your need, please provide an illustration example (and maybe some more context about your use-case)

**Comment by atassis** [comment]
Give me a couple of business days, i'll check it through both versions of compose and summarize everything

**Comment by ndeloof** [comment]
sure :+1:

**Comment by atassis** [comment]
Ok, I have finally checked this, it does well on beta compose, haven't checked on older one, but trying not to use it
