### ISSUE TITLE
compose logs for service not working

### ISSUE THREAD

**Issue by orxelm** [docker/compose-cli#1784]
**Description**
Hi
When trying to `docker compose logs <service_name>` the command hangs.
However, when using just `compose logs` it's working but i get the entire logs from the beggining of the project which is useless when i need the recent.

**Steps to reproduce the issue:**
1. type `docker compose logs <service_name>`
2. shell hangs

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.3)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 19
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.941GiB
 Name: docker-desktop
 ID: 5JKY:DJZQ:3SII:MTSK:QI7S:CRRM:6LXJ:XXVM:IH3X:6ZV4:UHRS:2I5D
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 41
  Goroutines: 45
  System Time: 2021-06-14T06:29:13.9540315Z
  EventsListeners: 3
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Running on AWS with ECS and Fargate.

**Comment by ndeloof** [comment]
On ECS, `compose logs <service>` is actually implemented client-side by filtering logs by service to only show the desired one

Does `docker compose logs` include the logs for the expected service ?

> I get the entire logs from the beggining of the project which is useless when i need the recent

`docker logs` indeed defines the `--since` flag to limit the amount of logs to get back from history, I would make sense for `compose logs` to do the same. I created https://github.com/docker/compose-cli/issues/1786 for this purpose

**Comment by orxelm** [comment]
@ndeloof Thanks for your help.

So, Yes `docker compose logs` indeed contains all services deployed on the desired project on ECS.

However, when trying `docker compose logs <service>` the shell hangs.
Additionally, there's no option to exit the terminal (CMD+C/D) after that, only after killing it. That's also relevant for `docker compose logs`

If you're saying it's client side filtering. Maybe something is breaking on my side?
