### ISSUE TITLE
Failed Authorization on Private Registry with multiple docker-compose.yml

### ISSUE THREAD

**Issue by emmyoop** [docker/compose-cli#1792]
**Description**

I'm using docker compose to dynamically do one of three things:
1. run a python container that connects to an external database
2. run a python container that is networked with a second oracle container
3. run a python container that is networked with a second postgres container

I have my oracle image stored in a private registry.  

Everything works fine when I have already pulled the image.  However, when I do not have the image on my machine it fails to pull the oracle image from my private registry due to auth issues.

**Steps to reproduce the issue:**
1. Use multiple docker-compose files that you combine on run.  At least one of the images referenced in the separate ```docker-compose.yml```s should be in a private registry.  
2.  run ```docker compose -f docker-compose-oracle.yml -f docker-compose-dbt-networked.yml -p local_dev up --build --timeout 60 --detach```

I verified I was indeed logged in and the fact that I can make workarounds to the issue shows it's not that I'm not authenticated.

**Describe the results you received:**
Auth error as if I'm not logged in:

```
failed to solve: rpc error: code = Unknown desc = failed to solve with frontend dockerfile.v0: failed to create LLB definition: pull access denied, repository does not exist or may require authorization: server message: insufficient_scope: authorization failed
```

**Describe the results you expected:**
The image is pulled from the private registry.

**Additional information you deem important (e.g. issue happens only occasionally):**

This works when I do any of the following:
- using ```docker-compose``` instead of ```docker compose```
- there is only one ```docker-compose.yml```
- I add ```docker compose -f docker-compose-oracle.yml pull``` before the ```docker compose -f docker-compose-oracle.yml -f docker-compose-dbt-networked.yml -p local_dev up --build --timeout 60 --detach```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:46:57 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 2
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 20.10.6
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc version: 12644e614e25b05da6fd08a38ffa0cfe1903fdec
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 6
 Total Memory: 1.941GiB
 Name: docker-desktop
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Local development with a private registry.

**Comment by ndeloof** [comment]
This has already been fixed by https://github.com/docker/compose-cli/commit/fe085df7b7692deee9464989dbe7470062cf7e7c

will be available in next release
