### ISSUE TITLE
With docker binaries of v1.0.14 or later, the "docker compose" command will fail on Ubuntu Server 20.04.

### ISSUE THREAD

**Issue by kemokemo** [docker/compose-cli#1794]
Hi! I am new to the compose-cli tool. I am trying to use this tool on Ubuntu Server 20.04.

**Description**

With docker binaries of `v1.0.14` or later, the `docker compose` command will fail.

**Steps to reproduce the issue:**
1. Use the [Install script](https://github.com/docker/compose-cli/blob/main/INSTALL.md#install-script) to install.
2. Run the `docker compose` command.

**Describe the results you received:**

```sh
docker: 'compose' is not a docker command.
See 'docker --help'
```

![image](https://user-images.githubusercontent.com/12206485/122033646-adc0fc00-ce0b-11eb-8692-5ca6acb6b287.png)

**Describe the results you expected:**

![image](https://user-images.githubusercontent.com/12206485/122036639-c0890000-ce0e-11eb-8153-d2fbcc4cd5be.png)

If you have the `v1.0.13` docker binary, it will work as intended.

**Additional information you deem important (e.g. issue happens only occasionally):**

![image](https://user-images.githubusercontent.com/12206485/122037734-d814b880-ce0f-11eb-8090-60d0634af281.png)

There are more docker-compose binaries in `v1.0.14` and later versions, is there any relation?

**Output of `docker version`:**

This is the output result of the installation with [Install script](https://github.com/docker/compose-cli/blob/main/INSTALL.md#install-script).

```
Client: Docker Engine - Community
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:38 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  

This is the output result of the installation with [Install script](https://github.com/docker/compose-cli/blob/main/INSTALL.md#install-script).

```
default
```

**Output of `docker info`:**

This is the output result of the installation with [Install script](https://github.com/docker/compose-cli/blob/main/INSTALL.md#install-script).

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 2
  Running: 0
  Paused: 0
  Stopped: 2
 Images: 1
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-74-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 15.61GiB
 Name: kemo-server
 ID: IIXG:3DNI:AP56:GVFR:WD3J:UGSB:NX73:E4Q7:6U7X:ABQS:5QYJ:YEQL
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by ndeloof** [comment]
̀ docker compose` is not bundled in Compose-CLI ("Cloud Integrations") since 1.0.16, 
You don't need it if you don't need ECS/ACI support, and will just need to install the compose CLI plugin, see https://github.com/docker/compose-cli#compose-v2-aka-local-docker-compose

**Comment by chiptus** [comment]
> ̀ docker compose` is not bundled in Compose-CLI ("Cloud Integrations") since 1.0.16,
> You don't need it if you don't need ECS/ACI support, and will just need to install the compose CLI plugin, see https://github.com/docker/compose-cli#compose-v2-aka-local-docker-compose

I followed the following instructions and `docker compose` is still not working for me.
> Compose v2 can be installed manually as a CLI plugin, by downloading latest v2.x release from https://github.com/docker/compose-cli/releases for your architecture and move into ~/.docker/cli-plugins/docker-compose

Is there anything else I should do? `chmod` the file?

btw, `docker plugin ls` doesn't show anything

**Comment by chiptus** [comment]
yes. when I ran `docker` I saw the regular output and on the last lines I saw:
```
Invalid Plugins:
  compose     failed to fetch metadata: fork/exec /home/chiptus/.docker/cli-plugins/docker-compose: permission denied
```

running `chmod +x ~/.docker/cli-plugins/docker-compose` fixed it and now `docker compose` works

**Comment by ndeloof** [comment]
`docker plugin ls` list _engine_ plugins, not CLI plugins
