### ISSUE TITLE
Critical: New Docker Desktop 3.4.0 policy causes local data loss

### ISSUE THREAD

**Issue by beaugunderson** [docker/compose-cli#1796]
From 3.4.0 release notes:

> Automatically reclaim space after deleting containers by deleting volumes and removing build cache.

I have aliases for running one-off commands for my images like `alias drm="docker compose run --rm web ./manage.py"` that now cause the removal of my database volume and all of its data in 3.4.0.

In my `docker-file.yml` `web` `depends_on` `db`.

It appears that all volumes for everything that `web` `depends_on` are deleted, including my `rabbitmq` and `redis` containers.

  - [x] I have tried with the latest version of Docker Desktop
  - [x] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior

My database volumes are not deleted.

### Actual behavior

My database volumes are deleted.

**Comment by ndeloof** [comment]
I tried to reproduce your using this compose file:
```yaml
services:
  web:
    image: nginx
    depends_on: 
      - db
  db:
    image: postgres
```
Started clean:
```
➜  docker volume ls
DRIVER    VOLUME NAME
➜  docker ps -a
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
➜  
```

Ran `docker-compose run --rm web echo hello`

After completion, volume is still present
```
➜  docker volume ls
DRIVER    VOLUME NAME
local     42dc522c5e4f7f028d0fd00e071e3eb933169599f9a8ad07f6aeb53d2ec696b3
```

Tested both with docker-compose v1 and v2
Please provide output for `docker-compose version` so I know which version to check

Could you please give this minimalist example a try, and confirm you still get into this issue?
Or maybe provide a reproduction example I could use to diagnose this error

**Comment by beaugunderson** [comment]
Now that I've rolled back to 3.3 my `docker compose` version shows as:

```
Docker Compose version 2.0.0-beta.1
```

I didn't check when on 3.4.0 but am unable to use 3.4.0 due to the hit in
productivity.

**Comment by ndeloof** [comment]
3.4.0 includes Docker Compose version 2.0.0-beta.3 which includes a bunch of fixes (many of those related to volumes / bind mount issues)

If you get issues on 3.4.0 with compose v2 you can switch back to "legacy" docker-compose 1.29 using `docker-compose disable-v2`, so no reason to keep using 3.3

**Comment by beaugunderson** [comment]
Ah, at some point I will upgrade to 3.4.0 and try legacy docker-compose to
see if the issue still happens.

**Comment by mat007** [comment]
Could this be https://github.com/docker/for-mac/issues/5754 and not related to compose?

**Comment by beaugunderson** [comment]
in my specific case, no—the upgrade left my containers intact but the
first time I ran a “run —rm” command everything got deleted

**Comment by maxfierke** [comment]
>  @maxfierke could this be https://github.com/docker/for-mac/issues/5754 and not related to compose?

Yes, very likely! Will verify later but would bet my hat. Thanks for the linking!
