### ISSUE TITLE
`docker compose up` resurrects previously `run` containers despite `restart: no`

### ISSUE THREAD

**Issue by jamshid** [docker/compose-cli#1807]
**Description**

When I `docker compose up` my project compose v2 is resurrecting containers that were created with `docker compose run -d --no-deps myservice` even though they `Exited (0)` long ago and have an explicit `restart: no`. 

I don't know how v1 `docker-compose` knew not to resurrect `run` containers, maybe it simply never restarted them? Do I now need to explicitly remove `run` containers or is there a way to make `docker compose up` only restart the services listed in my yml?

**Steps to reproduce the issue:**
1. Sorry will make a repro soon if you need it.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker Compose version 2.0.0-beta.3
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by ndeloof** [comment]
Confirmed `compose up` do restart one-off containers, which is a bug.

**Comment by ndeloof** [comment]
fixed by https://github.com/docker/compose-cli/commit/852aae0a398c828f1a5d4fb347985d0e96311ca0
