### ISSUE TITLE
v1 incompatibility: volumes not automatically attached to `docker compose run` containers

### ISSUE THREAD

**Issue by jamshid** [docker/compose-cli#1808]
**Description**

When I `docker-compose run -v myvol ...` a service the container will have all the volumes in the `volumes:` section of the yml in addition to the one I specify on the run command. But with `docker compose run` the volumes in the yml are not available, I have to explicitly add them all with `docker compose run -v myvol -v ...`.

**Steps to reproduce the issue:**
1. Using this docker-compose.yml, run `docker-compose up -d`.
```
services:
   myservice:
      image: centos
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      command: "sleep 900"
```
2. Do a `docker-compose run` with a volume, see that both the specified volume and the one from yml are there:
```
% docker-compose run -v /myvol myservice bash
WARNING: Found orphan containers (test_test_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating test_myservice_run ... done
[root@6d26e74965ce /]# ls -ld /myvol /var/run/docker.sock
drwxr-xr-x 2 root root 4096 Jul  8 17:57 /myvol
srwxr-xr-x 1 root root    0 Jun 30 14:36 /var/run/docker.sock
```
3. Do an identical `docker compose run` with a volume, see that only the specified volume is there.
```
% docker compose run -v /myvol myservice bash
WARN[0000] Found orphan containers ([test_test_1]) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up. 
[root@e3e0cf8fb250 /]# ls -ld /myvol /var/run/docker.sock
ls: cannot access '/var/run/docker.sock': No such file or directory
drwxr-xr-x 2 root root 4096 Jul  8 17:57 /myvol
```

**Describe the results you received:**

`volumes:` in yml not automatically attached to `docker compose run` containers *if the `run` command specifies any volumes*.

**Describe the results you expected:**

Compatibility with `docker-compose run` or explicit statement of why behavior s changing.

**Output of `docker version`:**

```
Docker Compose version 2.0.0-beta.4
```

**Comment by ndeloof** [comment]
I tried to reproduce but I get expected volumes/bind mounts set on `run` container.
Could you please prepare a reproduction example?

**Comment by jamshid** [comment]
hi @ndeloof I added a sample let me know if any problems reproducing this

**Comment by ndeloof** [comment]
This is actually already fixed by https://github.com/docker/compose-cli/pull/1914
Closing as duplicate
