### ISSUE TITLE
Error response from daemon: Duplicate mount point: /var/lib/postgresql/data/

### ISSUE THREAD

**Issue by butuzov** [docker/compose-cli#1811]
Issue happening with postgress container with docker volume (`postgress`) and mounted path (`./postgresql`). this two combination can't be used together, and failing with an error. ~~Once the physical directory mapping removed error is gone.~~ 
update: somehow it doesn't fix the issue anymore, rolled back to 3.3.3

## Checklist
  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
 

### Expected behaviour

docker compose's described containers starts

### Actual behaviour

fails with error

### Information
 
Please, help us understand the problem.  For instance:
  - Is it reproducible?
    > yes
  - Is the problem new?
    > yes
  - Did the problem appear with an update?
    > yes
  - A reproducible case if this is a bug, Dockerfiles FTW.
    > see next info.

  - macOS Version: mojave
  - Intel chip or Apple chip: intel
  - Docker Desktop Version: v20.10.7

### Steps to reproduce the behavior
```yaml
version: '3.2'
services:

  postgres:
    ports:
      - 6432:5432
    image: postgres:13
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data/
      - ./postgresql:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_MULTIPLE_DATABASES: db1,db2,db3

  mongodb:
    container_name: mongodb
    image: mongo:4.4.6
    volumes:
    - mongo:/data/db
    ports:
    - 27017:27017

volumes:
  postgres: {}
  mongo: {}

```

```shell
 > task up
task: [up] docker-compose -f .sandbox/docker-compose.yaml -p Project up -d postgres
[+] Running 3/1
 ⠿ Network Project_default    Created                                                                                                                                                                                           3.9s
 ⠿ Volume "Project_postgres"  Created                                                                                                                                                                                           0.0s
 ⠿ Volume "Project_mongo"     Created                                                                                                                                                                                           0.0s
 ⠋ Container postgres                 Creating                                                                                                                                                                                          0.1s
Error response from daemon: Duplicate mount point: /var/lib/postgresql/data/
```

**Comment by ndeloof** [comment]
This issue has been fixed already by https://github.com/docker/compose-cli/pull/1782

**Comment by StefanScherer** [comment]
Thanks @ndeloof that it's already fixed!

@butuzov As a workaround for now with Docker Desktop 3.4.0 go to the Preferences -> Experimental Features and turn off the Compose V2. The next release of Docker Desktop should have this fix included, then you are encouraged to turn the feature on again. Thanks for giving us feedback to make Compose V2 better!

**Comment by thorfi** [comment]
Better workaround without having to turn off Compose V2 is to remove the trailing slash from the volumes mount point so it matches the Dockerfile and doesn't trigger the bug:

      - postgres:/var/lib/postgresql/data

(This worked for me, anyway)

**Comment by codyfletcher** [comment]
Thanks @thorfi. This worked for me too! (remove trailing slash)

**Comment by butuzov** [comment]
Docker Desktop - version 3.5.1

`Error response from daemon: Conflict. The container name "/postgres" is already in use by container "590cc0c16d3afe3a8c8a983a6b9bd844941192c3b31da77a2aa9f12d24523e13". You have to remove (or rename) that container to be able to reuse that name.`

Did tried @thorfi's method, not working anymore.
