### ISSUE TITLE
compose v2 is not platform independent

### ISSUE THREAD

**Issue by WolfgangFahl** [docker/compose-cli#1819]
You might want to stay with python so that the installation process is simpler.

**Comment by ndeloof** [comment]
I'm not sure what you mean with this.
Python runtime abstract the platform to make code portable
Golang does the same, but at compile time
In both cases, some code has to be platform specific (typically, managing windows vs linux paths)

**Comment by WolfgangFahl** [comment]
@ndeloof  Thank you for asking.
https://docs.docker.com/compose/cli-command/

Does not realy explain how to install the Plugin.

https://github.com/docker/compose-cli/releases has the release and these are platform dependent.
https://github.com/docker/compose-cli/releases/tag/v2.0.0-beta.3
![grafik](https://user-images.githubusercontent.com/1336221/122728809-c6e90300-d278-11eb-915c-c00706624652.png)

**Comment by ndeloof** [comment]
installation is described here : https://github.com/docker/compose-cli#compose-v2-aka-local-docker-compose

This is a temporary installation process: makes it indeed hard to install the adequate binary if you want to be platform neutral, but as I said it will be bundled with the `docker-ce` system package once released with General Availability status.

That's a bit unfortunate GOARCH don't use the same values as `uname` which would make it simpler to detect the adequate binary to be installed. Will require something comparable to https://github.com/docker/compose-cli/blob/main/scripts/install/install_linux.sh#L109
