### ISSUE TITLE
`docker-compose -f $file ps` has different output than `docker compose -f $file ps`

### ISSUE THREAD

**Issue by agilob** [docker/compose-cli#1828]
>The new Compose V2, which supports the compose command as part of the Docker CLI, is now available as a beta version. Compose V2 seamlessly integrates compose functions into the Docker platform, continuing to support most of the previous docker-compose features and flags. You can test the Compose V2 today, by simply replacing the dash (-) with a space, and running docker compose, instead of docker-compose.

**Description**

**Steps to reproduce the issue:**
1. run the command with new `docker compose` and old `docker-compose`

**Describe the results you received:**
results in standard `docker ps` being executed, not ASCII-table with State column and lists all docker instances, not only these requested by `-f $file` flag

**Describe the results you expected:**
```
❯ docker-compose -f db-mysql.yml ps
           Name                        Command             State                          Ports
----------------------------------------------------------------------------------------------------------------------
compose_database-bbt-alt_1   docker-entrypoint.sh mysqld   Up      0.0.0.0:3307->3306/tcp,:::3307->3306/tcp, 33060/tcp
```

**Comment by ndeloof** [comment]
`docker-compose` has been designed as a separate tool, with it's own UX.
New `docker compose` (Compose v2) being integrated in the Docker CLI is adopting the same UX component, so the change in output

`docker compose ps` is **not** just plain `docker ps`, as it includes `Service` column, we just didn't replicated the "Up" status you might be used to, and preferred to render the container state as "running".

**Comment by ndeloof** [comment]
If there's any specific data you're missing from ̀`compose ps`, please let me know

**Comment by agilob** [comment]
We have a bunch of scripts on dev and jenkins that use Status column, they started braking on dev laptops who tried experimental docker-desktop features on mac. 

Missing data is: filter docker instances by provided file and print the status word Up|Down

**Comment by ndeloof** [comment]
Parsing console formatted output is a fragile approach, it might break for many reasons and there's no guarantee UX never will change

You can use `docker compose ps --format json` to get a computer-friendly status of your services/container and check for status within your scripts.
