### ISSUE TITLE
possible bug with relative paths on remote hosts

### ISSUE THREAD

**Issue by quasis** [docker/compose-cli#1850]
Sample docker-compose.yml:

```
services:
        ....
        volumes:
            - ./host_dir:/container_dir

```

For the sake of example, the current directory is `/mnt/d/work/project`

Running `docker compose up` maps `/container_dir` to the local folder `/mnt/d/work/project/host_dir`, which is expected and totally makes sense.

However, running `DOCKER_HOST=ssh://<user>@<domain> docker compose up` maps `/container_dir` to the **remote** `/mnt/d/work/project/host_dir`, which is not expected and not entirely makes sense. I would expect it to be mapped to `/home/<user>/host_dir`, as when you ssh to the remote host your current directory becomes `/home/<user>`.

**Comment by ndeloof** [comment]
`docker run` does not support relative paths for this exact reason.
`docker-compose` introduced this feature for usability as a local development tool, `docker compose` just does the same for backward compatibility. Both tools assume users running with a remote DOCKER_HOST understand what's they do and don't use relative paths when not relevant.
