### ISSUE TITLE
v1 incompatibility: terminal i/o management on output; impossible copy and output stderr properly

### ISSUE THREAD

**Issue by rfay** [docker/compose-cli#1853]
**Description**

In docker-compose v1 standard terminal management sequences were used to present the output as docker-compose did its work. The characters could be copied by another process and output to the screen and things would look fine.

Now in compose v2, you can't do that. 

**Steps to reproduce the issue:**

```bash
$ docker-compose -f .ddev-docker-compose-full.yaml up 2>&1 | tee
Container ddev-d9-db  Created
Container ddev-d9-web  Created
Container ddev-d9-dba  Created
Container ddev-d9-db  Starting
Container ddev-d9-db  Started
Container ddev-d9-dba  Starting
Container ddev-d9-web  Starting
Container ddev-d9-dba  Started
Container ddev-d9-web  Started
Attaching to ddev-d9-db, ddev-d9-dba, ddev-d9-web
```

**Describe the results you received:**

Above

**Describe the results you expected:**

<img width="1049" alt="output" src="https://user-images.githubusercontent.com/112444/123692922-a38ffc00-d814-11eb-89e3-6a4985339948.png">

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:23 2021
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:55:36 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
desktop-linux
```

**Output of `docker info`:**

```
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.4)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 9
  Running: 4
  Paused: 0
  Stopped: 5
 Images: 174
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runtime.v1.linux runc io.containerd.runc.v2
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 5.8GiB
 Name: docker-desktop
 ID: 53UE:EPJ4:JJNQ:JFFR:DIZ4:RKDH:DZOT:O2RE:53SK:6Z4G:7A7B:NPHD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false


```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

macOS Docker Desktop 3.5.1

**Comment by ndeloof** [comment]
Once you pipe `docker compose` to another process, the command don't run anymore with a terminal but with POSIX streams (stdin/stdout/stderr). A TTY is required to render the multi-line progress status, otherwise compose switch to plain-text events.

I'll check how `docker-compose` manage this. I wonder it still produces ANSI codes, whenever not running inside a terminal (which would explain another set of usability issues).

**Comment by ndeloof** [comment]
confirmed, using `docker-compose up | tee foo.log` I get a log file to include ansi escape codes:
```txt
Creating foo_test_1 ... 
Creating foo_test_1 ... done
Attaching to foo_test_1
[36mtest_1  |[0m /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
[36mtest_1  |[0m /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
...
```
... which is not desirable either.
`docker compose` detect a terminal is available and only enable formatted output in this context.

Funny (?) details: `docker-compose` progress creating resources does **not** use ANSI code when used in this context but render progress events line-by-line in plain ASCII, while the container logs still used colored-text for services prefix. This inconsistent behavior could be considered a bug, which has been "fixed" in compose v2.

Closing this issue as "won't fix"

**Comment by rfay** [comment]
At this point the only way to have decent output from docker-compose (with compose v2) is to introduce a pty to fool compose. I guess. Sounds like too much work.

**Comment by ndeloof** [comment]
We could consider introducing a `--ansi` flag for the same purpose we support `--no-ansi`. Please open a feature request if you feel this could be useful

**Comment by rfay** [comment]
I'll probably just have to filter all the ugly output. May be able to do it in a way that's backward compatible.

Please remember that docker-compose v1 will live on for several years, and ddev will need to work with it. It's not like every user can just switch. People on Ubuntu 20.04 for example will be on v1 likely until 2025. Maybe longer.

**Comment by ndeloof** [comment]
We still need to define compose.v1 End of Life policy, but this clearly won't be supported for years.
Once released as General Availability, compose.v2 will be bundled with docker-ce system package, so will be available for any up-to-date installation.

**Comment by rfay** [comment]
That will be amazing for compose to finally be bundled on Linux (never understood why it wasn't). But it doesn't solve the problem, because on recent versions of Debian-derived Linux the OS-provided docker-compose is fine, so it's sitting out there. Most people don't ever need to install the docker-ce packages.
