### ISSUE TITLE
"network default: network.external.name is deprecated in favor of network.name"

### ISSUE THREAD

**Issue by rfay** [docker/compose-cli#1856]
**Description**

In compose v2 I always see 
> "network default: network.external.name is deprecated in favor of network.name"

For every docker-compose command. 

Here's the networks stanza:

```yaml
networks:
  default:
    name: ddev_default
    external: true
```

This appears to be the exact same as is suggested in the official docs at https://docs.docker.com/compose/networking/#use-a-pre-existing-network - nothing about deprecation there.

And I also don't see `network.external.name` being used here. It's network.external as a bool, right?

**Steps to reproduce the issue:**

Use the network stanza above.

**Describe the results you received:**

> "network default: network.external.name is deprecated in favor of network.name"

**Describe the results you expected:**

No deprecation complaint. Or at least one that I can understand.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:23 2021
 OS/Arch:           darwin/arm64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:55:36 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker context show`:**  

```
desktop-linux

```

**Output of `docker info`:**

```
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.4)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 10
  Running: 5
  Paused: 0
  Stopped: 5
 Images: 174
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 5.8GiB
 Name: docker-desktop
 ID: 53UE:EPJ4:JJNQ:JFFR:DIZ4:RKDH:DZOT:O2RE:53SK:6Z4G:7A7B:NPHD
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false


```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

This is Docker Desktop 3.5.1 on either macOS or Windows. 

```
$ docker-compose --version
Docker Compose version 2.0.0-beta.4
```

**Comment by ndeloof** [comment]
I was not able to reproduce this issue

tested with:
```yaml
services:
  test:
    image: nginx
networks:
  default:
    name: ddev_default
    external: true
```

```console
$ docker-compose compose up
[+] Running 1/1
 ⠿ Container truc_test_1  Started                                                                                             2.0s
Attaching to test_1
test_1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
...
```

Can you please prepare a minimal reproduction example?

**Comment by ndeloof** [comment]
for your information, at some point compose file syntax we defined as:
```
networks:
  default:
    external: 
      name: ddev_default
      external: true
```
This was error prone and has been redesign to let user adopt the current syntax, passing `external: true`. This deprecation notice is here for this specific scenario, but should not be triggered if you don't use this legacy syntax

I notice you use `ddev`, do you directly run docker-compose with your own compose file, or the one managed by ddev under the hood?

**Comment by ndeloof** [comment]
see https://github.com/drud/ddev/blob/master/pkg/ddevapp/templates.go#L190-L193

**Comment by rfay** [comment]
I am the maintainer of ddev, trying to get it to work with new compose v2 :)

I'm sorry, I'm still missing the point I guess. The docs clearly show the syntax ddev is using here, don't they? https://docs.docker.com/compose/networking/#use-a-pre-existing-network 

Am I just blind and I can't see the difference? Can you propose the correct format?

You can recreate this just by using ddev with compose v2:

```bash
mkdir junk
ddev config --auto
ddev start
```

**Comment by ndeloof** [comment]
> I am the maintainer of ddev, trying to get it to work with new compose v2 :)

Oh, nice.
Ping me on docker community slack if you need a hand

reference syntax:
```yaml
networks:
  default:
    external: true
    name: my-pre-existing-network
```

ddev template:
```yaml
networks:
  default:
    external:
      name: ddev_default
```

shoud be:
```yaml
networks:
  default:
    name: ddev_default
    external: true
```

Makes me wonder: as ddev is written in Go, maybe you could use compose-go to build the model and marshall into yaml?

**Comment by rfay** [comment]
What is compose-go?  Would love to know more.

Here's the fix for ddev, https://github.com/drud/ddev/pull/3076

The reason I couldn't see it is that ddev uses `docker-compose config` to parse all the files together to use them as a single file. And of course *there* it was all fixed with the correct syntax. compose was complaining on *reading* but fixing on *writing*, and I was studying the output format, which had been normalized.

**Comment by ndeloof** [comment]
https://github.com/compose-spec/compose-go

**Comment by Mugane** [comment]
Ugh. *What is the correct syntax*??

**Comment by Wilkolicious** [comment]
The [docs](https://docs.docker.com/compose/networking/#use-a-pre-existing-network) still look incorrect.  
For reference at time of this comment:
```
networks:
  default:
    external:
      name: my-pre-existing-network
```
---
Correct syntax:
```
networks:
  default:
    name: my-pre-existing-network
    external: true
```

or

```
networks:
  my-pre-existing-network:
    external: true
```
