### ISSUE TITLE
docker compose v2 empty ports list not allowed

### ISSUE THREAD

**Issue by sfcgeorge** [docker/compose-cli#1861]
**Description**

Setting a service's `ports` to an empty list/array in `docker-compose.yml` and running `docker compose up` fails with the error "services.runner.ports must be a list" in compose v2.

This is problematic when using yaml inheritance. Our base service is our web server which has exposed ports, then we inherit from it for a command runner that doesn't need any ports so we set ports to an empty list.

**Steps to reproduce the issue:**

```yaml
 web: &web
    ports:
     - "3000:3000"

runner:
    <<: *web
    ports: [] # no exposed ports
```

Note the yaml inheritance isn't necessary to cause the bug, it's just the real world scenario where you'd want to set ports to nothing.

**Describe the results you received:**

```
services.runner.ports must be a list
```

**Describe the results you expected:**

An empty list is still a list so I think it should work and the error doesn't make sense. It should just not expose any ports.

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           desktop-linux
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

Docker Desktop Mac local.

**Comment by ndeloof** [comment]
Thanks for reporting.
This has been fixed already by https://github.com/compose-spec/compose-go/pull/151
