### ISSUE TITLE
Volume names were lowercased in docker-compose v1, here they are untouched, causing data loss

### ISSUE THREAD

**Issue by rfay** [docker/compose-cli#1871]
**Description**

In a project with mixed case, like TestServices, If you use docker-compose v1 and have a volume referenced in docker-compose.yaml like this:

```yaml
volumes:
  solr:
```

It will create a volume lowercased, like `ddev-testservices_nfsmount`
```
Creating volume "ddev-testservices_nfsmount" with local driver
```

The same project with compose-cli creates a volume named ddev-TestServices_nfsmount (not lowercased)

Edit: This means that if a volume existed and then compose v2 were switched into use, the existing volume will not be detected/used, and a new (empty) volume will be created, essentially losing the data that was in the original volume. 

In ddev this means that an existing project named SomeProject will may have volumes named
* ddev-someproject_solr
* ddev-someproject_nfsmount

So in this case, the solr database is lost when upgrading to compose-cli v2, because the new and completely separate (empty) volume ddev-SomeProject_solr is created.

**Comment by ndeloof** [comment]
docker-compose indeed force lower-case project name (for ¯\\_(ツ)_/¯ reasons)
https://github.com/docker/compose/blob/4a51af09d6cdb9407a6717334333900327bc9302/compose/cli/command.py#L197-L198

> losing the data that was in the original volume.

not "losing", data is still there. Just not visible by user

**Comment by thaJeztah** [comment]
> for ¯\(ツ)/¯ reasons

More info can be found in https://github.com/docker/compose/pull/568 (and tickets linked to / from that)

The TL;DR is that the project name prefix "leaked through" to many places, and not all of those are either case-sensitive (host names) or even accept uppercase.

Wether or not it should've done the conversion _automatically_ or just produce an error that only lowercase is allowed is another discussion, but I doubt it's easy to change that after so many years

**Comment by rfay** [comment]
> not "losing", data is still there. Just not visible by user

Of course you and I know this is true because we understand the dynamics. But it's definitely data loss from the perspective of an ordinary user experiencing it. 

Thanks for working away on all these!

**Comment by thaJeztah** [comment]
@ulyssessouza should this be reopened until the `go.mod` is updated to use a version of the spec with  https://github.com/compose-spec/compose-go/pull/154 included ?

**Comment by ulyssessouza** [comment]
@thaJeztah Sure! I'll reopen that and propose a PR with the update

**Comment by rfay** [comment]
This doesn't seem to have made it into v2.0.0-beta.6, I guess it will be in the next round?
