### ISSUE TITLE
Compose V2 CLI installation for Linux does not work

### ISSUE THREAD

**Issue by johnwchadwick** [docker/compose-cli#1874]
**Description**

The documentation for [Compose V2](https://docs.docker.com/compose/cli-command/) points to the [scripts/install/install_linux.sh](https://github.com/docker/compose-cli/blob/main/scripts/install/install_linux.sh) script in this repository. However, installing this merely updates the `docker` CLI command. It seems as though the latest (stable) release does not include the Compose V2 CLI, and thus this script does not install it.

If this script is no longer intended to install the Docker Compose CLI (which would be pretty strange,) the documentation probably needs to be updated to explain how to install the Docker Compose CLI plugin manually.

**Steps to reproduce the issue:**
1. Run `curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh`
2. Run `docker compose`, which will fail with an error that it is not a valid command.

**Describe the results you received:**
```sh
$ docker compose
docker: 'compose' is not a docker command.
See 'docker --help'
```

**Describe the results you expected:**
```sh
$ docker compose       

Usage:  docker compose [OPTIONS] COMMAND

Docker Compose
...
```

**Additional information you deem important (e.g. issue happens only occasionally):**

The [release that gets pulled by the script](https://github.com/docker/compose-cli/releases/tag/v1.0.17) seems to have a prescient note:

> * removed Compose v2 build from Compose-CLI release

**Output of `docker version`:**

```
$ docker version
Client: Docker Engine - Community
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.15
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:47 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by ndeloof** [comment]
install script installs the compose-cli ("Cloud Integrations")
compose.v2 is a CLI plugin, just download adequate binary into your $HOME/.docker/cli-plugins directory

**Comment by johnwchadwick** [comment]
> install script installs the compose-cli ("Cloud Integrations")
> compose.v2 is a CLI plugin, just download adequate binary into your $HOME/.docker/cli-plugins directory

I see. Then I suppose this is purely a documentation issue.

**Comment by ndeloof** [comment]
see https://github.com/docker/compose-cli#compose-v2-aka-local-docker-compose

compose.v2 will soon be extracted from this repo and moved to a new home to avoid such ambiguity

**Comment by snh** [comment]
I just experienced this myself as it seems the documentation at `docs.docker.com` is still incorrect.

Specifically https://docs.docker.com/compose/cli-command/#install-on-linux on the _Compose V2 beta_ page, which still indicates to use `scripts/install/install_linux.sh`.

**Comment by ndeloof** [comment]
@snh this indeed is outdated, will fix asap
