### ISSUE TITLE
Add `docker-compose disable-v2` and `docker-compose enable-v2` to help

### ISSUE THREAD

**Issue by rfay** [docker/compose-cli#1885]
**Description**

The `docker-compose disable-v2` and `docker-compose enable-v2` commands are partially documented in [compose cli docs](https://docs.docker.com/compose/cli-command/) but they are not in the docker compose help or the docker-compose help. 

**Steps to reproduce the issue:**

`docker-compose help` - There is no sign of disable-v2 or enable-v2

**Describe the results you expected:**

The most important command in there right now... is not in the help. 

**Additional information you deem important (e.g. issue happens only occasionally):**

The [compose cli docs](https://docs.docker.com/compose/cli-command/) should be updated to add enable-v2.

The docs might annoy people less if you remove the (currently) misleading phrase "so that users can seamlessly move to Docker Compose V2 without the need to upgrade any of their scripts". That seems a little optimistic for this stage of things.

**Output of `docker-compose --version`: ***
```
Docker Compose version 2.0.0-beta.4
```

**Comment by gitvadim** [comment]
Thank you a ton for creating this issue. I was surprised to find v2 being the default since the last update and it completely broke my setup. I wonder, whose idea it was to set a tool as default that is not production ready 💢 and not to mention in the docs how to get rid of it.

**Comment by terev** [comment]
:+1: this just broke our development setup too

**Comment by ndeloof** [comment]
enable-v2/disable-v2 are hidden command only available during the canary testing phase, we don't want to expose them to users as regular commands, as they will be dropped as soon as we release 2.0 G.A

**Comment by rfay** [comment]
I encourage you to reconsider this strategy.

compose v2 is not even available in packaged form on Linux, where it's really important. And there will always be incompatibilities/differences in behavior. So for people to add support for v2, they'll have to be able to switch back and forth.

For example, the next time I'm convinced to give docker-compose v2 a shot with ddev, I'll need to be able to run it through the entire set of automated tests, and the way I was planning to do that was to have the test setup switch to v2. But I don't plan to have a compose v2 dedicated set of test runners. 

Despite the best hopes, the transition to v2 is going to be a long one, and those of us who maintain tools/wrappers are going to be stretched between v1 and v2 for a long time.  But just getting to where we can support v2 in the first place is in immediate goal.

**Comment by kid1412621** [comment]
I installed Linux version v2 cli, just cannot find how to enable it.
