### ISSUE TITLE
--log-level with docker-compose always fails

### ISSUE THREAD

**Issue by cachedout** [docker/compose-cli#1891]
**Description**

Somewhat recently, it appears as if support for `--log-level` for docker-compose [was added ](https://github.com/docker/compose-cli/pull/1226) by @gtardif . However, any attempt to use this flag seems to fail with the message `Unable to parse logging level: compose`.

**Steps to reproduce the issue:**
1. Install Docker Compose version 2.0.0-beta.4 (I am on OS X 11.4)
2. Run `docker-compose  --log-level WARNING  ps`
3. Observe that the following error is returned: `Unable to parse logging level: compose`
4. Change the call to remove the `--log-level` flag and re-run it: `docker-compose    ps`
5. Note that the command runs without any errors.

**Describe the results you received:**
Results described above in reproduction steps

**Describe the results you expected:**
Expected results described above in reproduction steps

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker-compose --version`: ***
```
❯ docker-compose --version
Docker Compose version 2.0.0-beta.4
```
**Output of `docker version`:**
```
❯ docker --version
Docker version 20.10.7, build f0df350
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
❯ docker context show
desktop-linux
```

**Output of `docker info`:**

```
❯ docker info
Client:
 Context:    desktop-linux
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.4)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 34
  Running: 0
  Paused: 0
  Stopped: 34
 Images: 71
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 23.49GiB
 Name: docker-desktop
 ID: HR3I:D7HZ:X65A:C7GT:O2XZ:YYNR:RVFM:IVXC:O3MV:BKL5:J354:HYT7
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

macOS Big Sur 11.4

**Comment by cachedout** [comment]
For others who might come across this issue, I discovered that it can be worked around by unchecking the box for `Use Docker Compose v2` under `Experimental Features`.


<img width="774" alt="Screen Shot 2021-07-05 at 11 49 19 AM" src="https://user-images.githubusercontent.com/111616/124452817-4812c080-dd76-11eb-83b1-2223ba7a92cd.png">

**Comment by ndeloof** [comment]
`--log-level` added on https://github.com/docker/compose-cli/pull/1226 was for the compose CLI, i.e `docker compose ...̀  commands. If you still use `docker-compose` and Docker Desktop wrapper to redirect this command to compose v2, it obviously only support the legacy `docker-compose` flags.

Also, settings logs level on a docker CLI subcommand should be `docker --log-level=XX subcommand`, so I'm not sure this is desirable we keep this flag on compose-cli

**Comment by ndeloof** [comment]
Closing this issue as "won't fix": `--log-level` introduced on https://github.com/docker/compose-cli/pull/1226 applies to the top-level compose-cli command (the one ran as `docker` when installed), passing `--log-level` to `docker-compose` doesn't make any sense as this flag doesn't exists in the original (python) compose implementation, and is implemented on compose.v2 as a docker CLI flag
