### ISSUE TITLE
Add compose-cli plugin to docker Linux repositories

### ISSUE THREAD

**Issue by rfay** [docker/compose-cli#1911]
**Description**

I note that the compose plugin/subcommand for docker does not seem to ship in the official linux repositories, even as "docker compose". 

If compose cli is to be accepted and tested... it's going to have to be available easily on Linux, without an [awkward manual install technique](https://github.com/docker/compose-cli/blob/main/INSTALL.md#ubuntu-linux-installation)

Even though this is being pushed to unwitting canaries on Windows and macOS it's not even available in an expected way on Linux. At least as far as I can tell.

And, of course... there needs to be a way to enable the newfangled docker-compose v2 wrapper also on Linux.

**Comment by thaJeztah** [comment]
related; https://github.com/docker/docker-ce-packaging/pull/553

**Comment by ndeloof** [comment]
closing as a duplicate for  docker/docker-ce-packaging#553
