### ISSUE TITLE
Extend exec command to support specific instance name

### ISSUE THREAD

**Issue by mikesir87** [docker/compose-cli#1920]
**Description**

I've been thinking about the `docker compose exec` command, especially in the context of the additional backends. As an example, if I'm using the kube backend and do a ps, I might get output like the following:

```shell
docker compose -p votingapp ps
NAME                      COMMAND             SERVICE             STATUS              PORTS
db-677f6fd579-7nhsj       ""                  db                  Running             
redis-6c7f9657c-jbdkk     ""                  redis               Running             
result-66b4856489-4pqz7   ""                  result              Running             
vote-65d4d9594f-4tmfb     ""                  vote                Running             
vote-65d4d9594f-m7jwm     ""                  vote                Running             
worker-7497c578cb-9p498   ""                  worker              Running             
worker-7497c578cb-h9rxl   ""                  worker              Running  
```

Now, if I saw in logs that I'm having issues with a specific replica (let's pretend `vote-*-m7jwm`), how do I exec into that specific instance? Since the k8s deployments are managing the replicas, the normal `--index` parameter 1) doesn't make sense and 2) doesn't look like it's currently supported in the backend.

Looking at this from a user's perspective, I'd expect I could take one of the names listed here and use that as an argument for `docker compose exec`. For example... `docker compose -p votingapp exec vote-65d4d9594f-m7jwm`.

So... my proposal/request is if the `SERVICE` option in `docker compose exec` could be extended to support a specific instance name. If not found, it falls back to treating it as a service name (as it currently does). I'd be happy to submit a PR for the kube backend, but recognize the other backends could probably use this feature too. But, before I do anything, I figured I'd start a conversation first. Thoughts?

**Comment by ndeloof** [comment]
Once you have container name, you can just use plain `docker exec <container>` and don't need a compose command.

**Comment by mikesir87** [comment]
@ndeloof That works when using a local compose setup, but doesn’t work in the context of the other backends, such as kube (where Docker might not even be available at all). The names that show up in the `docker compose ps` output are the pod names, so yes… I could switch and run `kubectl exec <pod-name>`, but I’m trying to allow teams to stay within the compose tooling.

**Comment by ndeloof** [comment]
sure, but compose-cli is not just about compose, and `docker exec` (and other verbs) could be implemented as well by the Kube backend. cc @aiordache

**Comment by mikesir87** [comment]
Oh I see what you mean now... using the full context beyond just the Compose commands. I'll admit it's a little confusing at times that these additional backends/contexts are coming through this repo, which is focused on Compose, but end up affecting all of the other commands on the engine. It makes sense, but I keep mentally falling back to it being compose first.

Despite that... I wonder if it would be easy enough for the compose exec command to support a specific ID and fallback to service. It would just help satisfy the principle of least astonishment, as I got an ID from `compose ps` and then tried to use `compose exec` to find it didn't work. It just feels like something that _should_ work. I guess if the main `docker exec` gets implemented, it can be done so in a way in which that code could be shared to try a normal exec first and fallback pretty easily.
