### ISSUE TITLE
BUG REPORT: bash history (arrow keys) does not work correctly only docker compose v2.

### ISSUE THREAD

**Issue by y-okamoto-1113** [docker/compose-cli#1929]
# Description
bash history (arrow keys) does not work correctly.
**This Happens Only V2.**
V1 is Working Correctly.

# Steps to reproduce the issue:
1. docker compose run --rm app bash
2. pwd
3. pressing arrow keys `up`（↑）
4. bash shows `^[[A`, not `pwd`

`app` service uses image `ruby:2.4.1-alpine`.

# Describe the results you received:
when I pressed arrow kyes `up`（↑） after executed `pwd`, I saw `^[[A` (instead of `pwd`)

# Describe the results you expected:
I expect bash shows `pwd`

# Additional information you deem important (e.g. issue happens only occasionally):
This bug happens only v2.

bash history (arrow keys) on v1 does work corrently!
1. docker-compose disable-v2
2. docker-compose run --rm app bash
3. pwd
4. pressing arrow keys `up`（↑）

bash showed `pwd` as expected.

and docker, not docker compose, is working correctly.
1. docker run -it ruby:2.4.1-alpine
2. pwd
3. pressing arrow kyes `up`（↑）

bash showed `pwd` as expected.

# Output of `docker-compose --version`: 
```
Docker Compose version v2.0.0-beta.6
```

# Output of `docker version`:
```
Docker version 20.10.7, build f0df350

```

# Output of `docker context show`:
```
default
```

**Comment by ndeloof** [comment]
This is actually a duplicate for https://github.com/docker/compose-cli/issues/1908

**Comment by y-okamoto-1113** [comment]
@ndeloof 
thanks.
I'm looking forward to being fixed.
