### ISSUE TITLE
Docker CLI now warns about undefined variables with no documented way to turn this off

### ISSUE THREAD

**Issue by unikitty37** [docker/compose-cli#1938]
Docker has started warning about unset variables, where previously it *silently* set them to the empty string.

This output is useful in some cases, but is unnecessarily verbose, especially when the `environment` section contains variables that are set only in CI, such as `GITLAB_CI`; a warning is generated for *each* of these variables saying that the variable is not set. On one project, the CI variables cause 22 warnings to be generated every time the containers are spun up — and the variables are *supposed* to not be set in the local environment!

There is nothing in the release notes about this change, nor how to disable it.

  - [X] I have tried with the latest version of Docker Desktop
  - [X] I have tried disabling enabled experimental features
  - [X] I have uploaded Diagnostics
  - Diagnostics ID: C388E358-CA90-4EB9-8910-EF4159D5FFFD/20210721131702
  
### Expected behaviour

The command does not output warnings about undefined variables, as before.

The change is documented at https://docs.docker.com/docker-for-mac/release-notes/, with a link to the documentation page that contains instructions on how to disable this behaviour.

### Actual behaviour

The command outputs the following:

```
WARN[0000] The GITLAB_CI variable is not set. Defaulting to a blank string.
[+] Running 2/2
 ⠿ Network docker-compose-issue_default        Created                                                                                                      0.5s
 ⠿ Container docker-compose-issue_container_1  Started                                                                                                      1.2s
```

There is no mention in the release notes of why this is now happening, and no clues on where to find instructions on how to disable it.

### Information

  - macOS Version: macOS 10.14.6 (18G9216)
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.5.2 (66501)

This behaviour started after upgrading to version 3.5.2 (66501).
### Steps to reproduce the behaviour

Using the following `docker-compose.yml`:

```yaml
version: '3.8'

services:
  container:
    image: ruby:3.0.1-alpine
    environment:
      - GITLAB_CI
```

  1. Upgrade to Docker for Mac 3.5.2
  1. Type `docker compose up -d`

**Comment by Ocramius** [comment]
Just to add here: this is also true for when the variables have **explicit** default/fallback substitution, like:

```yml
services
  my-service:
    image: ghcr.io/my/repo:${GIVEN_TAG:-dev}
```

No matter what you do, `compose-cli` will complain about `GIVEN_TAG` not being specified in the current `env`

**Comment by ndeloof** [comment]
proposed fix: https://github.com/compose-spec/compose-go/pull/159

**Comment by abdounikarim** [comment]
You can disable Docker Compose V2 usage and you'll get again your docker compose working 😉
![image](https://user-images.githubusercontent.com/15892761/126767645-95b1f91c-d5db-4428-b3dc-d2fd1adbc258.png)

**Comment by beyondmeat** [comment]
I also discovered that commented out sections in a yml that contain env variables get parsed and expected in RC1. This seems to be a bug introduced by the recent env changes.

for example:
```   
# traefik.http.routers.dashboard.rule: Host(`${TRAEFIK_CNAME}.localhost`, `${TRAEFIK_CNAME}.local.${DOMAIN}`) 
``

1. docker-compose.yml
2.  have valid yml that uses a env variable
3. comment out the line in the yml, (line starting with #)
4. run docker compose pull to see variable is not set. Defaulting to a blank string warning.

**Comment by ndeloof** [comment]
issue has been fixed on compose-go
