### ISSUE TITLE
The dark blue color for building/pulling images and starting/stopping containers makes the text difficult to read

### ISSUE THREAD

**Issue by ericparton** [docker/compose-cli#1947]
The log text for building images, pulling images, starting containers, and stopping containers is always dark blue. This is often difficult to read on top of the traditional black terminal background. There is the no color option, which doesn't currently work due to another issue, but the color here would actually be a good thing if it was easier to read.

**Steps to reproduce the issue:**
1. Run docker compose up
2. Observe the log when images are built or pullled and when containers are started and stopped

**Describe the results you received:**

![Screen Shot 2021-07-23 at 1 42 13 PM](https://user-images.githubusercontent.com/13722178/126820850-494bd205-df48-4db4-9df8-3139f954165b.png)

**Describe the results you expected:**

Instead of dark blue, a lighter color should be used for these log messages. Docker compose has traditionally used lighter colors for its log messages, and I think that has worked well for a long time.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker-compose --version`: ***
```
Docker Compose version 2.0.0-beta.4
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:50 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.8
  GitCommit:        7eba5930496d9bbe375fdf71603e610ad737d2b2
 runc:
  Version:          1.0.0
  GitCommit:        v1.0.0-0-g84113ee
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., 2.0.0-beta.4)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 12
  Running: 8
  Paused: 0
  Stopped: 4
 Images: 71
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 7eba5930496d9bbe375fdf71603e610ad737d2b2
 runc version: v1.0.0-0-g84113ee
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
 Kernel Version: 5.4.0-80-generic
 Operating System: Ubuntu 20.04.2 LTS
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 31.05GiB
 Name: zaofu
 ID: YPJL:Z5RA:JNJU:4KIH:SKVP:SZMW:DDMA:AYT2:UW3N:QW36:WIN2:ACN2
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Registry Mirrors:
  https://docker-reg.arin.net/
 Live Restore Enabled: false

WARNING: No swap limit support
```

**Comment by ndeloof** [comment]
This is actually a buildx/buidkit issue

**Comment by ericparton** [comment]
does that mean that I need to file the issue somewhere else?

**Comment by ndeloof** [comment]
see https://github.com/docker/buildx/issues/596 and https://github.com/docker/buildx/issues/560

**Comment by bast1aan** [comment]
As of now, in docker compose 2.15.1, this is still an issue. At least, the methods mentioned in buildkit do not work:
```
NO_COLOR=1 docker compose
docker compose --progress=plain 
BUILDKIT_PROGRESS=plain docker compose
BUILDKIT_TERM_COLOR="light-blue" docker compose 
BUILDKIT_COLORS="run=light-blue:error=light-red:cancel=light-cyan:warning=light-red" docker compose

```
all still return dark blue colors that are unreadable on dark terminals (or gives an error). OS: Ubuntu 20.04.

**Comment by ndeloof** [comment]
@bast1aan you can use `docker compose build --progress plain` to force non-colored output
I expected support for BUILDKIT_COLORS to come "for free" as we update buildx dependency, but actually need to adjust compose code accordingly. I'm re-opening this issue

**Comment by bast1aan** [comment]
@ndeloof that does not work either for at least the `up` command.
```
$ docker compose up --progress plain
unknown flag: --progress
$ docker compose version
Docker Compose version v2.15.1
```

**Comment by littlematch0123** [comment]
I have the same issue.
![Screenshot 2023-02-18 at 15 34 50](https://user-images.githubusercontent.com/13502705/219848024-b0b7b65e-a0b3-4f9f-974e-9ab60e33b660.png)

**Comment by drifter75** [comment]
this is still an issue.

```
# docker compose up --progress plain
unknown flag: --progress

# docker compose version
Docker Compose version v2.16.0
```

**Comment by jma7889** [comment]
I have the same issue, the dark blue is in compose up, start, stop, restart, it is everywhere. I use zsh on mac docker desktop. Is there any workaround, would bash be better? It is annoying.

**Comment by vananiev** [comment]
I have the same issue with 2.16.0, hope, it will be fixed soon.

**Comment by r7l** [comment]
In case you only want to have plain output without any colors, you can simply use `docker compose --ansi=never ...`. Doesn't look nice but it works.

**Comment by vananiev** [comment]
It works, many thanks. I add to `.bashrc`
```shell
alias dc="docker compose --ansi=never"
```

**Comment by pparedes1** [comment]
Another option is to change the ANSI color of blue on your terminal to make the blue more legible. For example, if you are using PUTTY, you can click on Colours under the Window setting and change the ANSI Blue color to something less dark. Be sure to open a new session to see the colors applied (and save the profile if you want to use again). 

I use 39, 172, 252 and it provides a more pleasant color of blue for docker compose. 
![image](https://github.com/docker/compose-cli/assets/15050795/cb789fce-41dd-4bce-8179-40f6b6ec8605)

**Comment by aerique** [comment]
Setting colors works for me now: https://github.com/moby/buildkit/tree/master#configuring-buildctl
