### ISSUE TITLE
Deploying to AWS ECS with replicas: 0 end up in 1 task being run anyway

### ISSUE THREAD

**Issue by ROunofF** [docker/compose-cli#1948]
**When using a context deploying to AWS ECS and you set the services: deploy: replicas: 0, the services use the default value of DesiredCount: 1 since it's not defined in the CloudFormation template**

**Steps to reproduce the issue:**
1. docker context create ecs ecs (setup Access Key + Secret key for example)
2. docker context use ecs
2. docker compose up with the following docker-compose.yaml
```
  services:
  nginx1:
    image: nginx:alpine
    deploy:
      replicas: 0
```

**Describe the results you received:**
There is 1 instance of the services running.

**Describe the results you expected:** The service is configured in ECS but with DesiredTask : 0 so that no instance of the task is started.

**Additional information you deem important (e.g. issue happens only occasionally):**
I was able to pinpoint the problem that the generated CloudFormation template doesn't have DesiredCount defined when replicas: 0. When it's not specified, the default value is 1, hence the bug. I did a manual template with DesiredCount and the expected outcome is achieved, so it looks like it's a "conversion" error.

**Output of `docker-compose --version`: ***
```
docker-compose version 1.29.2, build 5becea4c
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           ecs
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
ecs
```

**Output of `docker info`:**

```
N/A
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):** AWS ECS

**Comment by thaJeztah** [comment]
wondering if it doesn't distinguish between an explicit `0` being set, and the value "not being set" (default for an integer is also `0`) 🤔

**Comment by ndeloof** [comment]
if your goal is to make some service optional for deployment, better use profiles in your compose file

**Comment by janrito** [comment]
This is still unaddressed

**Comment by JohnPreston** [comment]
Hello. I had the exact same issue in the past, my only workaround was to make sure I had replicas: 1 and an autoscaling rule that brought it down to 0.
I just thought of something to try, will try in compose-x, will report later.
