### ISSUE TITLE
3.5.2 seems to break some keyboard functions in centos7 container

### ISSUE THREAD

**Issue by davexre** [docker/compose-cli#1951]
- [ X] I have tried with the latest version of Docker Desktop
  - [ X] I have tried disabling enabled experimental features
  - [ ] I have uploaded Diagnostics
  - Diagnostics ID:

### Expected behavior
Ctrl-D at the command prompt in a centos7 container exits the container. Using arrow keys in bash traverses command history.

### Actual behavior
Ctrl-D displays a new line, and then hangs - xterm window must be closed manually, and never returns to shell prompt on the Mac. Arrow keys just display escape sequences (^[[A, ^[[B, etc).

### Information

  - macOS Version: Big Sur, 11.4
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: 3.5.2
  - Problem initially encountered immediately after upgrade to 3.5.2, and appears to be consistently repeatable on my system. Downgrade to 3.4.0 resolves the problem completely.

### Steps to reproduce the behavior

  1. Use docker-compose to start a centos7 image
  2. Run a couple of commands to get a command history. Doesn't matter which commands.
  3. Use the up arrow key to try to navigate back through the command history
  4. Ctrl-D to exit the container

**Comment by ndeloof** [comment]
This has been fixed by https://github.com/docker/compose-cli/pull/1934

**Comment by kaki404** [comment]
Updated last night to 3.5.2(66501)
Engine: 20.10.7
Compose: v2.0.0-beta.6

any news about when [#1934](https://github.com/docker/compose-cli/pull/1934) will be included in a release?

**Comment by lorenrh** [comment]
Hello @kaki404 #1934 should be in Compose v2.0.0-rc.1, that's included in the Docker Desktop 3.6.0, which we released a couple of days ago.

https://docs.docker.com/docker-for-mac/release-notes/
https://docs.docker.com/docker-for-windows/release-notes/
