### ISSUE TITLE
`docker compose run` brings down the cluster after one-off container finishes execution.

### ISSUE THREAD

**Issue by vintlucky777** [docker/compose-cli#1955]
**Description**

**Steps to reproduce the issue:**
1. Bring up local cluster with `docker-compose up --abort-on-container-exit`
2. Run a one-off job with `docker-compose run`, e.g. for a Django setup `docker-compose run --rm web python ./manage.py migrate`

**Describe the results you received:**

Docker compose now detects a new container join the cluster. After one-off completes execution it terminates, which causes docker compose to bring down the whole thing.

**Describe the results you expected:**

Expected the `docker compose up` cluster to keep running, and one-off container to not interfere with it via log output or exit code.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker-compose --version`:**
```
$ docker-compose --version
Docker Compose version v2.0.0-beta.6
```

**Output of `docker version`:**

```
$ docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
$ docker context show
default
```

**Output of `docker info`:**

```
$ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 5
  Running: 5
  Paused: 0
  Stopped: 0
 Images: 96
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 7.776GiB
 Name: docker-desktop
 ID: PB2F:CWXS:DOQR:WP35:2EVK:DBRT:AFDW:JQ3X:XJ2R:7NG3:LYWX:BWFK
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 95
  Goroutines: 121
  System Time: 2021-07-26T21:56:35.399582Z
  EventsListeners: 6
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by vintlucky777** [comment]
@ndeloof any timeline on when this would be addressed? Or maybe you could provide a couple hints on where to start looking at in the code to put together a patch?

**Comment by mat007** [comment]
Does it do the same if you run it detached (with `-d`)?

**Comment by vintlucky777** [comment]
it does not.
but when executed in detached mode, also none of the containers stop if another one dies, e.g. if a dependency container terminates (DB), consumers of that container won't get killed (Django app). we rely on docker-compose ability to spin up dependencies along with consumers, and to cascade-kill the whole thing if one of the services stops.
flags `-d` and `--abort-on-container-exit` are incompatible.

**Comment by mat007** [comment]
I meant the second invocation with `docker compose run -d …`. 😁

**Comment by vintlucky777** [comment]
thank you @ndeloof ! :tada:
