### ISSUE TITLE
If profiles are used, `docker-compose config --services` only lists services with no profile

### ISSUE THREAD

**Issue by bwateratmsft** [docker/compose-cli#1964]
**Description**
Using `docker-compose config --services` allows for the services in a compose document to be listed, one per line. However, if Compose Profiles are being used, this only emits services that have no profiles. IMO it should emit all services.

**Steps to reproduce the issue:**
1. Create a compose document with a few services
2. Run command `docker-compose config --services`, note that all services are emitted
3. Add profiles to some (but not all) of the services
4. Run `docker-compose config --services` again

**Describe the results you received:**
Only services that do not have any profiles are listed

**Describe the results you expected:**
All services are listed

**Output of `docker-compose --version`:**
```
PS D:\Sandbox\DebugTimeout\bin\Debug\net5.0> docker-compose version
Docker Compose version v2.0.0-beta.6
```

**Output of `docker version`:**

Docker Desktop 3.5.2 on Win10

```
PS D:\Sandbox\DebugTimeout\bin\Debug\net5.0> docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 12:00:56 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker info`:**

```
PS D:\Sandbox\DebugTimeout\bin\Debug\net5.0> docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 5
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.16.3-microsoft-standard-WSL2
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 24.99GiB
 Name: docker-desktop
 ID: EDOU:D523:AA3Z:S6DT:FEUA:RMQN:EA75:22IT:CN76:7OHD:3EK3:SUQA
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: No blkio throttle.read_bps_device support
WARNING: No blkio throttle.write_bps_device support
WARNING: No blkio throttle.read_iops_device support
WARNING: No blkio throttle.write_iops_device support
```

**Comment by ndeloof** [comment]
`--profiles` is applied before any other action, as a way to tweak the compose model. So the `config ----services` command to only list the active ones.

I agree this would make sense for this command to add an `ACTIVE` column and list all services, including the disabled ones.

**Comment by bwateratmsft** [comment]
That'd complicate our parsing logic (a little), but the cross-compatibility would be more of a challenge with that. Could it take an option like `docker-compose --profile all config --services`? Probably need some keyword other than "all" though, as that's likely to be a real profile name.

**Comment by ndeloof** [comment]
If you consume this from another tool, better use `--format json` so you don't depent on console-formatted output

**Comment by ravipal** [comment]
The earlier version (docker-compose version 1.29.2, build 5becea4c) of compose behavior is to list all services irrespective of active profile. So this seems like a regression and breaks the existing tools that depends on this behavior.

**Comment by bwateratmsft** [comment]
It might be a disparity between new and old compose, in that case.

**Comment by bwateratmsft** [comment]
> If you consume this from another tool, better use `--format json` so you don't depent on console-formatted output

@ndeloof turns out `--format json` and `--format="{{ json . }}"` do not work :(
```
PS D:\Sandbox\ComposeProfiles> docker-compose config --services --format="{{ json . }}"
bar
composeprofiles
dep
backend
PS D:\Sandbox\ComposeProfiles> docker-compose config --services --format json
composeprofiles
dep
backend
bar
```

According to @ravipal the same is true for the old compose CLI.

**Comment by ndeloof** [comment]
I was suggesting `--format` as a long term option to process compose commands output, but we first need to get it implemented on this specific one :P

**Comment by karolz-ms** [comment]
@ndeloof so where does this fall on your backlog, approximately? We rely on `config --services` listing all services quite heavily in Visual Studio tooling

@ravipal @nebuk89 FYI

**Comment by ndeloof** [comment]
A full fix for `config --services` to support profiles can be considered, but in the meantime I've proposed a workaround as https://github.com/compose-spec/compose-go/pull/175

**Comment by karolz-ms** [comment]
@ndeloof thanks for quick reply, much appreciated. The proposed workaround should unblock us.
