### ISSUE TITLE
ctrl + c doesn't send SIGTERM to docker container when container is started using docker-compose run

### ISSUE THREAD

**Issue by aniketbhatnagar** [docker/compose-cli#1966]
I recently upgraded to Docker Desktop 3.5.2 (66501) and  ctrl + c no longer sends SIGTERM signal to docker container started using docker-compose run. It works when using docker-compose up OR docker run.

  - [x] I have tried with the latest version of Docker Desktop
  - [ ] I have tried disabling enabled experimental features
  - [x] I have uploaded Diagnostics
  - Diagnostics ID: 6C4BE89A-68AC-4380-ACC9-F12C630E7528/20210729163825

### Expected behavior
ctrl + c should send SIGTERM to docker container

### Actual behavior
No signal is sent

### Information

  - macOS Version:  BigSur 11.5.1
  - Intel chip or Apple chip: Intel
  - Docker Desktop Version: Docker Desktop 3.5.2 (66501)

### Steps to reproduce the behavior
Steps along with sample docker-compose @ https://github.com/aniketbhatnagar/docker-compose-bug. Also recorded video @ https://github.com/aniketbhatnagar/docker-compose-bug/blob/main/docker-compose-bug.mp4

**Comment by ndeloof** [comment]
I guess this has been fixed by https://github.com/docker/compose-cli/pull/1934.

**Comment by aniketbhatnagar** [comment]
Great! thank you both!
