### ISSUE TITLE
pg-restore omits data

### ISSUE THREAD

**Issue by erwittry** [docker/compose-cli#1970]
**Description**

This appears to be a problem with CLI parameter passing.  When passing `pg_restore` to our DB, it restores the schema only without the data.  This looks like its inferring an '-a' flag thats not actually there.  Downgrading to docker 3.4.0 from 3.5.2 fixed this as a work around.  This was a long standing script which stopped working after an upgrade.

**Steps to reproduce the issue:**
1. docker-compose exec -T db pg_restore --no-acl --no-owner -U user -d db_name < dumpfile

**Describe the results you received:**
Essentially, this command silently failed to load data.

**Describe the results you expected:**
A fully populated database w/ data.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker-compose --version`: ***
```
Docker Compose version v2.0.0-beta.6
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true
Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
(paste your output here) 
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by ndeloof** [comment]
Seems to be related to https://github.com/docker/compose-cli/issues/1962

Copuld you please confirm by trying the same command, but using `docker compose` (space, no dash)?

**Comment by erwittry** [comment]
Late reply.  Can confirm `docker-compose `and `docker compose` yield the same behavior
