### ISSUE TITLE
How to use Docker compose create context ecs in travis.yml CI/CD

### ISSUE THREAD

**Issue by ardumez** [docker/compose-cli#1977]
I want use docker compose context ecs in travis.yml, it is secure to put .dockercontext file into public repository ? 
How to init docker compose context without interactive mode:

![image](https://user-images.githubusercontent.com/9568904/127752385-cc377cb7-8d87-4bbf-9a26-cdda34478a11.png)

 or without import .dockercontext ?
In CI/CD context.

I start expect scripts

```
#!/usr/bin/expect -f
set timeout 360
spawn  docker context create ecs test
expect "AWS environment variables"
send "\033\[B"
send "\033\[B"
interact
```

Thanks

**Comment by ndeloof** [comment]
check  `docker context create ecs --help` for command line flags you can use to setup context non-interactively

**Comment by ardumez** [comment]
Ok, I try with these settings, thanks for your response.
