### ISSUE TITLE
Compose CLI commands not available on Manjaro Linux

### ISSUE THREAD

**Issue by SalahAdDin** [docker/compose-cli#1982]
**Description**
We wanted to test the **compose cli** for both _V1_ and _V2_ in our new **Manjaro Linux** setup. We installed **Docker** and **Docker Compose CLI** without any problem, but at moment to use the `compose` command, we can find it.

**Steps to reproduce the issue:**
1. Install **Docker** following the documentation.
2. Install the **CLI** with the script as documentation says:  `curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh`.
3. Check the `compose` command and the `docker-compose` command.
4. You won't find anything.

**Describe the results you received:**
Neither `docker compose` nor `docker-compose` commands are available.

**Describe the results you expected:**
As the documentation says, we should see both commands.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker-compose --version`: ***
```
(paste your output here)
```

**Output of `docker version`:**

```
docker version
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df35096d
 Built:             Fri Jun  4 08:14:39 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server:
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.4
  Git commit:       b0f5bc36fe
  Built:            Fri Jun  4 08:14:24 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.5.4
  GitCommit:        69107e47a62e1d690afa2b9b1d43f8ece3ff4483.m
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b638
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
❯ docker context show
default
```

**Output of `docker info`:**

```
❯ docker info
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  app: Docker App (Docker Inc., v0.9.1-beta3)
  buildx: Build with BuildKit (Docker Inc., v0.5.1-tp-docker)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 0
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: false
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: systemd
 Cgroup Version: 2
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 69107e47a62e1d690afa2b9b1d43f8ece3ff4483.m
 runc version: v1.0.1-0-g4144b638
 init version: de40ad0
 Security Options:
  apparmor
  seccomp
   Profile: default
  cgroupns
 Kernel Version: 5.10.53-1-MANJARO
 Operating System: Manjaro Linux
 OSType: linux
 Architecture: x86_64
 CPUs: 8
 Total Memory: 31.06GiB
 Name: luis-nirvananbx400
 ID: 3JRP:U7XC:ABW7:U4VI:EHH2:VHXG:HFSS:MHXQ:5TQI:WCPG:ECUE:WKIR
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by ndeloof** [comment]
`install_linux` script installs the "cloud integration CLI"
To get compose.v2, just download adequate binary from this repo into your $HOME/.docker/cli-plugins folder.

see https://github.com/docker/compose-cli#compose-v2-aka-local-docker-compose
