### ISSUE TITLE
Docker-compose "V2 beta" exec into service produces shell with no arrow navigation and no tab-completion on macOS 11 Big Sur

### ISSUE THREAD

**Issue by rabihkodeih** [docker/compose-cli#1984]
**Description**

 Whenever I run `docker-compose run <service_name> exec /bin/bash` it produces shell where there is no arrow navigation and no tab-completion. When I press the four arrow keys I get something like `^[[A, ^[[B, ^[[C, ^[[D`. When I press tab I simply get tab printed on the shell instead of getting usual command completion. All env-vars seem to be in order, `echo $SHELL` gives `/bin/bash` and `echo $TERM` gives `xterm`. 

**Steps to reproduce the issue:**
1. Prepare any reasonably standard docker-compose services configuration with an entry-point that accepts exec command.
2. Type `docker-compose run <service_name> exec /bin/bash`
3. Expect bash shell prompt to open.

**Describe the results you received:**
Shell opens with no arrow navigation (pressing arrows gives `^[[A, ^[[B, ^[[C, ^[[D` and there is no command tab-completion).

**Describe the results you expected:**
Shell should opens with normal arrow navigation and usual command tab-completion.

**Additional information you deem important (e.g. issue happens only occasionally):**
Issue happens consistently only in docker-compose version "Docker Compose version v2.0.0-beta.6". Issue does not happen in version 1.

**Output of `docker-compose --version`:**
```
Docker Compose version v2.0.0-beta.6
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:22 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:54:58 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
[
    {
        "Name": "default",
        "Metadata": {
            "StackOrchestrator": "swarm"
        },
        "Endpoints": {
            "docker": {
                "Host": "unix:///var/run/docker.sock",
                "SkipTLSVerify": false
            }
        },
        "TLSMaterial": {},
        "Storage": {
            "MetadataPath": "\u003cIN MEMORY\u003e",
            "TLSPath": "\u003cIN MEMORY\u003e"
        }
    }
]

```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 9
  Running: 2
  Paused: 0
  Stopped: 7
 Images: 30
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 1.942GiB
 Name: docker-desktop
 ID: PBZ4:AZOV:TTQR:KDOH:TYVR:NE5F:TWHA:5ZJ4:F4B2:6266:R2VZ:7ZHH
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Local:
```
ProductName:	macOS
ProductVersion:	11.5.1
BuildVersion:	20G80
```

**Comment by kaki404** [comment]
Same problem here! A workaround to continue working is run the follow commands:

```
docker compose up
docker ps
docker exec -it projectname_app_1 /bin/bash
rails console
```

`docker ps` to find the name of your container, in my case: `projectname_app_1`
`rails console` in my case, I need `bash` to run the `rails console`

**Comment by ndeloof** [comment]
This indeed has been fixed by https://github.com/docker/compose-cli/pull/1934
closing as duplicate
