### ISSUE TITLE
Compose V2 'run' has different behaviour to V1

### ISSUE THREAD

**Issue by john-h-k** [docker/compose-cli#1986]
**Description**

`compose run` v2 behaves unexpectedly and inconsistently with `compose run` v1 for executing interactive shells.

**Steps to reproduce the issue:**

v1 command:
```sh
docker-compose run --rm web bash
```

v2 command:
```sh
docker compose run --rm web bash
```

Type a command in the resulting shell, and then try and navigate to history using up arrow, or try and move left/right with arrow keys, or attempt to use Ctrl-C to cancel the current command

**Describe the results you received:**

In V1, works as expected. In V2, escape codes are shown instead (e.g visiting history shows `[[A` instead of the last command and Ctrl-C does not work).

**Describe the results you expected:**

Same behaviour as V1

**Additional information you deem important (e.g. issue happens only occasionally):**

Functionally the keys still work, (hitting up and enter will exec last command), just incorrect display of it.
Shell being executed is definitely bash, not sh.

**Output of `docker-compose --version`: **x

```sh
# v1
docker-compose --version
> docker-compose version 1.29.2, build 5becea4c

# v2
docker compose version
> Docker Compose version v2.0.0-beta.6
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:23 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:55:36 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 14
  Running: 13
  Paused: 0
  Stopped: 1
 Images: 8
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 6
 Total Memory: 3.841GiB
 Name: docker-desktop
 ID: BK6Q:3XVV:6ZIC:VKHC:BGE6:FDWW:GWRL:6NR2:IWSK:W6UF:5JTE:5EIM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

Apple M1 silicon running Docker Desktop v2.

**Comment by thaJeztah** [comment]
I _think_ this was fixed on master/main through https://github.com/docker/compose-cli/pull/1934, but may not yet have been released.

**Comment by john-h-k** [comment]
Hmm, sorry if I've made a redundant issue - is there a beta/dogfooding build anywhere i can find which i could use to verify this?

**Comment by thaJeztah** [comment]
No beta/doogfooding releases, but I expect a new release to be shipping with a future Docker Desktop update, and I think the `BUILDING.md` describes how to build from source; https://github.com/docker/compose-cli/blob/main/BUILDING.md (haven't tried doing so myself recently)

**Comment by ndeloof** [comment]
This has indeed been fixed already by https://github.com/docker/compose-cli/pull/1934
