### ISSUE TITLE
Inappropriate binding to all interfaces when only localhost is specified ('ports')

### ISSUE THREAD

**Issue by rfay** [docker/compose-cli#1991]
**Description**

A docker-compose stanza like the `ports:` stanza below should result in binding only to localhost, not binding to all interfaces.
```yaml
services:
  junk:
    command:
    - tail
    - -f
    - /dev/null
    image: busybox
    ports:
    - mode: ingress
      host_ip: 127.0.0.1
      target: 8888
      published: 8888
      protocol: tcp
```

Instead, with that docker-compose as docker-compose.yaml (macOS) we see docker binding on all interfaces

```
$ lsof -PiTCP -sTCP:LISTEN |grep 8888
com.docke  2858 rfay   11u  IPv6 0x5d05b716bfdff219      0t0  TCP *:8888 (LISTEN)
```

Note that this problem does *not* happen on docker-compose v2 with this docker-compose.yaml:
```yaml
version: "3.6"
services:
  junk:
    image: busybox
    command: tail -f /dev/null
    ports:
      - 127.0.0.1:8888:8888
```

However the problematic yaml above is a result of `docker-compose config` of the more traditional docker-compose.yaml

So apparently it's the processing of the newer syntax that is a problem?

**Steps to reproduce the issue:**

* Save the above as `docker-compose.yaml`
* `docker-compose up` using docker-compose v2.0.0-beta.6
* use `lsof -PiTCP -sTCP:LISTEN |grep 8888` to see the binding.

**Describe the results you received:**

Binding on all ports

**Describe the results you expected:**

Binding on localhost only.

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker-compose --version`:**

Docker Compose version v2.0.0-beta.6

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.16.4
 Git commit:        f0df350
 Built:             Wed Jun  2 11:56:23 2021
 OS/Arch:           darwin/arm64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.7
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       b0f5bc3
  Built:            Wed Jun  2 11:55:36 2021
  OS/Arch:          linux/arm64
  Experimental:     false
 containerd:
  Version:          1.4.6
  GitCommit:        d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc:
  Version:          1.0.0-rc95
  GitCommit:        b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0```

**Output of `docker context show`:**  

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.5.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-beta.6)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 3
  Running: 1
  Paused: 0
  Stopped: 2
 Images: 151
 Server Version: 20.10.7
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: d71fcd7d8303cbf684402823e425e9dd2e99285d
 runc version: b9ee9c6314599f1b4a7f497e1f1f856fe433d3b7
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.25-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: aarch64
 CPUs: 4
 Total Memory: 5.8GiB
 Name: docker-desktop
 ID: 6ZOV:BBEF:2T2Q:TIYP:U4AF:UGTM:TXQZ:KQWW:RS6W:EM4X:V2YU:EZNF
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

This happens on macOS arm64 and macOS amd64, docker-desktop 2.5.3

**Comment by ndeloof** [comment]
nice catch, fixed by https://github.com/compose-spec/compose-go/commit/4f9b8a55a4ee0410b4aad560418a232249050671
