### ISSUE TITLE
Pull access denied for custom docker image after upgrading to Docker Desktop 3.6.0 with Docker Compose v2.0.0-rc.1

### ISSUE THREAD

**Issue by vitaly-krugl** [docker/compose-cli#2016]
---------------------------------------------------
BUG REPORT INFORMATION
---------------------------------------------------

**Description**

After upgrading to Docker Desktop 3.6.0 with Docker Compose version v2.0.0-rc.1 automatically enabled, I started getting the error "Error response from daemon: pull access denied for <my app docker image>, repository does not exist or may require 'docker login': denied: requested access to the resource is denied" when running
```
docker-compose -f ./compose.layer1.yml -f compose.layer2.yml pull
```

**Steps to reproduce the issue:**
1. I created a minimal set of files to reproduce this issue. Create the following files in the same directory:
Dockerfile
```
FROM python:3.8.3-slim-buster
```

compose.layer1.yml
```
version: '3.8'

services:
  dev:
    working_dir: /a/myapp

    build:
      context: ${PWD}
      dockerfile: ${PWD}/Dockerfile
```

compose.layer2.yml
```
services:
  dev:
    image: my_app
    container_name: my_app
```

compose.all-in-one.yml
```
version: '3.8'


services:
  dev:
    image: my_app
    container_name: my_app

    working_dir: /a/myapp

    build:
      context: ${PWD}
      dockerfile: ${PWD}/Dockerfile
```

2. Now, run either of these commands from the same directory that contains the above files:
```
docker-compose -f ./compose.layer1.yml -f compose.layer2.yml pull

[+] Running 0/1
 ⠿ dev Error                                                                                                                             2.8s
Error response from daemon: pull access denied for my_app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

```
docker-compose -f ./compose.all-in-one.yml pull
[+] Running 0/1
 ⠿ dev Error                                                                                                                             1.6s
Error response from daemon: pull access denied for my_app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied ```
```

**Describe the results you received:**
Getting these errors that were not happening prior to docker-compose v2:

```
docker-compose -f ./compose.layer1.yml -f compose.layer2.yml pull

[+] Running 0/1
 ⠿ dev Error                                                                                                                             2.8s
Error response from daemon: pull access denied for my_app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
```

```
docker-compose -f ./compose.all-in-one.yml pull
[+] Running 0/1
 ⠿ dev Error                                                                                                                             1.6s
Error response from daemon: pull access denied for my_app, repository does not exist or may require 'docker login': denied: requested access to the resource is denied ```
```

**Describe the results you expected:**
I expected a successful execution of pull

**Additional information you deem important (e.g. issue happens only occasionally):**

The issues goes away if I disable docker-compose v2 via `docker-compose disable-v2`

Also, with docker-compose v2, `build` and `build --pull` commands were working correctly. The problem was observed with just `pull` as described in steps to reproduce.

**Output of `docker-compose --version`:**

```
Docker Compose version v2.0.0-rc.1
```

**Output of `docker version`:**

```
Client:
 Cloud integration: 1.0.17
 Version:           20.10.8
 API version:       1.41
 Go version:        go1.16.6
 Git commit:        3967b7d
 Built:             Fri Jul 30 19:55:20 2021
 OS/Arch:           darwin/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Output of `docker context show`:**  

```
default
```

**Output of `docker info`:**

```
Client:
 Context:    default
 Debug Mode: false
 Plugins:
  buildx: Build with BuildKit (Docker Inc., v0.6.1-docker)
  compose: Docker Compose (Docker Inc., v2.0.0-rc.1)
  scan: Docker Scan (Docker Inc., v0.8.0)

Server:
 Containers: 1
  Running: 1
  Paused: 0
  Stopped: 0
 Images: 355
 Server Version: 20.10.8
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
  userxattr: false
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Cgroup Version: 1
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: e25210fe30a0a703442421b0f60afac609f950a3
 runc version: v1.0.1-0-g4144b63
 init version: de40ad0
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 5.10.47-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 4
 Total Memory: 1.939GiB
 Name: docker-desktop
 ID: EXXX:HMR7:557I:VBT6:IYHC:UXSL:IAWB:S5OS:Z5XD:2O4U:YI6H:PEI7
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 52
  Goroutines: 58
  System Time: 2021-08-13T22:43:53.0894996Z
  EventsListeners: 3
 HTTP Proxy: http.docker.internal:3128
 HTTPS Proxy: http.docker.internal:3128
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Running on MacBookPro  Catalina 10.15.7

**Comment by ulyssessouza** [comment]
Hello @vitaly-krugl . Thank you for the report.

What happens here is that the image you are trying to `pull` (named `myapp`) doesn't exist in "docker hub". Which is totally normal.
The difference with `compose v1` is that it will warn the user to run `docker compose build` instead.
I just proposed a [PR](https://github.com/docker/compose-cli/pull/2026) on that

**Comment by vitaly-krugl** [comment]
This proposal might not work cleanly. Docker-compose projects like mine
have multiple layers (yml files), and some of them refer to public images
either directly or via the underlying dockerfile's base image, so a
properly-functioning 'docker-compose pull' that pulls the public stuff is
important for consistency.

Note that it's often an automation script that invoked 'docker-compose
pull', and not necessarily an actual user at 5he terminal, so the script
won't be in position to observe your warning message and do build instead.

There are lots of automation scripts like that out in the field.

What's wrong with how 1.x did it? It seemed to work beautifully in this
case.
