### ISSUE TITLE
docker-compose vs docker compose   different behaviour    and config.json  proxies

### ISSUE THREAD

**Issue by bb980701** [docker/compose-cli#2032]
**Description**

docker-compose up was taking into account the default proxies setup in the config.json   as stated in doc : https://docs.docker.com/network/proxy/#set-the-environment-variables-manually

since Release 3.6.0 Docker desktop, docker-compose and docker compose refer to the same as version 
Docker Compose version v2.0.0-rc.1

**Steps to reproduce the issue:**
Set your /.docker/config.json with the
![image](https://user-images.githubusercontent.com/71716559/130103249-5017ff42-28aa-44e6-bd81-f12adf58aa8a.png)

Create the files :
![image](https://user-images.githubusercontent.com/71716559/130103317-58c60c04-3d47-41b2-bef9-be21165c57e9.png)

![image](https://user-images.githubusercontent.com/71716559/130103358-faac9207-d93e-41aa-b29b-28e5b23e8c2a.png)

![image](https://user-images.githubusercontent.com/71716559/130103389-d6cca697-1443-44f9-a8cf-34357102c578.png)

**Describe the results you received:**

**With Docker desktop 3.3.3**

*  docker-compose

docker-compose version  

docker-compose version 1.29.1, build c34c88b2
docker-py version: 5.0.0
CPython version: 3.9.0
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020

`docker-compose up`

Result is as expected by the documentation, environment variables were injected.

![image](https://user-images.githubusercontent.com/71716559/130103485-07ad30a0-50e1-4110-82c2-fc45c6df602e.png)

*  docker compose 

docker compose version
Docker Compose version 2.0.0-beta.1

`docker compose up`

Result is KO , no HTTP_PROXY,HTTPS_PROXY,http_proxy and https_proxy environment variables found

![image](https://user-images.githubusercontent.com/71716559/130105739-e799fa7f-738c-4fac-9caa-ffbeabb2def2.png)

**With Docker desktop 3.6.0**

docker-compose up
or
docker compose up

both refer to Docker Compose version v2.0.0-rc.1

and for both ; 
no HTTP_PROXY,HTTPS_PROXY,http_proxy and https_proxy environment variables found and so the container cannot reach internet :-(

![image](https://user-images.githubusercontent.com/71716559/130103671-f13ffdb8-d978-4551-b178-271af0ae7a72.png)
![image](https://user-images.githubusercontent.com/71716559/130103684-bd184279-7af2-4db4-8a13-3147254ae5c1.png)

when doing docker inspect in the KO result , I see cleary that the Config>Env properties is not set , 

![image](https://user-images.githubusercontent.com/71716559/130107385-0dfcc77e-8a60-4301-9e3c-5cf4a22a4115.png)

and in the OK result it is set 
![image](https://user-images.githubusercontent.com/71716559/130107118-fc0270a5-6960-4ece-8938-55fa715044ad.png)

**Describe the results you expected:**

I expects docker compose cli    Docker Compose version v2.0.0-rc.1 respects the documentation ie that the proxy env variables are injected in the containers

**Comment by ndeloof** [comment]
we indeed miss re-implementation of https://github.com/docker/compose/blob/0bea52b18dda3de8c28fcfb0c80cc08b8950645e/compose/service.py#L909-L915

**Comment by ndeloof** [comment]
Internally tracked as https://docker.atlassian.net/browse/IL-528

**Comment by bb980701** [comment]
Dear Nicolas, ndeloof , when can we expect to have the fix applied and released . Thx
