### ISSUE TITLE
Confusing "invalid compose project" Error Message From Compose v2

### ISSUE THREAD

**Issue by mccarthy** [docker/compose-cli#2050]
Docker Desktop quietly updated me to Compose v2 (`v2.0.0-rc.1` specifically), and now I'm getting this error message when I run most any docker-compose command (e.g. `docker-compose top`) for a complicated project:

`service "extensions" has neither an image nor a build context specified: invalid compose project`

I'm guessing v2 doesn't like something in my compose files, but as best I can tell I don't have a service named "extensions" so this error message is not very helpful.  I saw another issue (https://github.com/docker/compose-cli/issues/1968) related to empty strings and quotes that referenced a similar error message, but it appeared in that case the service mentioned in the error message was a real service from the person's docker-compose file.

I do also get a number of warnings about a variable that is not set, but these warnings occurred (and didn't cause issues) in v1.  
`WARN[0000] The "REDACTED" variable is not set. Defaulting to a blank string. `

**Comment by ndeloof** [comment]
Could you please post your compose file so I can check ?

**Comment by ndeloof** [comment]
Can you try running `docker compose config` to get the actual compose model being applied after merge/interpolation? (assuming this doesn't fail with same error)

**Comment by mccarthy** [comment]
`docker compose config` fails with same error.

**Comment by ndeloof** [comment]
ok, as `docker compose config` also fail, you can try to bisect your compose modela and don't need a running compose app to reproduce the issue:

Try to remove some of your services definition, remove extends etc until the error dissapears

**Comment by mccarthy** [comment]
Figured it out.  v2 is incompatible with the names of some of our services. To repro, run `docker compose config` on this minimal compose file:
```
version: '2.3'

services:

  x-redacted:
    image: "REDACTED"
```

**Comment by ndeloof** [comment]
nice catch.
`x-*` is reserved by the compose specification to define model extensions. But I don't think we would expect extension to apply to the `services` dictionary. I'm checking how we could remove this constraint in compose-go ...
