### ISSUE TITLE
support --ssh (ssh agent forwarding) when building with compose  

### ISSUE THREAD

**Issue by briceburg** [docker/compose-cli#2062]
The `docker build` has a --ssh option to allow the Docker Engine to forward SSH agent connections, for instance to support cloning from private repositories over the ssh protocol in a Dockerfile. Please support this in the compose spec / v2. e.g.

```yml
services:
  foo:
    build:
      context: ./src
      ssh: default
```

there's currently no way to use compose as a builder if the ssh agent is needed to build images. In the meantime I've been using a workaround which inspects the rendered compose config to infer  arguments to pass to `docker build`, e.g.

```sh
# docker-compose build does not currently support --ssh, so we build manually...
# TODO: use regule docker compose build when ssh agent is supported in v2
json=$(mktemp)
docker-compose config | yq -r '.services["triage"]' >"$json"

build_image=$(yq -r '.image' "$json")
build_context=$(yq -r '.build.context' "$json")
build_args=$(yq -r '.build.args|to_entries[] | "--build-arg \"\(.key)=\(.value)\""' "$json")
build_labels=$(yq -r '.build.labels|to_entries[] | "--label \"\(.key)=\(.value)\""' "$json")

docker build --ssh default $build_args $build_labels -t "$build_image" "$build_context"
"$PIPELINE_HOME/bin/manifest" artifact add -t docker "$build_image"
```
 
but this is a bit confusing to developers and prevents us from using central tooling which leverages plain `docker compose build`. 

thanks!

**Comment by ndeloof** [comment]
Changes to the compose file format are discussed by the Compose Specification.
See https://github.com/compose-spec/compose-spec/issues/81
