### ISSUE TITLE
Can't create ECS context

### ISSUE THREAD

**Issue by macsj200** [docker/compose-cli#2071]
I'm trying to create an `ecs` context with `docker context create ecs myecscontext` and I'm getting this message back:

```
docker context create ecs foo
"docker context create" requires exactly 1 argument.
See 'docker context create --help'.
```

Based on [this repo](https://github.com/docker-archive/ecs-plugin) it looks like this functionality has been moved to `docker/compose-cli`. I tried following the installation steps listed here and I'm still getting the same error:

```
/usr/local/bin/com.docker.cli context create ecs foo
"docker context create" requires exactly 1 argument.
See 'docker context create --help'.

Usage:  docker context create [OPTIONS] CONTEXT

Create a context
```

Does anybody have any suggestions for what I can try?

<details>
<summary>docker version</summary>

```
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu1~20.04.1
 Built:             Wed Aug  4 22:52:25 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

<details>
<summary>/usr/local/bin/com.docker.cli version</summary>

```
Client:
 Version:           20.10.7
 API version:       1.41
 Go version:        go1.13.8
 Git commit:        20.10.7-0ubuntu1~20.04.1
 Built:             Wed Aug  4 22:52:25 2021
 OS/Arch:           linux/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.8
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.6
  Git commit:       75249d8
  Built:            Fri Jul 30 19:52:10 2021
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          1.4.9
  GitCommit:        e25210fe30a0a703442421b0f60afac609f950a3
 runc:
  Version:          1.0.1
  GitCommit:        v1.0.1-0-g4144b63
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

</details>

**Comment by macsj200** [comment]
Additionally, I am using docker desktop for windows. I am running the `docker` commands in WSL Ubuntu.

**Comment by macsj200** [comment]
I thought it might be related to turning on experimental features as mentioned [here](https://github.com/docker/docker.github.io/issues/11845) but unfortunately that does not appear to have remedied the situation.

**Comment by ndeloof** [comment]
the ECS support is provided by "Cloud Integration", automatically enabled on Docker Desktop (not an experimental feature anymore)
Don't run `com.docker.cli` directly, which is the raw docker CLI, but the `docker` binary installed by the Cloud Integration. Which OS are you using?

**Comment by macsj200** [comment]
Wow, I must have been fat-fingering the command or something, it seems to be working as expected now. Thanks!
