### ISSUE TITLE
Add option to also set TransitionToPrimaryStorageClass in driver_opts

### ISSUE THREAD

**Issue by komatom** [docker/compose-cli#2092]
Currently lifecycle_policy can only be set to TransitionToIA, but normally to use this to full extend you have to use TransitionToPrimaryStorageClass as well

can we discuss if this is possible

https://github.com/docker/compose-cli/blob/69eda1fbe17ef227e6cc520b06cf370731a5a59f/ecs/awsResources.go#L374

**Comment by chingc** [comment]
Bump
