### ISSUE TITLE
Access DockerLabels in Docker Compose ECS context

### ISSUE THREAD

**Issue by WoodellJ** [docker/compose-cli#2110]
**Description**

I would like to be able to access DockerLabels when doing a docker compose to ecs convert. I have attempted to use `x-aws-cloudformation` to overcome this but I believe because `ContainerDefinitions` is a list the convert is overriding what is normally generated which is I believe a `sidecare` container and then the intended `Ui` container. 

```
x-aws-cloudformation: 
  Resources:
    UiTaskDefinition:
      Properties:
        ContainerDefinitions:
          - DockerLabels: 
              tag : value1
              tag2 : value2
              tag3 : value3
```
Originally post at [here](https://github.com/docker/compose/issues/8939) but was asked to transfer the issue to this repo.

**Steps to reproduce the issue:**
1. Create a Docker Compose 
2. Use `x-aws-cloudformation` to Add `DockerLabels`

**Describe the results you received:**

`ContainerDefinitions` is a list and overridden  by my x-aws-cloudformation.

**Describe the results you expected:**
I am hoping for a way to include these labels in the ContainerDefinitions

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker compose version`:**

Not sure why this is different
```
On ECS Context
Docker Compose version 1.0.17
On Default
Docker Compose version v2.0.0
```

**Output of `docker info`:**

```
ECS Context
Command "info" not available in current context (ecs_context), you can use the "default" context to run this command
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Using AWS Context to Connect to ECS

**Comment by WoodellJ** [comment]
I have also manually done a `docker compose convert` and added the labels to the output. To then deploy that modified file and that works as we intended it to. So I would just hoping for a streamed lined way of doing this built into the `docker compose up` \ `convert` process.

**Comment by rosmcmahon** [comment]
I am currently also looking for a solution to this. adding anything to ContainerDefinitions removes the usual autogenerated ContainerDefinitions configuration. 
I could copy all of the ContainerDefinitions into my compose file, but that makes it pretty hard to maintain.

**Comment by rosmcmahon** [comment]
ah. in my case it's because the configuration I am adding is not allowed with Fargate.
better errors would be nice.
