### ISSUE TITLE
ECS integration sets TaskRoleArn: null, doesn't work with ECS Exec

### ISSUE THREAD

**Issue by adair-kovac** [docker/compose-cli#2120]
**Description**

I'm trying to use ECS Exec to connect to a Fargate container created with the docker compose ecs integration. According to [ECS Exec documentation](https://aws.amazon.com/blogs/containers/new-using-amazon-ecs-exec-access-your-containers-fargate-ec2/), you need to specify `--enable-execute-command` for a task. Unfortunately, there's no mention of ECS Exec in the [docker compose ECS features](https://docs.docker.com/cloud/ecs-compose-features/).

As a result, I've tried using the [`aws ecs update-service` ](https://docs.aws.amazon.com/cli/latest/reference/ecs/update-service.html) command to add `--enable-execute-command`. When I provide the full task definition ARN, it fails on:

> An error occurred (InvalidParameterException) when calling the UpdateService operation: The service couldn't be updated because a valid taskRoleArn is not being used. Specify a valid task role in your task definition and try again.

Looking at the task definition json, it includes
```
  "taskRoleArn": null,
```
and again I don't see any way to explicitly provide this in the ECS compose features doc. 

Is there a way to provide a non-null taskRoleArn, or a more direct way to use ECS Exec with a docker compose fargate container? Is setting a null taskRoleArn the expected/desired behavior of this feature?

**Output of `docker-compose --version`:**

```
docker-compose version 1.29.2, build 5becea4c
```

**Output of `docker version`:**

```
Docker version 20.10.8, build 3967b7d
```

**Comment by bounlu** [comment]
You may want to to try `docker compose v2` to fix this.

**Comment by christopher-haueter** [comment]
I'm experiencing the same issue.

```
❯ aws ecs update-service --service <service> --cluster <cluster> --enable-execute-command

An error occurred (InvalidParameterException) when calling the UpdateService operation: The service couldn't be updated because a valid taskRoleArn is not being used. Specify a valid task role in your task definition and try again.
```

```
❯ docker compose version
Docker Compose version dev
```

```
❯ docker version
Client:
 Cloud integration: v1.0.22
 Version:           20.10.11
 API version:       1.41
 Go version:        go1.16.10
 Git commit:        dea9396
 Built:             Thu Nov 18 00:36:09 2021
 OS/Arch:           darwin/amd64
 Context:           staging
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.11
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.16.9
  Git commit:       847da18
  Built:            Thu Nov 18 00:35:39 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.12
  GitCommit:        7b11cfaabd73bb80907dd23182b9347b4245eb5d
 runc:
  Version:          1.0.2
  GitCommit:        v1.0.2-0-g52b36a2
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by andrekrosby92** [comment]
Are you providing it with your service?
```yaml
services:
  web:
    # ...
    x-aws-policies:
      - arn:aws:iam::671546565857:policy/DockerExecRole

**Comment by andrekrosby92** [comment]
Are you providing it with your service?
```yaml
services:
  web:
    # ...
    x-aws-policies:
      - arn:aws:iam::<ACC_ID>:policy/DockerExecRole
 ```
 
 My policy for reference:
 ```json
 {
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Allow",
            "Action": [
                "ecs:ExecuteCommand",
                "ssmmessages:CreateControlChannel",
                "ssmmessages:CreateDataChannel",
                "ssmmessages:OpenControlChannel",
                "ssmmessages:OpenDataChannel"
            ],
            "Resource": "*"
        }
    ]
}
```

 Also when updating the service, you need to force a new deployment
 ```
 aws ecs update-service \
     --service <service> \
     --cluster <cluster> \
     --enable-execute-command \
     --force-new-deployment
```

**Comment by MrChrisRodriguez** [comment]
Is there a way to modify the compose.yml to enable the execute command (EnableExecuteCommand: true) for one or more services in lieu of running the update-service command and forcing a new deployment?

It seems a bit wonky (if I understand correctly) that I have to write a configuration, spin up the service, then add additional configuration/restart the service with a command. 

Isn't this the sort of thing the overlay capability is for? I struggle to find an exhaustive list of supported overlays and/or a methodology I could use to infer overlays that aren't explicitly laid out.

**Comment by chingc** [comment]
@andrekrosby92 Thanks, your steps worked for me.

I really wish I could enable exec in my docker-compose.yml instead of having to explicitly enable it with `aws ecs ... --enable-execute-command`.

**Comment by JohnPreston** [comment]
Hello all. I know this ain't native to the docker toolset, but in the meantime / instead, see if [x-ecs.EnableExecuteCommand](https://docs.compose-x.io/syntax/compose_x/ecs.details/ecs.html) could work for you?
