### ISSUE TITLE
Future Direction and Recommended Growth Path

### ISSUE THREAD

**Issue by geocertify** [docker/compose-cli#2165]
It looks like development on this repo wound down and flatlined starting about a year ago.

I grew up on Docker-for-AWS and this is _deja vu_ for me.

What's the growth path forward?  Is there a strategy doc?  Is there a plan for compose-cli and ECS?  If not, can you point to any recommendations to the community on how to move forward with Docker on AWS?  Is it safer to be looking at Kubernetes, for example?

Thanks!  I drove my old Docker-for-AWS all the way through 2021--can you believe it?  I have to let it go now, and on paper this compose-cli looked like the way to go.  But I see it's broken and not getting fixed, so what do you guys recommend?

**Comment by JohnPreston** [comment]
Well @geocertify, I am working continiusly for 2y on [ECS Compose-X](https://docs.compose-x.io)

Seeing your recent other messages, i.e. EFS, i hope you will give it a try before throwing away your docker compose files.

I have been working on it and adding more and more features, fixing up bugs and adding up features based on user stories.

i.e. Saw people asking for FireLens so gone all in into making it th best I could think of

**Comment by geocertify** [comment]
Thanks so much @JohnPreston,  I am plugging away, but with an eye on the exit!  I've hit numerous fundamental issues with EFS that should be handled in compose.  I know how hard it is and I appreciate what's gone into this, but I also know how it feels when a thing starts going cold.  

My project is just a scalable nodejs website with a database on the back end. I also use a shared node_modules volume--I don't want every nodejs instance to load a separate copy of all the modules.  So the EFS is used to store data for the db and the static node_modules.  I populate all that with existing data before starting up the database and node app. 

For years I've used a little run-and-exit container stored on ECR to copy the node_modules onto a shared Volume--worked great.  Now the run-and-exit blows up -- compose throws an "**Essential Container Exited**" error and destroys the whole stack.   I set that service  _essential: false_, in the compose file but then it throws "**Essential Container Required**"--and destroys the whole stack.  I set the EFS _external: true_, thinking I'd run it in a separate compose file, but that throws "**EFSMountTarget Already Exists**" and destroys the stack.  So I added an overlay to the CloudFormation using a hack I found from over a year ago that tricks CF into creating AccessPoints instead of MountTargets and that works.  Then I just had to figure out how to correctly map the security groups for the case of an "external EFS"--that was another CF overlay in the compose file.

Anyway, there's probably a better way to do all this, but for now I tar up the node_modules on the dev platform, scp that onto an EC2 instance, ssh onto that, mount the EFS manually, and un-tar the node_modules onto the file system that way.

**Comment by JohnPreston** [comment]
@geocertify I get it. I started compose-x weeks before AWS & docker announced this thing, so I thought "oh, AWS, you did it again ..." (i.e. every year I do a thing, they do it too, ends with a nice few projects in the graveyard).

But this one, I don't know, I just did not love the way it is done and found limitations really fast so I kept going with my own project. Haven't done much "marketing" with it until more recently, mostly because it wasn't quite as stable as I wanted.

I only have 1 quick question before having a much longer reply: do you set the user:group ID for your services to run ?
AccessPoints having a Posix capability, just wanted to know if you were using it / wanted to use it?

**Comment by geocertify** [comment]
I'm working on **AWS Copilot** right now.  Sort of feels like that's what replaced this compose-cli.  @JohnPreston I'll keep in touch, but looks like even Docker didn't want to stand up to AWS on this one...  it's home-court for AWS all the way, and I'm sure you know way better than I how tough it is mapping services into a CloudFormation template!
