### ISSUE TITLE
Docs issue "deployment" vs "deploy"

### ISSUE THREAD

**Issue by actualben** [docker/compose-cli#2182]
https://github.com/docker/compose-cli/blob/6135c5edf1664dab0c0d05ab65a650587bcd2085/docs/ecs-compose-features.md?plain=1#L73

Should this be `Replaced by service.deploy.restart_policy` instead?

**Comment by nicksieger** [comment]
Looks like it, would you mind submitting a PR?

**Comment by actualben** [comment]
Darn. Looks like this duplicates #2153... and that issue captures an additional thing to correct. I'm going to see about updating my PR.

**Comment by actualben** [comment]
actually just closing this in favor of #2153.
