### ISSUE TITLE
docker.exe has no Windows resource version and icon

### ISSUE THREAD

**Issue by StefanScherer** [docker/compose-cli#242]
During some tests on Windows I saw in Process Explorer that the new `docker.exe` has no Windows version info and icon.

![new-docker-cli-no-windows-resources](https://user-images.githubusercontent.com/207759/85030080-5008be00-b17d-11ea-8a3e-ceacbdd62b66.jpg)

The `docker-classic.exe` that also is in this screenshot has this with some helper files from https://github.com/docker/cli/blob/master/scripts/gen/windows-resources script and files in https://github.com/docker/cli/tree/master/scripts/winresources

Note to self: I still wonder why this very old whale icon is used instead of the new black Icon I updated 4 months ago.

**Comment by ndeloof** [comment]
with the architecture re-design to make compose-cli a docker/cli backend, this issue is now obsolete
