### ISSUE TITLE
Download existing Docker CLI as part of e2e tests

### ISSUE THREAD

**Issue by chris-crone** [docker/compose-cli#399]
When debugging a [CI failure](https://github.com/docker/api/runs/882267598?check_suite_focus=true#step:7:24) and chatting to @thaJeztah, I found that the output of the CLI for logging out of a registry changed [between 19.03.11 and 19.03.12](https://github.com/docker/cli/commit/5a12f90b4cbf675f3b7d3c0a216ce5eee911e88a#diff-8d8d078d8774b4057cf393f93eb46a04).

We should download the version of the Docker CLI that we expect to ship with to make sure that we don't run into issues caused by a version mismatch like this.

**Comment by ndeloof** [comment]
actually fixed by https://github.com/docker/compose-cli/issues/1063
