### ISSUE TITLE
Revisit ECS context creation workflow

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#556]
**Description**
ECS context creation relies on selecting a profile from `.asw/config` file, but based on users feedback and also our own use of aws-okta we should also allow use of plain `AWS_*` environment variables

so, the `context create` flow must be revisited to ask user for crendentials _only_ if no AWS config files or environment variable is detected, and create `~/.aws/*` files with entered credentials on `default` profile to mimic the `aws` CLI. aws-go-sdk will automatically select the credentials source from env/config files.

**Comment by mreferre** [comment]
Nicolas, will this include, in addition to `.asw/config` and `AWS_*` variables, also the credentials populated in the `.asw/credentials` file?
