### ISSUE TITLE
Clarify how we will support EC2 with autoscaling

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#563]
**Description**

Need to clarify how we plan to support EC2 launch type in addition to Fargate

Roadmap says:

- [ ] CLI will support, with compose spec extensions as necessary, running a service on EC2 launch type.  
- [ ] CLI will automatically choose instance types and AMI.
- [ ] CLI will automatically configure an ASG and a capacity provider with managed scaling enabled.  
- [ ] CLI will configure the default cluster capacity provider strategy to use the capacity provider for all services

For services with gpu resources requirements, or other feature not available on Fargate, we need to clarify how the ECS integratoin will manage EC2 resources.

- User should have to explicitely request EC2 support, not just because some selected option can't be implemented on Fargate 
  suggestion: (ab)use the `runtime: EC2` field
- We should only support the reference AMIs per usage (GPU, ARM) from default catalog to avoid exposing user to the AMI selection complexity
- Configuration of autoscaling groups require us to define a machine type. This is the hard part, as we hardly can guess

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by chris-crone** [comment]
I see this is done on the board, can we close it?

**Comment by totalhack** [comment]
Hi there, did the `runtime: EC2` proposal end up making it in? If so is this in the latest release? Thanks for your help.

**Comment by ndeloof** [comment]
@totalhack by discussion with AWS people we decided to give up with this option (which would have made it impossible to run the compose file locally during development)
EC2 support is only available for services which declare requirement for features that are not available on Fargate, i.e. for now this only is enabled for services with GPU devices requirements.

**Comment by totalhack** [comment]
OK, thanks for the feedback. Is there anything that would prevent this from working when targeting an existing EC2-based ECS cluster?

**Comment by ndeloof** [comment]
@totalhack not that I know, but if you have a concrete problem in mind better ask on https://dockercommunity.slack.com/archives/G016UBBRAE5 or create a dedicated issue
