### ISSUE TITLE
`compose up`on ECS doesn't detect updated image with same tag

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#612]
see https://github.com/docker/ecs-plugin/issues/246 for context

tl;dr: as image is rebuilt/pushed with same tag, `compose up` doesn't detect any change in cloudformation model.
proposed solution: to mimic docker/app, the TaskDefinitions we create in CloudFormation model should use image digests, not tag - which, for some reasons, are mutable ¯\\_(ツ)_/¯.

**Comment by dsposito** [comment]
+1
