### ISSUE TITLE
Deprecate aci-integration-beta repo

### ISSUE THREAD

**Issue by chris-crone** [docker/compose-cli#649]
**Description**
Now that this repo is public we can deprecate the aci-integration-beta repo. This includes doing the following:

- [x] Move issues across
- [x] Update README to point people here
- [x] Optionally remove all released binaries on that repo

**Comment by gtardif** [comment]
@chris-crone FYI I also updated changelogs in compose-cli releases (from the cloud-integration-beta repo), back to v0.1.10
