### ISSUE TITLE
Docker compose stuck "waiting" when trying to deploy

### ISSUE THREAD

**Issue by HarrisonFretwell** [docker/compose-cli#650]
I'm unable to deploy a simple app using **docker compose** using the CLI on Windows 10. Attempting to deploy causes the container group to be made, and then any containers to simply be "waiting" until they time out after 900s. I've followed the [documentation here](https://docs.docker.com/engine/context/aci-integration/) to the letter as best as possible and still no luck.

My docker-compose file is simply this:
```
version: "3.8"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
```
And I've tested that this works perfectly fine (it is just the nginx container after all) on my own machine. By this I mean navigating to `localhost:80` shows the basic nginx hello world page. Updating the docker-compose file (specifically the name of the container), also results in updating the deployment in the aci context.

I've tried creating an entirely new resource group and following through the tutorial again replicating every step, reinstalling WSL and docker (ensuring I'm using the beta edge version). I'm logged in properly, and I've tried pulling various images, both my own and publicly listed ones to no avail.

To reiterate, uploading singular containers works just fine, such as by using `docker --context myacicontext run -p 80:80 nginx
`.

It might be worth noting that I'm using the free-trial subscription on azure, but I couldn't find any mention against this in the documentation.

You can see the the waiting process here. This continues all the way up until timeout.
![image](https://user-images.githubusercontent.com/4212596/94158215-0adde180-fe7a-11ea-8355-56962d9ee65b.png)

**Comment by gtardif** [comment]
Thanks for your feedback. 
We have experienced some situations where the ACI backend temporarily seems to be "frozen", and deployments can hold on for a long time ; although I haven't seen this recently. When I hit such situations, everything seemed back to normal after some time, maybe an hour or so at the most.

Does this still happen in your example? 
Could you get the output of `docker ps`, that should show the status of your container being deployed, if this happens again. That might help understanding what is happening in Azure. 
cc @macolso, @novinc in case you have any updates on this sort of issues

**Comment by gtardif** [comment]
Closing as relate to ACI APIs, won't be able to fix things in this repo, we're just using the ACI go SDK.
