### ISSUE TITLE
ACI Container Properties

### ISSUE THREAD

**Issue by timdagit** [docker/compose-cli#651]
Is there any view on how/when it will be possible to configure aci container properties? dns-name-label, cpu, memory etc

**Comment by gtardif** [comment]
dns-label-name, cpu, memory have been added in the Docker ACI integration, see [compose features](https://github.com/docker/compose-cli/blob/main/docs/aci-compose-features.md) and [container features](https://github.com/docker/compose-cli/blob/main/docs/aci-container-features.md). 

[v1.0.1](https://github.com/docker/compose-cli/releases/tag/v1.0.1) will be included in the next release of Docker Desktop, available very soon.

Feel free to detail if there are other features that are not yet available that you would like to have in the integration, we prioritise based on user feedback.
