### ISSUE TITLE
Allow passing arguments to the container 

### ISSUE THREAD

**Issue by metcalfc** [docker/compose-cli#656]
The way the args are parsed there is no way to pass arguments to the container itself. Local docker I can:

```
docker run  -it --rm --name=iperf3-server -p 5201:5201 networkstatic/iperf3 -s
```

And the `-s` is passed to iperf3. In ACI's run:

```
docker run  -p 5201:5201 networkstatic/iperf3 -s
unknown shorthand flag: 's' in -s
```

**Comment by gtardif** [comment]
Image command can now be overriden in the command line. 
In ACI, overriding command parameters also overrides the entrypoint of the image if one is defined, unlike with the docker local engine. ACI does not have the notion of entrypoint that we could potentially override.
So you need to slightly change your command line for ACI invocation, and add the actual binary invoked, that is defined in the image entrypoint. 
(for images defining a COMMAND but no ENTRYPOINT, there is no difference between ACI and the local docker engine)

So on ACI I managed to invoke: 
```
> docker --context acicontext run --name=iperf3-server -p 5201:5201 networkstatic/iperf3 iperf3 -s -V -d
[+] Running 2/2
 ⠿ Group iperf3-server  Created                  9.0s
 ⠿ iperf3-server        Done                           51.9s
2020-10-07T10:34:26.9208801Z stdout F iperf 3.6
2020-10-07T10:34:26.9208801Z stdout F Linux SandboxHost-637376636434999278 4.19.104-microsoft-standard #1 SMP Fri Feb 21 04:01:19 UTC 2020 x86_64
2020-10-07T10:34:26.9449005Z stderr F warning: this system does not seem to support IPv6 - trying IPv4
```
