### ISSUE TITLE
Support for `docker <noun> <verb>` syntax

### ISSUE THREAD

**Issue by sujaypillai** [docker/compose-cli#659]
The command `docker container rm` failed for me while having the context set too ACI.
<img width="1000" alt="Screenshot 2020-06-27 at 12 38 13 AM" src="https://user-images.githubusercontent.com/3936714/85920131-c014f380-b8a3-11ea-8a3d-52f3d3e4278d.png">

Will the commands in the form `docker <noun> <verb>` syntax be supported?

**Comment by ndeloof** [comment]
with the architecture re-design to make compose-cli a docker/cli backend, this issue is now obsolete
