### ISSUE TITLE
Review & document ACI secret mapping

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#663]
We have ACI secret support, but this was done before reviewing the volume implementation, there might be things to adjust / improve. 
- [x] Allow to map secrets to `run/secrets` (and not `run/secrets/subfolder`). We can do this by defining several secret values in ACI secret volumes (https://github.com/docker/compose-cli/blob/main/aci/convert/convert.go#L214), containers will see one secret file for each secret defined here, and we can map the entire thing to `/run/secret`. We need to be careful and not share the same secret volume with different containers, if they are not supposed to see all secrets, we'll need to define one volume per container.
- [x] remove `inline:` (https://github.com/docker/compose-cli/blob/main/aci/convert/convert.go#L52), secrets should not be define in compose files, these are not secrets anymore (use env properties or something else) 
- [x] add tests on ACI secret usage.

**Comment by gtardif** [comment]
Currently secrets are mapped to subfolders of `/run/secrets`. 
- [ ] We could define several secret values inside a single ACI secret volume, and map this to `/run/secret`, the container then sees one file for each secret value. However we need to be careful to have different ACI secret volumes for containers that don't see the same secrets. 
- [ ] we should remove the `inline:` option to set secret value in the compose file directly. Secrets should not be written in compose files, these are not secrets anymore (use env variables instead)

**Comment by ulyssessouza** [comment]
Implemented in https://github.com/docker/compose-cli/pull/753 and https://github.com/docker/compose-cli/pull/757
