### ISSUE TITLE
Add support for Target Group health checks/ELB grace periods

### ISSUE THREAD

**Issue by icj217** [docker/compose-cli#667]
It would be nice if the plugin allowed us to configure the health check behavior of the target group(s) that containers are added to. Also, being able to specify the `HealthCheckGracePeriodSeconds` option per service would serve a similar purpose.

**Comment by cch1** [comment]
Can you help me understand what you mean by this?

> we configure container health-check when set by comose file, but the TargetGroup health check mechanism is based on pinging an HTTP endpoint, while the Compose/Docker model for healthcheck is based on a command being ran. Would need to extend the Compose specification so it allows a new HTTP HealthCheck type

My simple single-container ECS compose is failing with `Task failed ELB health checks in (target-group arn:aws:elasticloadbalancing:us-east-1:264945611335:targetgroup/docke-Datom-1OF2I6UTDB0D8/b07e81079eaca14c)`.  The service in question is a database... I don't even _want_ a load balancer in front of it (it is not a distrubuted/cluster database), but if I have one, how do I satisify the  ELB health check?  Would it suffice to fabricate a health check script that establishes a client connection?

**Comment by cch1** [comment]
This comment https://github.com/docker/compose-cli/issues/777#issuecomment-722447259 appears to address the same issue I face: how does one define a back-end network such that it gets NO load balancer -and a front-end network that does get a load balancer (with HTTP(S)-based health checks).

**Comment by ndeloof** [comment]
Not being supported in the compose model we can't map an existing attribute to define URL-based HealthCheck, but I guess we could introduce reasonable `x-aws-*` extensions and propose those for compose-spec

Which would look something like this:
```yaml
services:
   foo:
      image: ...
      healthcheck:        
        x-aws-http: 
          path: "/health"
          port: "8080"
          match: "200-499"
```
The same `healthcheck` section would then be used to define both the container level healthcheck command and the external path-based healthcheck.

**Comment by cch1** [comment]
This would solve my problem (match needs to include 401).

**Comment by robogeek** [comment]
I see in https://github.com/docker/compose-cli/blob/main/docs/ecs-compose-features.md that it installs a prebaked health check of checking `/` and looking for a `200` status code.  Obviously this won't work in all cases.

The `x-aws-http` idea is pretty good, for a health check that pings an HTTP port.  Aren't there services that have a non-HTTP health check?

**Comment by ndeloof** [comment]
Cloudformation overlay can be used to configure healthcheck, see https://deploy-preview-12080--docsdocker.netlify.app//cloud/ecs-integration/#tuning-the-cloudformation-template
