### ISSUE TITLE
Cloud Map isn't always cleaned up

### ISSUE THREAD

**Issue by metcalfc** [docker/compose-cli#673]
I'm not sure how cloud map domain escaped the stack but I've had to delete the cloud map domain manually twice after a down. The stack is completely deleted but the stack remains. 

```The VPC vpc-aea5c3d6 in region us-west-2 has already been associated with the hosted zone Z02108341RK8P60554DIZ with the same domain name. (Service : AmazonRoute53; Status Code: 400; Error Code: ConflictingDomainExists; Request ID: bf263a31-1ca9-42e3-bbae-9f62b0d591ec; Proxy: null)```

Vanilla setup. Latest Desktop Edge. No x-params in the compose file. I'm not sure how else to debug this but I wanted to capture it as a repeat issue.

**Comment by ndeloof** [comment]
AWS has deployed a fix in all regions for this issue, haven't seen anymore for days => closing
