### ISSUE TITLE
Document supported deploy limits for the cloud backends

### ISSUE THREAD

**Issue by metcalfc** [docker/compose-cli#680]
A user on Twitter reached out: https://twitter.com/darsh_shukla/status/1309710647379152896

>  Can we specify CPU count and Memory request for ACI in docker compose file for container groups?

We talk about deploy limits in the Minecraft blog post and in the various demos around it. The compose spec outlines the various legitimate uses of the deploy stanza. However we don't current have a map for ACI or ECS as to what deploy limits are valid for those backends: cpu, memory, etc. 

The docs on `docs.docker.com` for ACI doesn't mention limits at all.

**Comment by karolz-ms** [comment]
The `docker run` command accepts `--cpus` and `--memory` flags to request specific number of CPUs and limit memory allocated for an ACI container group, respectively. This follows the native [resource request](https://docs.microsoft.com/en-us/azure/container-instances/container-instances-reference-yaml#resourcerequests-object) that is part of ACI cgroup spec. I have tried those and they seem to work as expected.

@metcalfc  are you saying there is noting in Compose that translates to ACI resource requests?

CC @gtardif

**Comment by metcalfc** [comment]
This does work. The compose spec documents the `deploy` stanza here: https://github.com/compose-spec/compose-spec/blob/master/spec.md#deploy and https://github.com/compose-spec/compose-spec/blob/master/deploy.md

The Docker ACI docs (https://docs.docker.com/engine/context/aci-integration/) do not document anything about `deploy` or `limits` and what is supported or how you would use it. Outside of the [Minecraft examples](https://github.com/docker/awesome-compose/blob/a3c38822277bcca04abbadf34120dcff808db3ec/minecraft/docker-compose.yml#L9) its not clear how to use it or that it is supported. See the referenced tweet in the OP. 

This is just about making the docs more friendly to folks coming into the ACI work and not having to guess or experiment.
