### ISSUE TITLE
Support path-based with Application Load Balancers

### ISSUE THREAD

**Issue by ay0o** [docker/compose-cli#691]
Only network load balancers are supported.

It's quite common to have an application load balancer acting as endpoint forwarding traffic to the target groups based on rules, that is, path-based targeting:

```
/s1 --> target group for s1
/s2 --> target group for s2
```

Right now, even passing an existing pre-configured ALB with `x-aws-loadbalancer` doesn't work, because the `convert` tries to create a TCP  listener which is not suitable for an ALB (only HTTP and HTTPS are supported).

If an ALB is specified and a service exposes a port in the compose file, `docker` should not try to create a listener, just configure the port in the task definition.

Ideally, we could even expand this to have fine-grained control on the ALB and target groups with something like:

- `x-aws-loadbalancer-type`: application or network.
- `x-aws-loadbalancer`: arn for the load balancer. If not specified, create one using the type specified by `x-aws-loadbalancer-type`.
- `x-aws-alb-rules`: list of rules to attach to the listeners of an ALB.  Required if `x-aws-loadbalancer-type` is application. Not applicable for NLB.
- `x-aws-alb-listeners`: list of listeners for the ALB.  Required if `x-aws-loadbalancer-type` is application. Not necessary for NLB as NLB would automatically create a listener for each exposed port (as it's working right now).
- `x-aws-loadbalancer-target-groups`:  list of arn of the target groups to attach to the load balancer. Required if `x-aws-loadbalancer-type` is application. If it's network and no target groups are specified, they could be created as they are right now.

And so on.

**Comment by flaviostutz** [comment]
I need almost the same thing, but adding domain and protocol (http/https) capabilities in forwarding as well.
Do you think we could merge this discussion with issue #777? 
The idea is to use full URLs to specify protocol, domainname and paths for forwarding rules on LB.

**Comment by ndeloof** [comment]
While compose-spec get approved support to define routing, one can rely on cloudformation template overlays to tweak LoadBalancer's Listeners and associate a path to a service. See https://deploy-preview-12080--docsdocker.netlify.app//cloud/ecs-integration/#adjusting-load-balancer-http-healthcheck-configuration

Please note one major issue doing so is that this only applies to external->service communication, not service-to-service
