### ISSUE TITLE
Support to create or modify Route53 records resolving the load balancer

### ISSUE THREAD

**Issue by ay0o** [docker/compose-cli#692]
If the idea is to convert `docker` in an all-in-one toolbox, then a parameter `x-aws-loadbalancer-domain` or similar would be very welcome to create or update a Route53 record resolving the address of the load balancer.

Otherwise, we need to previously create a load balancer and the record, and then pass the arn with `x-aws-loadbalancer`.

The certificate for the load balancer is a must as well, but I see it was already mentioned in https://github.com/docker/ecs-plugin/issues/249.

**Comment by ndeloof** [comment]
x-aws-loadbalancer was introduced to cover such a use-case, and I'm not in favour for ECS integration to interact with Route53 and assume this DNS service is in used by all users.

I'm not sure this is feasible, but if you can define a CloudFormation `AWS::Route53::RecordSetè resource to create/update your domain name records, then you can rely on cloudformation overlays to add this one to the template being applied by `compose up`, read more on https://deploy-preview-12080--docsdocker.netlify.app//cloud/ecs-integration/#adjusting-load-balancer-http-healthcheck-configuration
