### ISSUE TITLE
enable Proxy protocol v2 for a network load balancer's target groups

### ISSUE THREAD

**Issue by ledzeppelin** [docker/compose-cli#695]
Currently this is a step I'm manually doing, not sure if it requires a change to the compose spec.

**Comment by ndeloof** [comment]
Ability to tweak the CloudFormation template to patch TargetGroup has been introduced, see https://deploy-preview-12080--docsdocker.netlify.app//cloud/ecs-integration/#adjusting-load-balancer-http-healthcheck-configuration
This will allow you to get this supported without the need to AWS-specific extensions
