### ISSUE TITLE
[ECS] Short hostname resolution does not work with Alpine based images

### ISSUE THREAD

**Issue by chris-crone** [docker/compose-cli#705]
**Description**
As the short hostname resolution on ECS currently works by injecting a `LOCALDOMAIN` environment variable into containers, it does not work for containers that do not respect this. Notably Alpine Linux based containers will not work.

One possible workaround is [this PR](https://github.com/docker/compose-cli/pull/688) which edits the shared `/etc/resolv.conf` instead using a sidecar.

**Steps to reproduce the issue:**
1. `docker --context ecs compose up` with Alpine based images
2. Timeout on deploy as services cannot resolve one another

**Comment by ndeloof** [comment]
proposed solution here : https://github.com/docker/compose-cli/pull/688

**Comment by ndeloof** [comment]
#688 was approved
