### ISSUE TITLE
revisit ECS context creation

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#725]
**Description**
ECS context creation relies on aws CLI config files to select a profile and store credentials. Many users (including Docker developers using Okta) get credentials set by `AWS_*` environment variables, and there might be other workflows to retrieve credentials (see https://github.com/docker/ecs-plugin/issues/166).

Generaly speaking, the context creation has been source of confusion 
(https://github.com/docker/ecs-plugin/issues/198, https://github.com/docker/ecs-plugin/issues/174)

I suggest we revisit the `context create ecs` command so it support 3 usage scenarios:
1. New AWS user, don't have `~/.aws` config file
1. Existing AWS user, have `~/.aws` config file with a profile configured
1. Existing AWS user with third party tool to populate `AWS_*` variables (which is typically what we do by Docker with okta)

To support those we need to update the `context create` flow:

- `docker context create ecs --key=.. --secret=.. --region=..` with explicit access keys set by user, probably as a new AWS user getting those from the web console but not having the `aws` CLI installed. This would create `~/.aws/config` and `~/.aws/credentials` files based on user input as profile `default` and configure docker context accordingly
- `docker context create ecs --profile` would select an existing aws profile and configure docker context to use this profile. this flag can't be combined with `key`, `secret` nor `region`
- `docker context create ecs` (interactive) 
  - if `AWS_ACCESS_KEY_ID`, `AWS_SECRET_ACCESS_KEY`, `AWS_SESSION_TOKEN` and `AWS_DEFAULT_REGION` are set in environment, just create context with `default` profile. This address usage scenario #3
  - list profiles from `~/.aws` config file and let user select one.
  - offer option to create a profile (`default`) **only** if no profile exists. User who already have aws config files are expected to know how to create extra profiles. This interactive mode only target users for scenario #1.

**Comment by ndeloof** [comment]
We could also get inspired by https://github.com/aws/copilot-cli/blob/mainline/internal/pkg/term/selector/creds.go

**Comment by ndeloof** [comment]
@nebuk89 assigned to you so you validate the usage scenarios and context creation flow

**Comment by nebuk89** [comment]
Scenarios look sound to me, though I have only run through 2/3 of them myself (OKTA & new).

Broken down by user:

**New**
I type `docker context create ecs myecscontext` -> I am offered a new profile and continue through the interactive builder providing the required data? 

**New with AWS portal open**
I type in `docker context create ecs myectcontext --key =.. --secret=.. `
I told I have had a profile created for me?

**existing profiles**
I type `docker context create ecs myecscontext` -> I am offered my list of profiles to choose from 

**OKTA is setup**
I type `docker context create ecs myecscontext` -> and the default profile uses the environment set in OKTA? 


Then we also have the other flags including profile for those who want to specify a profile as part of the create?

**Comment by ardumez** [comment]
Why is closed ?
