### ISSUE TITLE
Support database provisioning

### ISSUE THREAD

**Issue by camilosantana** [docker/compose-cli#726]
Relational database definition would allow devs to spin up/down stacks in the cloud context easier with a single command. Otherwise, they have to connect to an existing instance or provision something with terraform or another external task.

Parameter structure / abstraction can be taken from the [terraform-aws-modules/terraform-aws-rds](https://github.com/terraform-aws-modules/terraform-aws-rds) module.

This issue is related to existing desires for persistent data:

- [docker/ecs-plugin/issues/254](https://github.com/docker/ecs-plugin/issues/254) - Persistence volume data
  - in the example here, a user is provisioning a persistent volume for postgres. It would be ideal to provide postgres itself.
- [docker/ecs-plugin/issues/220](https://github.com/docker/ecs-plugin/issues/220) - Support persistent volumes with EFS
  - connecting to an existing RDS instance is mentioned here. In a staging environment, it would be ideal to bring up a dedicated instance and seed data rather than manage an existing instance.

reference:

issue created from context of a [slack thread](https://cloud-native.slack.com/archives/C01162AJ23C/p1600791657008200) in CNCF [compose-specification channel](https://cloud-native.slack.com/archives/C01162AJ23C).

**Comment by ndeloof** [comment]
This would require compose specification to be extended to support an abstract definition for a database service (or, generally speaking, "external services"

**Comment by camilosantana** [comment]
i ended up switching to [copilot add-ons](https://aws.github.io/copilot-cli/docs/developing/additional-aws-resources/)

to reduce the amount of IAC code to deploy load balanced web services that rely on Postgres+Redis for persistent storage and caching.

**Comment by tkrotoff** [comment]
This issue should be re-opened

**Comment by JohnPreston** [comment]
You can use [x-rds](https://docs.compose-x.io) which will allow you to provision RDS Aurora & non-aurora Cluster & Instances. It can create new ones as much as use existing ones and import a secret to pass onto the service if necessary.
It will automatically create security ingress rules to allow your service access to the DB and can expose properties to your containers such as endpoint and such. Hope this helps
