### ISSUE TITLE
unable to select login to different Azure cloud

### ISSUE THREAD

**Issue by bb5178** [docker/compose-cli#749]
Cloud Integration 0.1.18

As-title: docker login azure command have no option to select different Azure cloud (AzureCloud, Azure ChinaCloud, AzureUSGovernment, and AzureGermanCloud)

**Comment by karolz-ms** [comment]
Duplicate of https://github.com/docker/compose-cli/issues/658

**Comment by gtardif** [comment]
closing as duplicate
