### ISSUE TITLE
Option to enable Cross-Zone Load Balancing for Network Load Balancers

### ISSUE THREAD

**Issue by ledzeppelin** [docker/compose-cli#755]
**Description**

Network load balancers support cross zone load balancing (this is enabled by default for Application load balancers), however there doesn't seem to be a way to set this in the compose file so it's recognized by compose-cli.

https://aws.amazon.com/about-aws/whats-new/2018/02/network-load-balancer-now-supports-cross-zone-load-balancing/

https://docs.aws.amazon.com/elasticloadbalancing/latest/userguide/how-elastic-load-balancing-works.html#availability-zones

**Steps to reproduce the issue:**
1. Configure a public facing service in your compose file that accepts http traffic on a non 80 port like 8080 - this will result in a network load balancer being spun up.
2. Query the load balancer's DNS.  You should hopefully see two A records (one for each AZ.) Sometimes there's only one A record, but another one pops up eventually to support multiple AZs if there's enough traffic.

**Describe the results you received:**
3. Try reaching an endpoint via `curl MyApp-123.elb.us-east-2.amazonaws.com.:8000/`.  This command will respond immediately 50% of the time, or hang 50% of the time depending on which of the AZs the traffic was routed to.  Some languages and tools will handle failover to the A record in the AZ that the application is deployed to, however DNS failover is not handled by `curl` automatically and thus requests fail 50% of the time.

The consequence of not enabling cross zone load balancing is that when you query the load balancer's DNS records and there's two A records for the load balancer, with each being in a different availability zone; since the actual application is deployed in only 1 availability zone, half the requests hang.

**Additional information you deem important (e.g. issue happens only occasionally):**
Perhaps adding an extension like `x-aws-cross-zone-balancing` could help.

**Output of `docker version`:**

```
$ docker version
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
AWS ECS

**Comment by ndeloof** [comment]
This explains an earlier issue reported on ecs-plugin before code was moved into this repository.
need to set https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-ec2-elb.html#cfn-ec2-elb-crosszone
I don't see any reason we don't set this by default
