### ISSUE TITLE
ECS: How to use private dockerhub repositories?

### ISSUE THREAD

**Issue by raveesh-me** [docker/compose-cli#756]
As was available with ecs-plugin,
https://blog.56k.cloud/how-to-deploy-containers-directly-to-aws-ecs-using-docker/

What is the equivalent of `docker ecs secret create` in compose-cli?
What is the preferred way to have private dockerhub images deployed with compose-cli?

**Comment by ndeloof** [comment]
Just use `docker secret create` with your ECS context enabled

**Comment by tuanalumi** [comment]
I ran the command in the doc: https://docs.docker.com/engine/context/ecs-integration/#private-docker-images

```
docker secret create dockerhubAccessToken --username <dockerhubuser>  --password <dockerhubtoken>
```

And got `unknown flag: --username`. I don't know what is wrong.

**Comment by patrix58** [comment]
I ran into the same issue and found out that the documentation is outdated: the username and the password flags have been removed meantime.

For whoever is looking into this thread in the future, the solution is to run: `docker secret create pullcred /path/to/creds.json`.
And the credential json file should be in this format:
```json
{
  "username":"DockerHubID",
  "password":"GeneratedHubTokenOrPassword"
}
```

Source: https://github.com/docker/compose-cli/blob/main/docs/ecs-compose-examples.md

**Comment by ndeloof** [comment]
Doc is indeed outdated, I proposed a PR to fix this
