### ISSUE TITLE
service using EC2 should have CapacityProviderStrategy set

### ISSUE THREAD

**Issue by ndeloof** [docker/compose-cli#778]
**Description**
As we configure a service with specific resources to require an EC2 capacity provider, service should be defined with a capcity provider strategy so that we enforce it get ran by the expected CP.

This is currently blocked by https://github.com/aws/containers-roadmap/issues/631

Also, as stated by the [CapacityProviders doc](https://docs.amazonaws.cn/en_us/AmazonECS/latest/developerguide/cluster-capacity-providers.html):

> When a capacity provider strategy is used, a launch type may not be specified and vice versa. 

we need to fix service definition so it doesn't set a value to service LaunchType when we expect the use of a capacity provider.

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by SPTKL** [comment]
I'm having the same issue, I'm trying to specify CapacityProviderStrategy in `x-aws-cloudformation` but `docker compose` by default generates a `launchType: EC2`, even tho with capacity provider we don't need launchtype at all

**Comment by JohnPreston** [comment]
@ndeloof 
Using docker compose syntax buy not using the ECS plugin, you can use ECS Compose-X to do all of that in a much simpler way than using the x-aws-cloudformation marker.
Linking to nightly docs given 0.18 is just coming out this week.
Hope this helps
https://nightly.docs.compose-x.io/syntax/compose_x/ecs.details/ecs.html#capacityproviderstrategy
