### ISSUE TITLE
CLI json format: return json array instead of multi-json (one per line)

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#794]
`docker --context aci ps --format json` currently outputs one json line per returned resource, like the docker cli does historically. 
`jq` supports this nicely, but for better integration with any json tool, it seems returning a json array ([{...}, {...}] could be more suitable.
@thaJeztah any historical reason we should be aware of for this choice in the docker CLI ?

The same applies for other commands in the new CLI returning lists of objects: `compose ls`, `compose ps`, `context ls`, `volume ls`, `secret ls`

**Comment by thaJeztah** [comment]
There's a very old discussion in https://github.com/moby/moby/issues/20625 (and somewhat related, but on the API in https://github.com/moby/moby/issues/16925 and https://github.com/moby/moby/pull/17349).

I think the main motivation for this (at least at the API level) was for performance; the multi-json / [JSON streaming](https://en.wikipedia.org/wiki/JSON_streaming) to allow streaming the results; a JSON array would require the results to be buffered, waiting for all results to arrive; while this could work for _some_ endpoints, it may be troublesome for others (swarm clusters with many results), or "_impossible_" for others (pull progress etc).

I agree that having an array would be less surprising, that said; we should think through if that would be kicking the can down the road, and if at some point having to buffer all results before printing would become a problem for us.

Given that (possibly) not all output can be output as an array; if that's the case, it would be equally confusing to users that some commands output an array, other a JSON-stream (line-delimited), so possibly documenting "how to work with JSON stream output" would be the alternatives.

**Comment by thaJeztah** [comment]
related; https://github.com/microsoft/vscode-docker/issues/2452, https://github.com/docker/compose-cli/pull/854
