### ISSUE TITLE
Can't log in to Azure in GitHub Codespace environment

### ISSUE THREAD

**Issue by karolz-ms** [docker/compose-cli#814]
**Description**

In GitHub Codespace environment, the CLI attempts to open a web browser via `xdg-open` when doing `docker login azure`. This fails.

**Steps to reproduce the issue:**
1. Create GitHub Codespace and [install Docker CLI](https://github.com/docker/compose-cli/blob/main/INSTALL.md#ubuntu-linux-installation) into it.
2. Do `docker login azure`

**Describe the results you received:**

Error: the message asks to open https://microsoft.com/devicelogin with a specific authN code (correct), but it does not wait for the user to do so. Instead it tries to use `xdg-open` utility to open the browser and that fails, causing the whole command to fail.

Also see https://github.com/microsoft/vscode-docker/issues/2391 (VS Code scenario) 

**Describe the results you expected:**

The command should wait for the user to open the browser manually and authenticate (which will cause the token endpoint to return a token to the CLI).

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
Docker 19.03.13
Cloud integration 0.1.18
```

I thought  docker/compose-cli#575 docker/compose-cli#510 would cover this scenario, but it does not seem so.

**Comment by gtardif** [comment]
@rumpl You did run the cli with ACI integration in codespaces and logged into azure using device code flow, if I remember correctly. Do you see any hint with the above scenario, that would be different from what you did ?

**Comment by rumpl** [comment]
@karolz-ms Can you retry please? I just tried this and it worked:

```
codespace ➜ ~/workspace/compose-cli (main) $ curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5888  100  5888    0     0  122Running checks...- --:--:-- --:--:--     0
07      0 --:--:-- --:--:-- --:--:-- 12215
Warning: This script has been tested on Ubuntu and may not work on other distributions
Checks passed!
Downloading CLI...
Downloaded CLI!
Installing CLI...
Done!
codespace ➜ ~/workspace/compose-cli (main) $ docker login azure
Could not automatically open a browser, falling back to Azure device code flow authentication
2020/11/02 09:12:46 To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code XXXXXXXX to authenticate.
login succeeded
codespace ➜ ~/workspace/compose-cli (main) $ 
```

**Comment by karolz-ms** [comment]
@rumpl thanks! Will do and will report back

**Comment by karolz-ms** [comment]
Works well for me too! ☺️ 

Thanks @rumpl for looking into it
