### ISSUE TITLE
Storage account not created automatically during CD to Azure 

### ISSUE THREAD

**Issue by karolz-ms** [docker/compose-cli#815]
**Description**

I was under impression that, when deploying a Compose project to ACI, the storage account specified for a file share does not exist, it will be automatically provisioned. This does not happen in a CD scenario using GitHub actions and service principal account for authenticating Docker CLI to Azure.

**Steps to reproduce the issue:**
1. Follow instructions in https://github.com/karolz-ms/actions-composecli-demo/blob/main/README.md, including deploying the application to Azure (verify everything works as expected)
2. Delete storage account created in step 5 of the instructions
3. Try to re-deploy the app (re-run `DeployApp` workflow)

**Describe the results you received:**

Error:
```
could not access storage account acountKeys for gbexpresssa201013a, 
using the azure login: storage.AccountsClient#ListKeys: 
Failure responding to request: StatusCode=404 -- 
Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" 
Message="The Resource 'Microsoft.Storage/storageAccounts/gbexpresssa201013a' under resource group '
rg-guestbookexpress' was not found. 
For more details please go to https://aka.ms/ARMResourceNotFoundFix"
```

**Describe the results you expected:**

The storage account should be automatically created as part of application deployment.

**Output of `docker version`:**

```
Client:
 Cloud integration: 0.1.22
 Version:           19.03.13+azure
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        cd8016b6bcc51a51f577bcffb37e6a870f7813f9
 Built:             Tue Sep 15 23:02:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       bd33bbf0497b2327516dc799a5e541b720822a4c
  Built:            Mon Mar 12 00:00:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7+azure
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
```

**Comment by gtardif** [comment]
Hi @karolz-ms, actually deploying a Compose file to ACI with a fileshare will not automatically provision the storage account, it will fetch keys for the storage account automatically from your azure login but the storage account and fileshare must be created explicitly before deploying the application (and their lifecycle is totally separated from the Compose application lifecycle). 
It should work the same with manual login or Service Principal login in a CI scenario.

Note that you can manage volume creation/deletion so in the CI with `docker volume create` and `docker volume rm`

**Comment by karolz-ms** [comment]
@gtardif thank you and sorry, I got the feature design wrong 😊
