### ISSUE TITLE
ECS Load Balancer options

### ISSUE THREAD

**Issue by dalegaspi** [docker/compose-cli#821]
Hello!

I know there is a `x-aws-loadbalancer` option to use an existing load balancer but per the documentation it says it should be top level...would it be possible to make this "service-level" configuration in case the services will need to expose ports and need to be mapped to different existing load balancers?

Also speaking of load balancers, although we have this, now i think it would be better if there's a way to set the port of the load balancer itself (instead of using the same that is exposed by the service in docker-compose.yml) and set the type of load balancer (i.e., to specify if ALB or NLB) instead of inferring type via the `x-aws-protocol`.

**Comment by ndeloof** [comment]
> would it be possible to make this "service-level" configuration

that's technicaly feasible, what would be the use-case for this ?

> a way to set the port of the load balancer itself instead of using the same that is exposed by the service

`published` port could indeed be set to load balancer public port. But Service to service communication doesn't go through the LB, and so the compose application would have distinct behaviour when ran locally vs deployed on ECS: service would have to connect to depencies by internal port, not published one.

we _could_ introduce yet another `x-aws-*` field to define LoadBalancer public port, but I'd prefer we avoid too many custom extensions, as the mapping is already complex for newcomers.

Reasoning on `x-aws-protocol` is that such an attribute could make sense outside AWS context, and be adopted by compose-spec.

**Comment by dalegaspi** [comment]
> that's technicaly feasible, what would be the use-case for this?

we are using docker compose for an API with an envoy side-car... normally entry point is through side car but there will be use cases to bypass it...we could have the bypass through an internal ALB only so assigning a different LB for that bypass will be better and we can also expose the same port. 

as for further customization...yes, i get the reluctance to add more `x-aws-*` so maaaaaybe support an `ecs_params.yml` file instead just like ecs-cli so you don't pollute the docker-compose file with custom ecs-specific fields?
