### ISSUE TITLE
ACI: Allow volume creation from `compose up` deployment

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#841]
Current ACI integration requires volumes to be created *before* (through `docker volume create`) they can be used in compose files. This is not the case with `docker-compose up` nor with the ECS integration. 

Compose files using ACI volumes include all the necessary information to create the volume while deploying to ACI with  `docker compose up`, if the Azure File Share does not exist yet. (of course if it exists the ACI deployment will simply connect to the existing volume)
the `compose down` command should display a warning to make sure users are aware there is some remaining resources not deleted when the compose file uses ACI volumes.

**Comment by karolz-ms** [comment]
@bigmorty say you love this! ☺️

**Comment by BigMorty** [comment]
I LOVE this! :-) @gtardif, can you explain in detail when/if the volume is deleted on compose down?
