### ISSUE TITLE
ECS documentation does not describe how to create ECS contexts in Linux.

### ISSUE THREAD

**Issue by billycao** [docker/compose-cli#847]
**Description**

[ECS documentation](https://docs.docker.com/engine/context/ecs-integration/) does not describe how to create ECS contexts in Linux.

**Steps to reproduce the issue:**
1. Install Docker Engine and docker-compose on Linux.
2. Run "docker context create ecs myecscontext" as [documentation](https://docs.docker.com/engine/context/ecs-integration/) describes.

**Describe the results you received:**

`$ docker context create ecs spineaiecs`
`"docker context create" requires exactly 1 argument.`

**Describe the results you expected:**

Since the documentation states "Alternatively, install the Docker Compose CLI for Linux.", I expected a way to easily create an ECS docker context in Linux.

**Additional information you deem important (e.g. issue happens only occasionally):**

I exclusively use Docker Engine on Linux machines so not familiar with Docker Desktop and how docker-compose integrates with it.

I wanted to experiment with this new ECS integration to simply my deployments and documentation seems to suggest that this is possible in Linux as well. Thanks for working on this!

Snooped around in source but couldn't find an easy answer. Sorry if I'm missing something obvious. Thanks!

**Output of `docker version`:**

```
Client: Docker Engine - Community
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 17:02:36 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:01:06 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 nvidia:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683z
```

**Comment by ndeloof** [comment]
"_Alternatively, install the Docker Compose CLI for Linux._" only applies on installing the ECS integration, creating ECS context is the same for all installations. I guess we need to rephrase for clarity

**Comment by mjpowersjr** [comment]
I found this issue while troubleshooting the same error. The fix seems to be enabling *experimental* support for the Linux version of Docker. See more details here:

https://github.com/docker/docker.github.io/issues/11845

**Comment by socketbox** [comment]
@ndeloof I think you missed the point of this issue. To wit, the documentation is inadequate for the task of creating an ECS context because the command specified in the page referenced does not produce a context, but rather an error.

Why was this issue closed? What work was done in order to address it?
