### ISSUE TITLE
All ECS Tasks are recreated even when no changes are made to the related service during updates

### ISSUE THREAD

**Issue by flaviostutz** [docker/compose-cli#858]
**Description**

When updating a docker-compose.yml for a running stack and updating it (docker compose up), all TaskDefinitions are recreated making all Tasks to be down/up again, even when no changes were performed to the service.

**Steps to reproduce the issue:**
1. Create a docker-compose.yml with some ENVs in two services
2. Run `docker compose up` and wait for completion
3. Change the ENV value of only one service
4. Run `docker compose up`
5. Check the ECS panel and see a new TaskDefinition version and the recreation of all Tasks

**Describe the results you received:**
![image](https://user-images.githubusercontent.com/7790172/97785117-dbf61200-1b81-11eb-827a-1e39f2c0ec70.png)

**Describe the results you expected:**
I expected the rollout of only the Tasks for the updated service, keeping others untouched

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
(paste your output here) 
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-tp-docker)
  scan: Docker Scan (Docker Inc., v0.3.4)

Server:
 Containers: 0
  Running: 0
  Paused: 0
  Stopped: 0
 Images: 401
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: active
  NodeID: vfw3bft5qkwxp8f2x8me35t5d
  Is Manager: true
  ClusterID: 5okhxug6ylqnec72ia0fa3ef7
  Managers: 1
  Nodes: 1
  Default Address Pool: 10.0.0.0/8
  SubnetSize: 24
  Data Path Port: 4789
  Orchestration:
   Task History Retention Limit: 5
  Raft:
   Snapshot Interval: 10000
   Number of Old Snapshots to Retain: 0
   Heartbeat Tick: 1
   Election Tick: 10
  Dispatcher:
   Heartbeat Period: 5 seconds
  CA Configuration:
   Expiry Duration: 3 months
   Force Rotate: 0
  Autolock Managers: false
  Root Rotation In Progress: false
  Node Address: 192.168.65.3
  Manager Addresses:
   192.168.65.3:2377
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 5
 Total Memory: 7.78GiB
 Name: docker-desktop
 ID: M2XC:7THC:EZRF:QYS5:AXAI:HM3J:QTMA:RF3G:EUNT:OOV7:X2ED:EPYM
 Docker Root Dir: /var/lib/docker
 Debug Mode: false
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
ECS

**Comment by flaviostutz** [comment]
There is something that may be causing this behavior. Two sequencial calls to `docker convert` with the same docker-compose.yml contents generates different Cloudformation templates probably because of parse/rendering ordering of arrays.

See below a snippet comparing those two templates. The contents of the two templates are the same, but some orderings are different.

![image](https://user-images.githubusercontent.com/7790172/97785538-6fc8dd80-1b84-11eb-9fc9-3d3f651b1824.png)

**Comment by ndeloof** [comment]
nice catch, thanks!
