### ISSUE TITLE
Azure Devops Integration fails on volume mount 

### ISSUE THREAD

**Issue by abinashkd** [docker/compose-cli#865]
**Description**

I am trying to integrate a docker compose file in Azure DevOps which will deploy to ACI. In the pipeline I am having problem with volume mounts. The images which doesn't require volume mount gets deployed successfully, but images with volume mount fails with could not find volume source "/proc/"

**Steps to reproduce the issue:**
1. Follow the documentation process of ACI for docker compose. 
2. In Azure DevOps create a release pipeline with below commands in CLI:

#To install docker compose cli
curl -L https://raw.githubusercontent.com/docker/compose-cli/main/scripts/install/install_linux.sh | sh
sudo docker login azure --client-id ** --client-secret ** --tenant-id **

#These to check if paths exists or not:
ls -ltr /var/run/docker.sock
ls -ltr /proc/
ls -ltr /sys/fs/cgroup

which docker 
docker version

sudo docker context create aci myacicontext --resource-group ** --location **

sudo docker context use myacicontext

sudo docker compose up -d

3.

**Describe the results you received:**

Downloading CLI...
Downloaded CLI!
Installing CLI...
Done!

login succeeded

total 8
drwxr-xr-x 3 vsts docker 4096 Nov  3 04:56 _projects-azure-CI
-rw-r--r-- 1 vsts docker  648 Nov  3 04:56 docker-compose.yaml

srw-rw---- 1 root docker 0 Nov  3 04:30 /var/run/docker.sock
total 0
lrwxrwxrwx  1 root            root                          0 Nov  3 04:30 thread-self -> 2575/task/2575
lrwxrwxrwx  1 root            root                          0 Nov  3 04:30 self -> 2575
....
total 0
dr-xr-xr-x 5 root root  0 Nov  3 04:30 systemd
dr-xr-xr-x 2 root root  0 Nov  3 04:30 rdma
...

/usr/local/bin/docker
Client:
 Cloud integration: 1.0.1
 Version:           19.03.13+azure
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        cd8016b6bcc51a51f577bcffb37e6a870f7813f9
 Built:             Tue Sep 15 23:02:04 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.13+azure
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       bd33bbf0497b2327516dc799a5e541b720822a4c
  Built:            Mon Mar 12 00:00:00 2018
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.7+azure
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc92
  GitCommit:        ff819c7e9184c13b7c2607fe6c30ae19403a7aff
 docker-init:
  Version:          0.18.0
  GitCommit:        

  
Successfully created aci context "myacicontext"
myacicontext

could not find volume source "/proc/"
could not find volume source "/var/run/docker.sock/"

[command]/usr/bin/az account clear

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
(paste your output here) 
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Azure ACI

docker-compose.yaml 
```yaml
version: "3"
services: 
  application: 
    image: "image1"
    ports:
      - "8080:8080"
  app2: 
    links: 
      - application
    image: "image2"
    environment: 
      - key1=val1
    volumes: 
      - /proc/:/host/proc/:ro
      - /var/run/docker.sock:/var/run/docker.sock
```

**Comment by gtardif** [comment]
Hi @abinashkd , sorry but you will only be able to mount volumes from Azure File Share, and you have to specify your volume in the volume section, after the service section in the compose file. (see https://docs.docker.com/engine/context/aci-integration/#using-azure-file-share-as-volumes-in-aci-containers)
Especially, you won't be able to mount the docker socket with the Docker ACI integration

**Comment by gtardif** [comment]
We'll see to at least make the error message more explicit
