### ISSUE TITLE
ecs-params.yml support

### ISSUE THREAD

**Issue by totalhack** [docker/compose-cli#885]
I gather from the discussion [here](https://github.com/docker/compose-cli/issues/821#issuecomment-714427809) that there is no support for reading in ecs-params.yml. 

Are there any plans to support that? Am I missing where it is otherwise documented how to replace some of the configuration that would go in there? For example, where would I specify task cpu and memory limits, as well as service cpu and memory limits? Should I be going off the `ecs-cli` compose [docs](https://docs.aws.amazon.com/AmazonECS/latest/developerguide/cmd-ecs-cli-compose-parameters.html) and assuming those params will work in my `docker-compose.yml`?

Thanks for your help. While this may not be an "issue" and/or is planned behavior, I'm hoping at least documenting it here will help someone else down the road.

**Comment by ndeloof** [comment]
Docker ECS integration is a distinct product and don't support ecs-cli configuration files

You can configure service cpu and memory limits using the standard compose attributes:
```yaml
services:
  foo:
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: 128m
```

Generally speaking, we focus on embracing the existing docker-compose usages and warn user when something isn't supported, vs documenting usage from scratch

**Comment by totalhack** [comment]
Got it, thanks for the feedback.
