### ISSUE TITLE
go 1.15.3 required but not available

### ISSUE THREAD

**Issue by cch1** [docker/compose-cli#902]
https://github.com/docker/compose-cli/blob/949f0ce62ea5e7b2059bf67e12c61213ff00dbd6/Dockerfile#L18

It appears that the image for `docker.io/library/golang:1.15.3-alpine@sha256:df0119b970c8e5e9f0f5c40f6b55edddf616bab2b911927ebc3b361c469ea29c` is not available.

**Comment by cch1** [comment]
I'm actually not sure this is the proper description for the problem I see.  In any case, it's not possible to run the default Makefile target in the repo after c8b8a9f767664fc2f9c0eeba3196b65e1d84b286

**Comment by ndeloof** [comment]
``
`
➜  ~ docker pull golang:1.15.3-alpine
1.15.3-alpine: Pulling from library/golang
188c0c94c7c5: Already exists 
0ef7d3d256c8: Already exists 
de9db76c5a1d: Already exists 
0eba1c9be4d2: Already exists 
0d57e429df01: Already exists 
Digest: sha256:df0119b970c8e5e9f0f5c40f6b55edddf616bab2b911927ebc3b361c469ea29c
Status: Downloaded newer image for golang:1.15.3-alpine
docker.io/library/golang:1.15.3-alpine
```

not sure what's wrong with your setup

**Comment by cch1** [comment]
Is it relevant that I don't see the `1.15.3` tag here: 

https://registry.hub.docker.com/_/golang/

?

**Comment by ndeloof** [comment]
DockerHub usability UX issue it seems :)
This image has so much tags that the main tag list is useless, using a tag filter make it more relevant:
https://registry.hub.docker.com/_/golang?tab=tags&page=1&name=1.15.3

**Comment by cch1** [comment]
Yep.  I see it now -shoulda looked further.  Regardless, it seems I can't pull 1.15.3 or 1.15.4 -but if I change the one character in the Dockerfile `1.15.3` -> `1.15.2` the build succeeds.

**Comment by cch1** [comment]
@ndeloof Thanks for your patience...  I got it to work, but only by pulling the image _without_ a `--platform` spec.  Then the build worked.

I'm on MacOS ...

```
docker build . --target cli --platform local --build-arg BUILD_TAGS=example,local,e2e --build-arg GIT_TAG=`git describe --tags --match "v[0-9]*"` --output ./bin

=> FAIL

docker pull golang:1.15.3-alpine

=> SUCCESS

docker build . --target cli --platform local --build-arg BUILD_TAGS=example,local,e2e --build-arg GIT_TAG=`git describe --tags --match "v[0-9]*"` --output ./bin

=> SUCCESS
```
