### ISSUE TITLE
enhancement - allow subnet assignment (thus private IPs) for azure container instances

### ISSUE THREAD

**Issue by qmnonic** [docker/compose-cli#909]
**Description**
When deploying from a compose file for Azure, there is no way to specify a subnet to deploy into.
Similarly, all deployments have a public ip.  If deployed to a subnet, it should be a private IP.

Ideally, there should be a way to deploy to a subnet, which would allow access to protected resources and leverage existing azure networking rules.

I checked the source and didn't see any reference to subnet or vnet in the aci code.

**Steps to reproduce the issue:**
Deploy any container to azure.

**Describe the results you received:**
No error.  Observed while trying to map a volume to azure storage, which is not publicly accessible.  While this can be resolved in azure by provisioning access to a single IP, it means the app deployed is public.

**Describe the results you expected:**
Ideally, there should be a way to deploy to a subnet, which would allow access to protected resources and leverage existing azure networking rules.  Container Instance should not have a public IP.

https://docs.microsoft.com/en-us/azure/container-instances/container-instances-vnet

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
mattm$ docker version
Client: Docker Engine - Community
 Cloud integration  0.1.18
 Version:           19.03.13
 API version:       1.40
 Go version:        go1.13.15
 Git commit:        4484c46d9d
 Built:             Wed Sep 16 16:58:31 2020
 OS/Arch:           darwin/amd64
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          19.03.13
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       4484c46d9d
  Built:            Wed Sep 16 17:07:04 2020
  OS/Arch:          linux/amd64
  Experimental:     true
 containerd:
  Version:          v1.3.7
  GitCommit:        8fba4e9a7d01810a393d5d25a3621dc101981175
 runc:
  Version:          1.0.0-rc10
  GitCommit:        dc9208a3303feef5b3839f4323d9beb36df0a9dd
 docker-init:
  Version:          0.18.0
  GitCommit:        fec3683
 Kubernetes:
  Version:          v1.11.9
  StackAPI:         Unknown
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
<redacted>
```

**Output of `docker info`:**

```
Client:
 Debug Mode: false
 Plugins:
  app: Docker Application (Docker Inc., v0.8.0)
  buildx: Build with BuildKit (Docker Inc., v0.4.2-tp-docker)
  scan: Docker Scan (Docker Inc., v0.3.4)

Server:
 Containers: 4
  Running: 1
  Paused: 0
  Stopped: 3
 Images: 59
 Server Version: 19.03.13
 Storage Driver: overlay2
  Backing Filesystem: extfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 8fba4e9a7d01810a393d5d25a3621dc101981175
 runc version: dc9208a3303feef5b3839f4323d9beb36df0a9dd
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 4.19.76-linuxkit
 Operating System: Docker Desktop
 OSType: linux
 Architecture: x86_64
 CPUs: 2
 Total Memory: 3.848GiB
 Name: docker-desktop
 ID: ZBB7:4YCC:JIN7:Z6G7:LGPM:Q3RT:6AQ7:T5UD:REET:3LAF:ZQFP:RDWH
 Docker Root Dir: /var/lib/docker
 Debug Mode: true
  File Descriptors: 47
  Goroutines: 52
  System Time: 2020-11-13T19:52:14.015753Z
  EventsListeners: 3
 HTTP Proxy: gateway.docker.internal:3128
 HTTPS Proxy: gateway.docker.internal:3129
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: true
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
 Product License: Community Engine```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**
Azure ACI.

**Comment by gtardif** [comment]
Hi @qmnonic , 
Thanks for the feedback. This is actually already requested in #654 (which you can up-vote)

Closing this as a duplicate, we'll track it in #654

**Comment by pietelite** [comment]
@qmnonic I appreciate you bringing this up on this thread again. I'm just coming across this issue right now: I have an application that I have completely prepared for deployment and I have my domain but I would like to get my SSL set up to a permanent public IP but with the current deployment with `docker compose` and the azure context method, I cannot get specify the vnet/subnet to then use the network gateway.

Do you have another solution/workaround while this is being worked on? (I would love to do this in the CLI but that could be well off) The Azure Portal doesn't seem to have suitable ways to do all of setting up a multi-container instance with docker compose configuration files and specify vnet/subnet.

**Comment by qmnonic** [comment]
In my case, I switched to an ARM template, which isn’t as portable or easy
to read.

**Comment by ChristSent** [comment]
@pietelite You could use Azure Application Gateway as a reverse proxy to your backend. You can specify a permanent dns name in your compose file for ACI. That is all you'll need to configure the App Gateway
