### ISSUE TITLE
Could you please help clarify how to connect Azure China Cloud with `docker login` cmdlet?

### ISSUE THREAD

**Issue by rockboyfor** [docker/compose-cli#917]
**Description**

**Steps to reproduce the issue:**
1. Could you please help clarify how to connect the Azure China Cloud with `docker login` cmdlet?
2. I have try to use `docker login https://login.partner.microsoftonline.cn/` but failed, Is there any tips to connect Azure China Cloud?
3. Looking forward to your early replace.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important (e.g. issue happens only occasionally):**

**Output of `docker version`:**

```
(paste your output here)
```

**Output of `docker context show`:**  
You can also run `docker context inspect context-name` to give us more details but don't forget to remove sensitive content.

```
(paste your output here) 
```

**Output of `docker info`:**

```
(paste your output here)
```

**Additional environment details (AWS ECS, Azure ACI, local, etc.):**

**Comment by rockboyfor** [comment]
Is there any schedule to append the Azure China Cloud login parameter to suit Azure China Cloud?

const (
	// AcrRegistrySuffix suffix for ACR registry images
	AcrRegistrySuffix         = ".azurecr.io"
	activeDirectoryURL        = "https://login.microsoftonline.com"
	azureManagementURL        = "https://management.core.windows.net/"
	azureResouceManagementURL = "https://management.azure.com/"
	authorizeFormat           = activeDirectoryURL + "/organizations/oauth2/v2.0/authorize?response_type=code&client_id=%s&redirect_uri=%s&state=%s&prompt=select_account&response_mode=query&scope=%s"
	tokenEndpoint             = activeDirectoryURL + "/%s/oauth2/v2.0/token"
	getTenantURL              = azureResouceManagementURL + "tenants?api-version=2019-11-01"

	// scopes for a multi-tenant app works for openid, email, other common scopes, but fails when trying to add a token
	// v1 scope like "https://management.azure.com/.default" for ARM access
	scopes   = "offline_access " + azureResouceManagementURL + ".default"
	clientID = "04b07795-8ddb-461a-bbee-02f9e1bf7b46" // Azure CLI client id
)

Best Regards!

**Comment by gtardif** [comment]
Unfortunately this is not supported yet. 
Azure China cloud is a specific case of https://github.com/docker/compose-cli/issues/658

**Comment by gtardif** [comment]
Closing this one as a duplicate, tracking this in #658
