### ISSUE TITLE
Local Compose: build as part of compose up

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#927]
Using compose command in local context, I should be able to run `docker compose build` and build images in my compose file that have a `build` section and associated Dockerfile, like in `docker-compose`. 

This should use buildkit engine to build Docker images locally.

Other backends (cloud backends) will return `not implemented` on this command

**Comment by ndeloof** [comment]
we can re-use code from docker/app for this purpose: 
https://github.com/docker/app/blob/c51fa999dbc1cd47a5c8de36649ce884520c0bc5/internal/commands/build/build.go#L202
