### ISSUE TITLE
Local compose: push command

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#931]
Using compose command in local context, I should be able to run `docker compose push` and push images in my compose file, like in `docker-compose`.

Other backends (cloud backends) will return not implemented on this command.

**Comment by ndeloof** [comment]
Considering the "build, test local, push, run on the cloud" scenario, this build process _should_ be designed so we can retrieve the image sha256 and use those for the "cloud" part.
This would help fix https://github.com/docker/compose-cli/issues/612
Maybe we can store image shas into a `.docker-compose` file at project root, or something comparable, to avoid makeing changes to user's `compose.yaml` file
