### ISSUE TITLE
Local compose: run command

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#940]
Using compose command in local context, I should be able to run `docker compose run` and run a specific command in a new container started from one service spec, like in `docker-compose`

**Comment by gtardif** [comment]
Will need to update oneoff label for "compose run" containers, at https://github.com/docker/compose-cli/blob/main/local/compose.go#L371

**Comment by ndeloof** [comment]
Implementation note: new `compose run` command could tweak the compose model to force target service with: 

* scale=1 
* command, env, etc as set by command
* create random slug 
* set label com.docker.compose.slug for target service
* for container name = project_service_run_slug

then 
* use the existing `Create` API to create containers for the stack 
* introduce a new `Attach` API to attach to container in/ou streams
* Start the stack without attaching to other services output
