### ISSUE TITLE
Local compose: attach to logs when 'compose up' by default

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#970]
if the `--detach` flag is not specified, `docker compose up` should attach to compose logs by default.

**Comment by ndeloof** [comment]
I wonder about interactions with the progressWriter ...
Or shall we just chain `logs` after `up` completed? Which is not the same as `docker-compose up`

**Comment by flaviostutz** [comment]
Isn't this issue solved by the mentioned PR #998?
