### ISSUE TITLE
Local compose: down does not removed previously stopped containers

### ISSUE THREAD

**Issue by gtardif** [docker/compose-cli#993]
After a `docker compose up`, if I stop one container manually and then issue `docker compose down`,  the stopped container does not get removed. 
Re-issuing `docker compose up` then leads to 
`Error response from daemon: Conflict. The container name "/elasticsearch-logstash-kibana_logstash_1" is already in use by container "a39c92e10af2a04b3de9c622a47906735a89512e0120f609fb7477bcb29b20ba". You have to remove (or rename) that container to be able to reuse that name.`

**Comment by ndeloof** [comment]
I'll look into this as soon as https://github.com/docker/compose-cli/pull/968 is merged
